force-app/main/default/objects/DeliveryInstructions__c/DeliveryInstructions__c.object-meta.xml
<CustomObject>
    <label>Delivery Instructions</label>
    <nameField> 
        <displayFormat>LV-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber> 
        <label>LVID</label>
        <type>AutoNumber</type> 
    </nameField>
    <pluralLabel>Delivery Instructions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryInstructions__c/fields/AdditionalTitle__c.field-meta.xml
<CustomField>
    <fullName>AdditionalTitle__c</fullName>
    <label>Additional Title  </label> 
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/DateOfIssue__c.field-meta.xml
<CustomField>
    <fullName>DateOfIssue__c</fullName>
    <label>Date Of Issue  </label> 
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/FlagMonthYearOnly__c.field-meta.xml
<CustomField>
    <fullName>FlagMonthYearOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flag MonthYear Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label> 
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision  </label> 
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName> 
    <label>Title  </label> 
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentTemplate/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>   
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeliveryInstrPDFGenerationTest.cls
/****************************************************************************
* Name: DeliveryInstrPDFGenerationTest
* Author: Naina Butle
* Created Date: 22/11/2023
* Description: test class of DeliveryInstrPDFGeneration.
*****************************************************************************
* Modification log
* Name		Date	           		Description
* Developer Name	Date of Modification	Modification Description  
****************************************************************************/
@isTest
public class DeliveryInstrPDFGenerationTest {
    
    @TestSetup
    static void createTestData(){
        TestDataFactory.createDeliveryInstruction();
        TestDataFactory.createdocumentTemplate(1);
    }
    
    @isTest 
    static void testcreateDocumentGenerationProcessRequest(){
        Test.startTest();
         List<DeliveryInstructions__c> deliveryInst = [SELECT Id, Name, Title__c, AdditionalTitle__c, FlagMonthYearOnly__c, DateOfIssue__c, Language__c, Revision__c  FROM DeliveryInstructions__c LIMIT 1];
		 deliveryInst[0].Language__c = 'DE';
         deliveryInst[0].AdditionalTitle__c = 'AddT';
         deliveryInst[0].Revision__c = 'Rev';
         deliveryInst[0].DateOfIssue__c = system.Today();
        update deliveryInst[0];
        DeliveryInstrPDFGeneration.createDocumentGenerationProcessRequest(new List<Id>{deliveryInst[0].Id});
        Test.stopTest();
        System.assertEquals(deliveryInst[0].Language__c, 'DE' , 'Language should be DE');
    }
    
    @isTest 
    static void testcreateDocumentGenerationProcessRequestEn(){
        Test.startTest();
         List<DeliveryInstructions__c> deliveryInst = [SELECT Id, Name, Title__c, AdditionalTitle__c, FlagMonthYearOnly__c, DateOfIssue__c, Language__c, Revision__c  FROM DeliveryInstructions__c LIMIT 1];
		 deliveryInst[0].Language__c = 'EN';
         deliveryInst[0].AdditionalTitle__c = 'AddT';
         deliveryInst[0].Revision__c = 'Rev';
         deliveryInst[0].DateOfIssue__c = system.Today();
        deliveryInst[0].FlagMonthYearOnly__c = true;
        update deliveryInst[0];
        List<DocumentTemplate> documentTemplate = [SELECT id, Name, Language__c FROM DocumentTemplate LIMIT 1];
        documentTemplate[0].Language__c = 'EN';
        update documentTemplate[0];
        DeliveryInstrPDFGeneration.createDocumentGenerationProcessRequest(new List<Id>{deliveryInst[0].Id});
        Test.stopTest();
        System.assertEquals(deliveryInst[0].Language__c, 'EN' , 'Language should be EN');
    }
}