force-app/main/default/objects/ManagingVisitReports__mdt/ManagingVisitReports__mdt.object-meta.xml
<CustomObject>
    <label>Visit Report Settings</label> 
    <pluralLabel>Visit Report Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ManagingVisitReports__mdt/fields/ExtendedContactsasAttendees__c.field-meta.xml
<CustomField>
    <fullName>ExtendedContactsasAttendees__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be set as TRUE if you want to add as attendees contacts that are related to accounts other than the one for which the visit report was created.</description>
    <label>Extended Contacts as Attendees</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ManagingVisitReports__mdt/fields/ExtendUsersasAttendees__c.field-meta.xml
<CustomField>
    <fullName>ExtendUsersasAttendees__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be set as TRUE if you want to add internal users as attendees for visit reports.</description>
    <label>Extend Users as Attendees</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ManagingVisitReports__mdt/fields/ManageChecklists__c.field-meta.xml
<CustomField>
    <fullName>ManageChecklists__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field should be set as TRUE if the the Manage Checklists functionality should be available to users.</description>
    <label>Manage Checklists</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ManagingVisitReports__mdt/fields/ManageExternalAttendees__c.field-meta.xml
<CustomField>
    <fullName>ManageExternalAttendees__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be set as TRUE if the the Manage External Attendees functionality should be available to users.</description>
    <label>Manage External Attendees</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ManagingVisitReports__mdt/fields/ManageInternalAttendees__c.field-meta.xml
<CustomField>
    <fullName>ManageInternalAttendees__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field should be set as TRUE if the the Manage Internal Attendees functionality should be available to users.</description>
    <label>Manage Internal Attendees</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit Management</label>
    <nameField>
        <displayFormat>B-{YYYY}-{0}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Management</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visitor/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName> 
    <label>Comment</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Visitor/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName> 
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field defines the contact this junction record is related to.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visitors</relationshipLabel>
    <relationshipName>Visitors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visitor/fields/IsPrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryContact__c</fullName> 
    <defaultValue>false</defaultValue>
    <label>Is Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visitor/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>  
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visitors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visitor__c/Visitor__c.object-meta.xml
<CustomObject>
    <label>Visitor</label>
    <nameField>
        <label>Visitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visitor__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Visitor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Assignee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visitors</relationshipLabel>
    <relationshipName>Visitors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visitor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visitors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visitor__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visitors</relationshipLabel>
    <relationshipName>Visitors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VisitReportController.cls
/****************************************************************************
* Name: VisitReportController
* Author: Harshitha U
* Created Date: 02/11/2023
* Description: VisitReportController class is used to process data related to Visit.
*****************************************************************************/
/*****************************************************************************
* Modification log
* Name              Date                    Description
* Developer Name    Date of Modification    Modification Description 
****************************************************************************/
public with sharing class VisitReportController {
  @TestVisible
  private static Boolean coverCode = false;
  /********************************************************************************************************
   * @author           Harshitha U
   * @description      This method will retrieve the record from Visitor Settings medatadata
   * @param            void
   * @return           Map<String, Boolean>
   *********************************************************************************************************/
  @AuraEnabled
  public static Map<String, Boolean> displayManageVisitReportTiles() {
    try {

      ManagingVisitReports__mdt visitReportSettings = VisitReportUtility.getVisitReportSettingsMetadata();

      Map<String, Boolean> mapManagingVisitReports = new Map<String, Boolean>();
      if (visitReportSettings != null) {
        mapManagingVisitReports.put(
          'Manage_Internal_Attendees',
          visitReportSettings.ManageInternalAttendees__c
        );

        mapManagingVisitReports.put(
          'Manage_External_Attendees',
          visitReportSettings.ManageExternalAttendees__c
        );

        mapManagingVisitReports.put(
          'Manage_Checklists',
          visitReportSettings.ManageChecklists__c
        );
      }

      return mapManagingVisitReports;
    } catch (Exception e) {
       String exdetails = e.getCause()+' ; '+e.getLineNumber() + ' ; '+e.getMessage()+' ; '+e.getStackTraceString()
                +' ; '+e.getTypeName() ;
       ExceptionUtilClass.publishException('Visit__c','Manage Visits',null,exdetails,ConstantClass.APEX_CLASS);
            
   
    }
    return null;
  }
    /********************************************************************************************************
   * @author           Harshitha U
   * @description      This method will return the information about 2 fields <ExtendedContactsasAttendees__c> and <ExtendUsersasAttendees__c> from Visitor Settings metadata
   * @return           Map<String, Boolean>
   *********************************************************************************************************/
  @AuraEnabled
  public static Map<String, Boolean> getExtendedFieldsValue() {

      ManagingVisitReports__mdt visitReportSettings = VisitReportUtility.getVisitReportSettingsMetadata();

      Map<String, Boolean> mapManagingVisitReports = new Map<String, Boolean>();
      if (visitReportSettings != null) {
        mapManagingVisitReports.put(
          'Extended_Contacts',
          visitReportSettings.ExtendedContactsasAttendees__c
        );

        mapManagingVisitReports.put(
          'Extended_Users',
          visitReportSettings.ExtendUsersasAttendees__c
        );
      }

      return mapManagingVisitReports;
  }

    /********************************************************************************************************
   * @author           Harshitha U
   * @description      This method is used to insert a list of attendees.
   * @param            String jsonInput, String vrId
   *********************************************************************************************************/
  @AuraEnabled
  public static void insertAttendees(String jsonInput, String vrId) {
            try {
      //Boolean isValidAttendee = GlobalConstantClass.chkAccess('Visitor', 'Creating', new List<String>{'VisitId', 'Contact__c', 'User__c', 'Comment__c', 'IsPrimaryContact__c'});
      //if(isValidAttendee) {  
        List<Map<String, String>> deserializedMap = new List<Map<String, String>>(
            (List<Map<String, String>>) JSON.deserialize(
              jsonInput,
              List<Map<String, String>>.class
            )
        );
        List<Visitor__c> attendeesList = new List<Visitor__c>();
        for(Map<String, String> attendeeMap : deserializedMap){
          Visitor__c attendee = new Visitor__c();
          attendee.Visit__c = vrId;
          if(attendeeMap.get('Account.Name') != null) {
            attendee.Contact__c = attendeeMap.get('Id');
            //attendee.AssigneeId = attendeeMap.get('Id');
          }
          else {
            attendee.User__c = attendeeMap.get('Id');
            //attendee.AssigneeId = attendeeMap.get('Id');
          }
          if(attendeeMap.get('detailedComment') != null && attendeeMap.get('detailedComment') != ''){
            attendee.Comment__c = attendeeMap.get('detailedComment');
          }
          /*if(attendeeMap.get('isPrimaryContact') != null && attendeeMap.get('isPrimaryContact') != ''){
            attendee.IsPrimaryContact__c = Boolean.valueOf(attendeeMap.get('isPrimaryContact'));
          }*/
          attendeesList.add(attendee);
        }
        if(attendeesList.size() > 0){
          insert attendeesList;
        }
      //}
    } catch (Exception e) {
        String exdetails = e.getCause()+' ; '+e.getLineNumber() + ' ; '+e.getMessage()+' ; '+e.getStackTraceString()
                +' ; '+e.getTypeName() ;
       ExceptionUtilClass.publishException('Visit__c','Manage Visits',null,exdetails,ConstantClass.APEX_CLASS);
    }
  }
}