force-app/main/default/objects/SalesPlanning__c/SalesPlanning__c.object-meta.xml
<CustomObject>
    <label>Absatzplanung</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Absatzplanung</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanning__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Plannings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ActualNetProceeds__c.field-meta.xml
<CustomField>
    <fullName>ActualNetProceeds__c</fullName>
    <label>Actual Net proceeds</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ActualSoldAmount__c.field-meta.xml
<CustomField>
    <fullName>ActualSoldAmount__c</fullName>
    <label>Actual sold amount</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area/Product Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZZ - High Carbon</fullName>
                <label>Drawing Grades - High Carbon</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon - B10</fullName>
                <label>Drawing Grades - Low Carbon - B10</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon</fullName>
                <label>Drawing Grades - Low Carbon (w.o. B10)</label>
            </value>
            <value>
                <fullName>ZZ - Tyre Cord</fullName>
                <label>Drawing Grades - Tyre Cord</label>
            </value>
            <value>
                <fullName>ZZ - Welding Wire (SZW)</fullName>
                <label>Drawing Grades - Welding Wire</label>
            </value>
            <value>
                <fullName>ZW</fullName>
                <label>Bearing Steel</label>
            </value>
            <value>
                <fullName>ZK</fullName>
                <label>Cold Heading</label>
            </value>
            <value>
                <fullName>ZM</fullName>
                <label>Forging Steel</label>
            </value>
            <value>
                <fullName>ZS</fullName>
                <label>Free Cutting Steel (SZO)</label>
            </value>
            <value>
                <fullName>ZF</fullName>
                <label>Spring Steel</label>
            </value>
            <value>
                <fullName>00</fullName>
                <label>Across business Area</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/DeltaNetProceeds__c.field-meta.xml
<CustomField>
    <fullName>DeltaNetProceeds__c</fullName>
    <label>Delta Net proceeds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastLevel__c.field-meta.xml
<CustomField>
    <fullName>ForecastLevel__c</fullName>
    <label>Forecast Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Area/Product Group</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastNetProceeds__c.field-meta.xml
<CustomField>
    <fullName>ForecastNetProceeds__c</fullName>
    <label>Forecast Net proceeds</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastSoldAmount__c.field-meta.xml
<CustomField>
    <fullName>ForecastSoldAmount__c</fullName>
    <label>Forecast sold amount</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastTimePoint__c.field-meta.xml
<CustomField>
    <fullName>ForecastTimePoint__c</fullName>
    <label>Forecast Time point</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RollupFromAccountLevelControllerTest.cls
/****************************************************************************
* Name: RollupFromAccountLevelControllerTest
* Author: Naina B
* Created Date: 28/03/2023
* Description: Test class for RollupFromAccountLevelController
*****************************************************************************
* Modification log
* Name      Date                    Description
* Developer Name    Date of Modification    Modification Description  
****************************************************************************/
@isTest
public class RollupFromAccountLevelControllerTest {
    @testSetup
    static void setUpData(){
        List<SalesPlanning__c> sPLST = TestDataFactory.createSalesPlanning(13);
       List<SalesPlanning__c> spListAccount = TestDataFactory.createSalesPlanningAccount(13);
        List<SalesPlanning__c> spListYearly = TestDataFactory.createYearlySalesPlanning(4);
        List<SalesPlanning__c> spListAccountYearly = TestDataFactory.createAccountYearlySalesPlanning(4);
        Date currentDate = Date.today();
        Integer currentMonth = currentDate.month();
        Integer currentYear = currentDate.year();
        Date fTp;
        List<SalesPlanning__c> SalesPlanBussiness = new List<SalesPlanning__c>();
            for(Integer i= 0 ; i <= 12 ;i++){
                Integer calYear = 0;
                Integer calMonth = 0;
                if(currentMonth + i > 12){
                    calYear = currentYear + 1;
                    calMonth = currentMonth + i - 12;
                }else{
                    calMonth = currentMonth + i;
                    calYear = currentYear;
                }
                fTp = Date.newInstance(calYear, calMonth, 1);
                SalesPlanning__c sp = sPLST[i];
                sp.ForecastTimePoint__c = fTp;
                sp.BusinessArea__c  = 'ZW';
                sp.ForecastSoldAmount__c = 100 + i;
                sp.ForecastNetProceeds__c = 100 + i;
                SalesPlanBussiness.add(sp);
                
                SalesPlanning__c spAccount = spListAccount[i];
                spAccount.ForecastTimePoint__c = fTp;
                spAccount.BusinessArea__c  = 'ZW';
                spAccount.ForecastSoldAmount__c = 100 + i;
                spAccount.ForecastNetProceeds__c = 100 + i;
                spAccount.Frequency__c ='Monthly';
                SalesPlanBussiness.add(spAccount);
            }
        for(integer i=0 ; i <=3 ; i++){
             fTp = Date.newInstance(currentYear + i, i, 1);
             SalesPlanning__c spAccount = spListYearly[i];
                spAccount.ForecastTimePoint__c = fTp;
                spAccount.BusinessArea__c  = 'ZW';
                spAccount.ForecastSoldAmount__c = 100 + i;
                spAccount.ForecastNetProceeds__c = 100 + i;
                spAccount.DeltaNetProceeds__c = 100 + i;
                SalesPlanBussiness.add(spAccount);
            
             SalesPlanning__c spAccountYr = spListAccountYearly[i];
                spAccountYr.ForecastTimePoint__c = fTp;
                spAccountYr.BusinessArea__c  = 'ZW';
                spAccountYr.ForecastSoldAmount__c = 100 + i;
                spAccountYr.ForecastNetProceeds__c = 100 + i;
                spAccountYr.DeltaNetProceeds__c = 100 + i;
                SalesPlanBussiness.add(spAccountYr);
        }
        
        update SalesPlanBussiness;
    }
  
    @isTest static void testOLIRecord(){
      List<SalesPlanning__c> ss = [SELECT Id, Account__c, BusinessArea__c, ForecastTimePoint__c, ForecastSoldAmount__c, ActualSoldAmount__c, ForecastNetProceeds__c, ActualNetProceeds__c, ForecastLevel__c, DeltaNetProceeds__c 
                                                                                       FROM SalesPlanning__c];
        Test.startTest();

         RollupFromAccountLevelController.rollupFromAccountLevelCal();
         RollupFromAccountLevelController.rollupAnnualPlanningCal();

        Test.stopTest();
        system.assertNotEquals(ss.size(), 0,'List should not be empty');
    }
}