force-app/main/default/objects/Account/fields/BusiessAreaForPlanning__c.field-meta.xml
<CustomField>
    <fullName>BusiessAreaForPlanning__c</fullName>
    <label>Business area/Product group for planning</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZK</fullName>
                <label>Cold Heading</label>
            </value>
            <value>
                <fullName>ZF</fullName>
                <label>Spring Steel</label>
            </value>
            <value>
                <fullName>ZS</fullName>
                <label>Free Cutting Steel (SZO)</label>
            </value>
            <value>
                <fullName>ZW</fullName>
                <label>Bearing Steel</label>
            </value>
            <value>
                <fullName>ZM</fullName>
                <label>Forging Steel</label>
            </value>
            <value>
                <fullName>ZZ - Welding Wire (SZW)</fullName>
                <label>Drawing Grades - Welding Wire</label>
            </value>
            <value>
                <fullName>ZZ - Tyre Cord</fullName>
                <label>Drawing Grades - Tyre Cord</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon</fullName>
                <label>Drawing Grades - Low Carbon (w.o. B10)</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon - B10</fullName>
                <label>Drawing Grades - Low Carbon - B10</label>
            </value>
            <value>
                <fullName>ZZ - High Carbon</fullName>
                <label>Drawing Grades - High Carbon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>SAPAccountNumber__c</fullName>
    <label>SAP Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/SalesPlanning__c.object-meta.xml
<CustomObject>
    <label>Absatzplanung</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Absatzplanung</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanning__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Plannings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area/Product Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZZ - High Carbon</fullName>
                <label>Drawing Grades - High Carbon</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon - B10</fullName>
                <label>Drawing Grades - Low Carbon - B10</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon</fullName>
                <label>Drawing Grades - Low Carbon (w.o. B10)</label>
            </value>
            <value>
                <fullName>ZZ - Tyre Cord</fullName>
                <label>Drawing Grades - Tyre Cord</label>
            </value>
            <value>
                <fullName>ZZ - Welding Wire (SZW)</fullName>
                <label>Drawing Grades - Welding Wire</label>
            </value>
            <value>
                <fullName>ZW</fullName>
                <label>Bearing Steel</label>
            </value>
            <value>
                <fullName>ZK</fullName>
                <label>Cold Heading</label>
            </value>
            <value>
                <fullName>ZM</fullName>
                <label>Forging Steel</label>
            </value>
            <value>
                <fullName>ZS</fullName>
                <label>Free Cutting Steel (SZO)</label>
            </value>
            <value>
                <fullName>ZF</fullName>
                <label>Spring Steel</label>
            </value>
            <value>
                <fullName>00</fullName>
                <label>Across business Area</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastLevel__c.field-meta.xml
<CustomField>
    <fullName>ForecastLevel__c</fullName>
    <label>Forecast Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Area/Product Group</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastTimePoint__c.field-meta.xml
<CustomField>
    <fullName>ForecastTimePoint__c</fullName>
    <label>Forecast Time point</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesForecastingBatch.cls
/****************************************************************************
* Name: SalesForecastingBatch
* Author: Impana Paalyam
* Created Date: 17/03/2023
* Description: Batch Class and Scheduled Class to run on July 1st Every Year to create sales planning records.
*****************************************************************************/
global class SalesForecastingBatch implements Database.Batchable<SObject>,Schedulable {   
    global void execute(SchedulableContext SC) {
        SalesForecastingBatch batchJob = new SalesForecastingBatch();
        Database.executeBatch(batchJob);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,name,SAPAccountNumber__c, BusiessAreaForPlanning__c from Account where SAPAccountNumber__c!=null and BusiessAreaForPlanning__c!=null';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        List<SalesPlanning__c> newRecords = new List<SalesPlanning__c>();
        SalesPlanning__c sp = new SalesPlanning__c();
        List<String> businessAreas = new List<String>();
        
        // check if Business Area field is a picklist and retrieve all its values
        if (sp.getSObjectType().getDescribe().fields.getMap().containsKey('BusinessArea__c')) {
            Schema.DescribeFieldResult fieldResult = sp.getSObjectType().getDescribe().fields.getMap().get('BusinessArea__c').getDescribe();
            if (fieldResult.getType() == Schema.DisplayType.PICKLIST) {
                List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
                for (Schema.PicklistEntry picklistValue : picklistValues) {
                    if(picklistValue.isActive()) {
                        businessAreas.add(picklistValue.getValue());
                    }
                }
            }
        }
        //system.debug('****businessAreas***'+businessAreas);
        for (String businessArea : businessAreas) {
            SalesPlanning__c newSP = new SalesPlanning__c();
            newSP.BusinessArea__c = businessArea;
            newSP.ForecastTimePoint__c = Date.newInstance(System.today().year(), 1, 1).addMonths(36);
            newSP.ForecastLevel__c = 'Business Area/Product Group';
            newSP.Frequency__c = 'Yearly';
            newRecords.add(newSP);
        }
        Set<String> busiessAreaValueSet = new Set<String>();
        for (SObject record : scope) {
            Account acc = (Account)record;
            busiessAreaValueSet.addAll(acc.BusiessAreaForPlanning__c.split(';')); 
            //system.debug('****busiessAreaValueSet***'+busiessAreaValueSet);
            for (String businessArea : busiessAreaValueSet) {
                SalesPlanning__c newSP = new SalesPlanning__c();
                newSP.BusinessArea__c = businessArea;
                newSP.ForecastTimePoint__c = Date.newInstance(System.today().year(), 1, 1).addMonths(36);
                newSP.ForecastLevel__c = 'Account';
                newSP.Account__c=acc.id;
                newSP.Frequency__c = 'Yearly';
                newRecords.add(newSP);
            } busiessAreaValueSet.clear();
        }
        
        insert newRecords;
    }
    global void scheduleBatchJob() {
        Datetime jobStart = Datetime.newInstance(2023, 7, 1, 0, 0, 0);
        String cronExp = '0 0 0 1 7 ? *';
        System.schedule('Sales Forecast Batch Job', cronExp, new SalesForecastingBatch());
    }
    
    global void finish(Database.BatchableContext BC) {
        // implementation
    }
}