force-app/main/default/objects/Account/fields/BusiessAreaForPlanning__c.field-meta.xml
<CustomField>
    <fullName>BusiessAreaForPlanning__c</fullName>
    <label>Business area/Product group for planning</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZK</fullName>
                <label>Cold Heading</label>
            </value>
            <value>
                <fullName>ZF</fullName>
                <label>Spring Steel</label>
            </value>
            <value>
                <fullName>ZS</fullName>
                <label>Free Cutting Steel (SZO)</label>
            </value>
            <value>
                <fullName>ZW</fullName>
                <label>Bearing Steel</label>
            </value>
            <value>
                <fullName>ZM</fullName>
                <label>Forging Steel</label>
            </value>
            <value>
                <fullName>ZZ - Welding Wire (SZW)</fullName>
                <label>Drawing Grades - Welding Wire</label>
            </value>
            <value>
                <fullName>ZZ - Tyre Cord</fullName>
                <label>Drawing Grades - Tyre Cord</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon</fullName>
                <label>Drawing Grades - Low Carbon (w.o. B10)</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon - B10</fullName>
                <label>Drawing Grades - Low Carbon - B10</label>
            </value>
            <value>
                <fullName>ZZ - High Carbon</fullName>
                <label>Drawing Grades - High Carbon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/InvoicedOrders__c.object-meta.xml
<CustomObject>
    <label>Invoiced Order</label>
    <nameField>
        <label>Invoiced Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoiced Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicedOrders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Orders</relationshipLabel>
    <relationshipName>Invoiced_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessArea</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/fields/ProductGroupBusinessArea__c.field-meta.xml
<CustomField>
    <fullName>ProductGroupBusinessArea__c</fullName>
    <label>Product Group Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinessArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>BusinessSubgroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/SalesPlanning__c.object-meta.xml
<CustomObject>
    <label>Absatzplanung</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Absatzplanung</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanning__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Plannings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ActualNetProceeds__c.field-meta.xml
<CustomField>
    <fullName>ActualNetProceeds__c</fullName>
    <label>Actual Net proceeds</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ActualSoldAmount__c.field-meta.xml
<CustomField>
    <fullName>ActualSoldAmount__c</fullName>
    <label>Actual sold amount</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area/Product Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZZ - High Carbon</fullName>
                <label>Drawing Grades - High Carbon</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon - B10</fullName>
                <label>Drawing Grades - Low Carbon - B10</label>
            </value>
            <value>
                <fullName>ZZ - Low Carbon</fullName>
                <label>Drawing Grades - Low Carbon (w.o. B10)</label>
            </value>
            <value>
                <fullName>ZZ - Tyre Cord</fullName>
                <label>Drawing Grades - Tyre Cord</label>
            </value>
            <value>
                <fullName>ZZ - Welding Wire (SZW)</fullName>
                <label>Drawing Grades - Welding Wire</label>
            </value>
            <value>
                <fullName>ZW</fullName>
                <label>Bearing Steel</label>
            </value>
            <value>
                <fullName>ZK</fullName>
                <label>Cold Heading</label>
            </value>
            <value>
                <fullName>ZM</fullName>
                <label>Forging Steel</label>
            </value>
            <value>
                <fullName>ZS</fullName>
                <label>Free Cutting Steel (SZO)</label>
            </value>
            <value>
                <fullName>ZF</fullName>
                <label>Spring Steel</label>
            </value>
            <value>
                <fullName>00</fullName>
                <label>Across business Area</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastLevel__c.field-meta.xml
<CustomField>
    <fullName>ForecastLevel__c</fullName>
    <label>Forecast Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Area/Product Group</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastNetProceeds__c.field-meta.xml
<CustomField>
    <fullName>ForecastNetProceeds__c</fullName>
    <label>Forecast Net proceeds</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastSoldAmount__c.field-meta.xml
<CustomField>
    <fullName>ForecastSoldAmount__c</fullName>
    <label>Forecast sold amount</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/ForecastTimePoint__c.field-meta.xml
<CustomField>
    <fullName>ForecastTimePoint__c</fullName>
    <label>Forecast Time point</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BusinessArea.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZK</fullName>
        <label>Cold Heading</label>
    </customValue>
    <customValue>
        <fullName>ZF</fullName>
        <label>Spring Steel</label>
    </customValue>
    <customValue>
        <fullName>ZS</fullName>
        <label>Free Cutting Steel (SZO)</label>
    </customValue>
    <customValue>
        <fullName>ZZ</fullName>
        <label>Drawing Grades</label>
    </customValue>
    <customValue>
        <fullName>ZW</fullName>
        <label>Bearing Steel</label>
    </customValue>
    <customValue>
        <fullName>ZM</fullName>
        <label>Forging Steel</label>
    </customValue>
    <customValue>
        <fullName>00</fullName>
        <label>Across Business Areas</label>
    </customValue>
    <masterLabel>Business Area</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/BusinessSubgroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Welding Wire (SZW)</fullName>
        <label>Welding Wire</label>
    </customValue>
    <customValue>
        <fullName>Tyre Cord</fullName>
    </customValue>
    <customValue>
        <fullName>Low Carbon</fullName>
    </customValue>
    <customValue>
        <fullName>High Carbon</fullName>
    </customValue>
    <masterLabel>Product Group Business Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesplanningbatchTest.cls
/****************************************************************************
* Name: SalesplanningbatchTest
* Author: Gunjan Saxena
* Created Date: 08/11/2022
* Description: Test class of Salesplanningbatch
*****************************************************************************/
/*****************************************************************************
* Modification log
* Name		        Date	           		Description
* Developer Name	Date of Modification	Modification Description   
****************************************************************************/
@isTest
public class SalesplanningbatchTest {
    @testSetup
    static void setUpData(){
        List<Account> Acclst = TestDataFactory.createAccounts(2);
        Acclst[0].BusiessAreaForPlanning__c = 'ZK';
        Acclst[1].BusiessAreaForPlanning__c = '';
        
        Database.DMLOptions dml = new Database.DMLOptions();
			dml.DuplicateRuleHeader.allowSave = true;
			dml.DuplicateRuleHeader.runAsCurrentUser = true; 
        	Database.update(Acclst, dml);
        
       // update Acclst;
        list<InvoicedOrders__c> IOs = TestDataFactory.createIOs(6);
        for(InvoicedOrders__c IO : IOs){
            IO.InvoiceDate__c = system.today().addmonths(-1).toStartOfMonth();
        }
        IOs[0].BusinessArea__c = 'ZZ';
        IOs[1].BusinessArea__c = 'ZZ';
        IOs[0].ProductGroupBusinessArea__c = 'Low Carbon';
        IOs[2].BusinessArea__c = 'ZF';
        IOs[3].BusinessArea__c = 'ZW';        
        update IOs;
        
        List<SalesPlanning__c> SPLST = TestDataFactory.createSalesPlanning(7);
        for( SalesPlanning__c sp : SPLST){
            sp.ForecastTimePoint__c = system.today().addmonths(-2);
            sp.Frequency__c = 'Monthly';
            sp.ActualSoldAmount__c = 1500;
        }
        SPLST[0].ForecastLevel__c = 'Account';
        SPLST[0].Account__c = Acclst[0].ID;
        SPLST[0].ForecastTimePoint__c = system.today().addMonths(-2).toStartOfMonth();
        SPLST[0].ActualSoldAmount__c = 20;
        SPLST[0].ForecastSoldAmount__c = 30;
        SPLST[0].ActualNetProceeds__c = 50;
        SPLST[0].ForecastNetProceeds__c = 100;
        SPLST[0].Frequency__c = 'Monthly';
        
        SPLST[1].ForecastLevel__c = 'Account';
        SPLST[1].Account__c = Acclst[0].ID;
        SPLST[1].ForecastTimePoint__c = system.today().addMonths(-2).toStartOfMonth();
        SPLST[1].ActualSoldAmount__c = 20;
        SPLST[1].ForecastSoldAmount__c = 30;
        SPLST[1].ActualNetProceeds__c = 50;
        SPLST[1].ForecastNetProceeds__c = 100;
        SPLST[1].Frequency__c = 'Monthly';
        update SPLST;
        
        List<SalesPlanning__c> SPLST1 = TestDataFactory.createSalesPlanning(7);
        
        SPLST1[0].ForecastTimePoint__c = system.today().addmonths(-1);
        SPLST1[0].Account__c =  Acclst[0].ID;
        SPLST1[0].BusinessArea__c = 'ZZ - Low Carbon - B10';
        SPLST1[0].ForecastLevel__c = 'Business Area/Product Group';
        SPLST1[0].Frequency__c = 'Monthly';
            
        SPLST1[1].ForecastTimePoint__c = system.today().addmonths(-1);
        SPLST1[1].Account__c =  Acclst[0].ID;
        SPLST1[1].BusinessArea__c = 'ZZ - Low Carbon - B10';
        SPLST1[1].ForecastLevel__c = 'Account';
        SPLST1[1].Frequency__c = 'Monthly';
        
        SPLST1[2].ForecastTimePoint__c = system.today().addmonths(-1);
        SPLST1[2].Account__c =  Acclst[1].ID;
        SPLST1[2].BusinessArea__c = 'ZZ - Low Carbon - B10';
        SPLST1[2].ForecastLevel__c = 'Business Area/Product Group';
        SPLST1[2].Frequency__c = 'Monthly';
        
        SPLST1[3].ForecastTimePoint__c = system.today().addmonths(-1);
        SPLST1[3].Account__c =  Acclst[1].ID;
        SPLST1[3].BusinessArea__c = 'ZZ - Low Carbon - B10';
        SPLST1[3].ForecastLevel__c = 'Account';
        SPLST1[3].Frequency__c = 'Monthly';
        
        SPLST1[5].ForecastLevel__c = 'Account';
        SPLST1[5].ForecastTimePoint__c = system.today().addMonths(11).toStartOfMonth();
        SPLST1[5].Account__c =  Acclst[1].ID;
        SPLST1[5].BusinessArea__c = 'ZZ - Low Carbon - B10';
        SPLST1[5].Frequency__c = 'Monthly';
        
        SPLST1[6].ForecastLevel__c = 'Account';
        SPLST1[6].ForecastTimePoint__c = system.today().addMonths(11).toStartOfMonth();
        SPLST1[6].Account__c =  NULL;
        SPLST1[6].BusinessArea__c = 'ZZ - Low Carbon - B10';
        SPLST1[6].Frequency__c = 'Monthly';
        
        update SPLST1;
                
    }
    @isTest static void testOLIRecord(){
        test.starttest();
        List<SalesPlanning__c> SPLSTbefore = [Select ID from SalesPlanning__c Where ForecastLevel__c = 'Account' AND Account__c = ''];
        Salesplanningbatch b = new Salesplanningbatch(); 
        Database.executeBatch(b); 
        List<SalesPlanning__c> SPLSTafter = [Select ID from SalesPlanning__c Where ForecastLevel__c = 'Account' AND Account__c = ''];
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = SalesPlanning__c.BusinessArea__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getValue());                                
        }
        system.assertEquals(pickListValuesList.size(), (SPLSTafter.size() - SPLSTbefore.size()), 'Incorrect output');
        test.stoptest();
    }
    @isTest static void testOLIELSERecord(){
        test.starttest();
        InvoicedOrders__c IOs = [SELECT ID, Account__c  FROM InvoicedOrders__c LIMIT 1];
        Account Acc = [SELECT ID, BusiessAreaForPlanning__c  FROM Account Where ID = :IOs.Account__c LIMIT 1];
        Acc.BusiessAreaForPlanning__c = '';
        Database.DMLOptions dml = new Database.DMLOptions();
			dml.DuplicateRuleHeader.allowSave = true;
			dml.DuplicateRuleHeader.runAsCurrentUser = true; 
        	Database.update(Acc, dml);
        //Update Acc;
        List<SalesPlanning__c> SPLSTbefore = [Select ID from SalesPlanning__c Where ForecastLevel__c = 'Account' AND Account__c = ''];
        Salesplanningbatch b = new Salesplanningbatch(); 
        Database.executeBatch(b); 
        List<SalesPlanning__c> SPLSTafter = [Select ID from SalesPlanning__c Where ForecastLevel__c = 'Account' AND Account__c = ''];
        
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = SalesPlanning__c.BusinessArea__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getValue());                                
        }
        system.assertEquals(pickListValuesList.size(), (SPLSTafter.size() - SPLSTbefore.size()), 'Incorrect output');
   		test.stoptest();
    }
    
}