force-app/main/default/objects/Account/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ProductManager__c.field-meta.xml
<CustomField>
    <fullName>ProductManager__c</fullName>
    <label>Product Manager</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>SalesRepresentative__c</fullName>
    <label>Sales Representative</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAPAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>SAPAccountNumber__c</fullName>
    <label>SAP Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/QualityDepartment__c.field-meta.xml
<CustomField>
    <fullName>QualityDepartment__c</fullName>
    <label>Quality Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neunkirchen</fullName>
            </value>
            <value>
                <fullName>Burbach</fullName>
            </value>
            <value>
                <fullName>Nauweiler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinalCheckStartDate__c.field-meta.xml
<CustomField>
    <fullName>FinalCheckStartDate__c</fullName>
    <label>Final Check Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductManager__c.field-meta.xml
<CustomField>
    <fullName>ProductManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QualityCheckStartDate__c.field-meta.xml
<CustomField>
    <fullName>QualityCheckStartDate__c</fullName>
    <label>Quality Check Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QualityCheckTotalDuration__c.field-meta.xml
<CustomField>
    <fullName>QualityCheckTotalDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quality Check Total Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QualityDepartment__c.field-meta.xml
<CustomField>
    <fullName>QualityDepartment__c</fullName>
    <formula>IF(OR(ISPICKVAL(BusinessArea__c, &apos;ZK&apos;),ISPICKVAL(BusinessArea__c, &apos;ZF&apos;),ISPICKVAL(BusinessArea__c, &apos;ZS&apos;)) , &apos;620 - Neunkirchen&apos;, 
IF(ISPICKVAL(BusinessArea__c, &apos;ZZ&apos;),&apos;473 - Burbach&apos;,
IF(OR(ISPICKVAL(BusinessArea__c, &apos;ZW&apos;),ISPICKVAL(BusinessArea__c, &apos;ZM&apos;)) , &apos;460 - Nauweiler&apos;, 
NULL)))</formula>
    <label>Quality Department</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QualityManager__c.field-meta.xml
<CustomField>
    <fullName>QualityManager__c</fullName> 
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Manager</label> 
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QualityRep__c.field-meta.xml
<CustomField>
    <fullName>QualityRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>SalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelper.cls
/****************************************************************************
* Name: OpportunityTriggerHandler
* Author: Naina Butle
* Created Date: 02/12/2022
* Description: Helper class for Opportunity Trigger
*****************************************************************************
* Modification log
* Name      Date                    Description
* Developer Name    Date of Modification    Modification Description  
* Naina Butle       08-02-2023              US-2241
* Naina Butle       20/02/2022              US-2218 Opportunity Creator to be inserted as Sales Rep when Sales Profile
****************************************************************************/
public with sharing class OpportunityTriggerHelper {
    /****************************************************************************
* Author Name: Naina B
* Description: Method to update the  quality team.
* Created Date: 19/10/2022
* Last Modified Date: 
****************************************************************************/
public static void updateSalesRProductMQualityR(list<Opportunity> oppList, Map<Id, Opportunity> oldOppMap){
    Set<Id> accountIdSet = new Set<Id>();
    Map<Id, List<AccountTeamMember>> accountIdVsAccountTeamMemberMap = new Map<Id, List<AccountTeamMember>>();
    Map<Id, String> accChannel = new Map<Id, String>();
    Map<Id, String> accSAPAccount = new Map<Id, String>();
     Savepoint sp;
    try{
       sp = Database.setSavepoint();
        User user = [SELECT ID, Profile.Name From User WHERE ID = :UserInfo.getUserId() LIMIT 1];//US-2218
        for(Opportunity opp : oppList){
            if(opp.AccountId != null){
                accountIdSet.add(opp.AccountId);
            }
            if(oldOppMap != null){ //5407
                if(opp.ChannelOfDistribution__c != null && oldOppMap.containsKey(opp.Id) && opp.ChannelOfDistribution__c != oldOppMap.get(opp.Id).ChannelOfDistribution__c){
                    opp.SalesRepresentative__c = null;
                    opp.ProductManager__c = null;
                    opp.QualityRep__c = null;
                }
                if(opp.ChannelOfDistribution__c != null && oldOppMap.containsKey(opp.Id) && opp.ChannelOfDistribution__c != oldOppMap.get(opp.Id).ChannelOfDistribution__c){
                    opp.SalesRepresentative__c = null;
                    opp.ProductManager__c = null;
                    opp.QualityRep__c = null;
                }
            }
        }
        for(Account acc: [SELECT Id,ChannelOfDistribution__c, SAPAccountNumber__c FROM Account WHERE ID IN:accountIdSet]){
            accChannel.put(acc.Id, acc.ChannelOfDistribution__c);
            if(acc.SAPAccountNumber__c != null){
                accSAPAccount.put(acc.Id, acc.SAPAccountNumber__c);
            }
        }
        for(AccountTeamMember accTeam : [SELECT Id, AccountId, ChannelOfDistribution__c, QualityDepartment__c, TeamMemberRole, UserId, User.Name,
                                         Account.ChannelOfDistribution__c
                                         FROM AccountTeamMember
                                         WHERE AccountId IN :accountIdSet]){
                                             if (String.isNotBlank(accTeam.AccountId) && String.isNotBlank(accTeam.Account.ChannelOfDistribution__c)){
                                                 if(!accountIdVsAccountTeamMemberMap.containsKey(accTeam.AccountId)){
                                                     accountIdVsAccountTeamMemberMap.put(accTeam.AccountId, new List<AccountTeamMember>());
                                                 }
                                                 accountIdVsAccountTeamMemberMap.get(accTeam.AccountId).add(accTeam);
                                             }
                                         }
        
        for(Opportunity oppData :oppList){
            if(accSAPAccount.containsKey(oppData.AccountId)){
                if(( (oppData.ChannelOfDistribution__c == null || String.isBlank(oppData.ChannelOfDistribution__c)) && (!accChannel.containsKey(oppData.AccountId) || accChannel.get(oppData.AccountId) == null)) ||
                   ((String.isNotBlank(oppData.ChannelOfDistribution__c) ) && 
                    (accChannel.containsKey(oppData.AccountId) && !String.isBlank(accChannel.get(oppData.AccountId)) && accChannel.get(oppData.AccountId) != null && accChannel.get(oppData.AccountId).contains(oppData.ChannelOfDistribution__c)) //US-2241
                   )){ 
                       if(accountIdVsAccountTeamMemberMap.containsKey(oppData.AccountId))
                       {   
                           for(AccountTeamMember accData : accountIdVsAccountTeamMemberMap.get(oppData.AccountId)){
                               if(oppData.ChannelOfDistribution__c == accData.ChannelOfDistribution__c){
                                   if(accData.TeamMemberRole == ConstantClass.SALESREPRESENTIVE){
                                       oppData.SalesRepresentative__c = accData.UserId;
                                   }else if(accData.TeamMemberRole == ConstantClass.ACCOUNTMANAGER){
                                       oppData.ProductManager__c = accData.UserId;
                                   }else if(accData.TeamMemberRole == ConstantClass.QUALITYREP){
                                       oppData.QualityRep__c = accData.UserId;
                                   }else if(accData.TeamMemberRole == ConstantClass.QWACCOUNTMANAGER){ //7428
                                    oppData.QualityManager__c = accData.UserId;
                                   }
                               }
                           }
                           //US-2218 - Start
                           if(user.Profile.Name == ConstantClass.SAG_SALES_PROFILE && (oppData.SalesRepresentative__c == null || String.isBlank(oppData.SalesRepresentative__c))){
                               oppData.SalesRepresentative__c = user.Id;
                           }
                           //US-2218 - end
                           
                       }else{
                           //oppData.ChannelOfDistribution__c.addError(oppData.ChannelOfDistribution__c + ' ' + System.Label.ChannelOfDistributionError);
                       }
                       //US-2218 - Start
                       if(user.Profile.Name == ConstantClass.SAG_SALES_PROFILE && (oppData.SalesRepresentative__c == null || String.isBlank(oppData.SalesRepresentative__c))){
                           oppData.SalesRepresentative__c = user.Id;
                       }
                       //US-2218 - end
                   }else{
                       oppData.ChannelOfDistribution__c.addError(oppData.ChannelOfDistribution__c + ' ' + System.Label.ChannelOfDistributionError);
                   }
            }
        }
    }catch(Exception e){
        Database.RollBack(sp);
        String exdetails = e.getCause() + ' ; '+ e.getLineNumber() + ' ; '+ e.getMessage() + ' ; '+ e.getStackTraceString()
            + ' ; ' + e.getTypeName() ;
        ExceptionUtilClass.publishException(ConstantClass.OPPORTUNITY_OBJECT, ConstantClass.CHANNELDISCLASS_ERROR, oppList[0].Id, exdetails, ConstantClass.APEX_CLASS);
    }
}
    
    /****************************************************************************
* Author Name: Naina B
* Description: Method to update the FinalCheckStartDate and QualityCheckStartDate when Opportunity Stage is changed to "Final Check/Quality Check".
* Created Date: 31/01/2023
* Last Modified Date: 1/02/2023
****************************************************************************/
    public static void updateFinalCheckStartDate(list<Opportunity> oppList,Map<Id, Opportunity> oppOldMap){
        for(Opportunity opp : oppList){
            if(oppOldMap.get(opp.Id).StageName != ConstantClass.QUALITYCHECK_STAGENAME && opp.StageName == ConstantClass.QUALITYCHECK_STAGENAME){
                opp.QualityCheckStartDate__c = System.today();
            }
            else if(opp.StageName == ConstantClass.FINALCHECK_STAGENAME && opp.FinalCheckStartDate__c== null){
                opp.FinalCheckStartDate__c = System.today();
            }
        }
    }
    
    /****************************************************************************
* Author Name: Impana Paalyam
* Description: Method to update the QualityCheckTotalDuration when  Opportunity Stage is changed from Quality Check to some other stage.
* Created Date: 01/02/2023
* Last Modified Date: 
****************************************************************************/
    public static void updateQualityCheckTotalDuration (list<Opportunity> oppList,Map<Id, Opportunity> oppOldMap,Map<Id, Opportunity> oppNewMap){
        for(Opportunity opp : oppList){
            if(oppOldMap.get(opp.Id).StageName == ConstantClass.QUALITYCHECK_STAGENAME && oppNewMap.get(opp.Id).StageName != ConstantClass.QUALITYCHECK_STAGENAME && opp.QualityCheckStartDate__c!= null){
                Integer diff = opp.QualityCheckStartDate__c.date().daysBetween(Date.today());
                if(opp.QualityCheckTotalDuration__c!= null){
                    opp.QualityCheckTotalDuration__c = opp.QualityCheckTotalDuration__c + diff;
                } else {
                    opp.QualityCheckTotalDuration__c = diff;
                }
            }
        }
        
    } 
}