force-app/main/default/objects/Account/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerSize__c.field-meta.xml
<CustomField>
    <fullName>CustomerSize__c</fullName>
    <label>Customer Size</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ProductManager__c.field-meta.xml
<CustomField>
    <fullName>ProductManager__c</fullName>
    <label>Product Manager</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/QualityRepresentative__c.field-meta.xml
<CustomField>
    <fullName>QualityRepresentative__c</fullName>
    <label>Quality Representative</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>SalesRepresentative__c</fullName>
    <label>Sales Representative</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Praekula__c/Praekula__c.object-meta.xml
<CustomObject>
    <label>Präkula</label>
    <nameField>
        <displayFormat>TA-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber>
        <label>PräkulaID</label> 
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Präkula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Praekula__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account </label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Präkula</relationshipLabel>
    <relationshipName>Pr_kula</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language </label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/ProductManager__c.field-meta.xml
<CustomField>
    <fullName>ProductManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager </label> 
    <referenceTo>User</referenceTo>
    <relationshipName>Pr_kula</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/QualityManager__c.field-meta.xml
<CustomField>
    <fullName>QualityManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Manager </label> 
    <referenceTo>User</referenceTo>
    <relationshipName>Pr_kula2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/QualityRepresentative__c.field-meta.xml
<CustomField>
    <fullName>QualityRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Representative </label> 
    <referenceTo>User</referenceTo>
    <relationshipName>Pr_kula3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>SalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative </label> 
    <referenceTo>User</referenceTo>
    <relationshipName>Pr_kula1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/TechnicalRemarkQualityDepartment__c.field-meta.xml
<CustomField>
    <fullName>TechnicalRemarkQualityDepartment__c</fullName>
    <label>Technical Remark Quality Department </label> 
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/TechnicalRemarkSales__c.field-meta.xml
<CustomField>
    <fullName>TechnicalRemarkSales__c</fullName>
    <label>Technical Remark Sales </label> 
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/TextForSelectionQuality__c.field-meta.xml
<CustomField>
    <fullName>TextForSelectionQuality__c</fullName>
    <label>Texts for Selection Quality Dep. </label> 
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not in product portfolio</fullName>
            </value>
            <value>
                <fullName>Acceptance of Spec.</fullName>
            </value>
            <value>
                <fullName>Surface according to DIN EN ISO 9443</fullName>
            </value>
            <value>
                <fullName>Surface according to EN ISO 9443</fullName>
            </value>
            <value>
                <fullName>Upset testing</fullName>
            </value>
            <value>
                <fullName>Edge decarburization according to DIN EN ISO 3887-03</fullName>
            </value>
            <value>
                <fullName>Edge decarburization according to DIN EN 10263</fullName>
            </value>
            <value>
                <fullName>Purpose of use</fullName>
            </value>
            <value>
                <fullName>Maraform</fullName>
            </value>
            <value>
                <fullName>Standard sentence: &quot;Further customer requirements&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/TextForSelectionSales__c.field-meta.xml
<CustomField>
    <fullName>TextForSelectionSales__c</fullName>
    <label>Texts for Selection Sales</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minimum order quantity (t)</fullName>
            </value>
            <value>
                <fullName>Batch size</fullName>
            </value>
            <value>
                <fullName>New admission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PrakulaTriggerHandlerTest.cls
/****************************************************************************
* Name: PrakulaTriggerHandlerTest
* Author: Harshitha Udaykumar
* Created Date: 13/09/2023
* Description: Test class of PrakulaTriggerHandler
*****************************************************************************
* Modification log
* Name		Date	           		Description
* Developer Name	Date of Modification	Modification Description  
****************************************************************************/
@isTest
public class PrakulaTriggerHandlerTest {
    @testSetup
    static void setUpdata(){
        List<User> userList = TestDataFactory.createUser(4);
        system.runAs(userList[0]) {
            List<Account> acc = TestDataFactory.createAccounts(1);
            List<Praekula__c> prakulalst = TestDataFactory.createPrakula(1);
            prakulalst[0].Account__c = acc[0].id;
            Update prakulalst;
        }
    }
    @isTest static void testInsertPrakula(){
        Test.startTest();
        List<Account> acclst = [SELECT Id FROM Account WHERE CustomerSize__c = 3.00];
        List<User> userList = [SELECT Id FROM User WHERE CompanyName = 'TEST'];
        List<AccountTeamMember> members = new list<AccountTeamMember>();
        members.add(new AccountTeamMember(AccountId = acclst[0].id, ChannelOfDistribution__c = '11', TeamMemberRole = ConstantClass.SALESREPRESENTIVE, UserId = userList[0].Id));
        members.add(new AccountTeamMember(AccountId = acclst[0].id, ChannelOfDistribution__c = '11', TeamMemberRole = ConstantClass.ACCOUNTMANAGER, UserId = userList[1].Id));
        members.add(new AccountTeamMember(AccountId = acclst[0].id, ChannelOfDistribution__c = '11', TeamMemberRole = ConstantClass.QUALITYREP, UserId = userList[2].Id));
        members.add(New AccountTeamMember(AccountId = acclst[0].id, ChannelOfDistribution__c = '11', TeamMemberRole = ConstantClass.QWACCOUNTMANAGER, UserId = userList[3].Id));
        insert members;
        List<Praekula__c> praekulalst = [SELECT Id,Language__c, Account__c,QualityManager__c, QualityRepresentative__c, SalesRepresentative__c, ProductManager__c  FROM Praekula__c WHERE Language__c ='EN'];
        praekulalst[0].Language__c = 'DE';
        Update praekulalst;
        Test.stopTest();
        system.assertEquals( praekulalst[0].Language__c, 'DE', 'Language__c should be English');
        
    }
    
    //US-7210   
    @isTest static Void testUpdatePrakula(){
        Test.startTest();
        List<Praekula__c> praekulalst = [SELECT Id, Language__c,TextForSelectionSales__c,TextForSelectionQuality__c FROM Praekula__c WHERE Language__c ='EN'];
        praekulalst[0].TextForSelectionSales__c = 'Minimum order quantity (t)';
        praekulalst[0].TextForSelectionQuality__c = 'Not in product portfolio';
        Update praekulalst;
        Test.stopTest();
        system.assertEquals( praekulalst[0].TextForSelectionSales__c, 'Minimum order quantity (t)', 'TextForSelectionSales__c should be Minimum order quantity (t)');
    }
    
    @isTest static Void testUpdatePrakula2(){
        Test.startTest();
        List<Praekula__c> praekulalst = [SELECT Id, Language__c,TextForSelectionSales__c,TextForSelectionQuality__c,TechnicalRemarkSales__c FROM Praekula__c WHERE Language__c ='EN'];
        praekulalst[0].Language__c = 'DE';
        praekulalst[0].TextForSelectionSales__c = 'Minimum order quantity (t)';
        praekulalst[0].TechnicalRemarkSales__c = 'The minimum order quantity per item is 150 metricton.';
        praekulalst[0].TextForSelectionQuality__c = 'Not in product portfolio';
        praekulalst[0].TechnicalRemarkQualityDepartment__c ='We offer in accordance with the statement from Saarstahl to your specification.';
        Update praekulalst;
        praekulalst[0].TextForSelectionSales__c = null;
        praekulalst[0].TextForSelectionQuality__c = null;
        update praekulalst;
        Test.stopTest();
        system.assertEquals( praekulalst[0].TextForSelectionSales__c, null, 'TextForSelectionSales__c should be null');
    }
    
    @isTest static Void testUpdatePrakula3(){
        Test.startTest();
        List<Praekula__c> praekulalst = [SELECT Id, Language__c,TextForSelectionSales__c,TextForSelectionQuality__c,TechnicalRemarkSales__c FROM Praekula__c WHERE Language__c ='EN'];
        praekulalst[0].Language__c = 'DE';
        praekulalst[0].TextForSelectionSales__c = 'Minimum order quantity (t)';
        praekulalst[0].TextForSelectionQuality__c = 'Not in product portfolio';
        Update praekulalst;
        praekulalst[0].TextForSelectionSales__c = 'Batch size';
        praekulalst[0].TextForSelectionQuality__c = 'Acceptance of Spec.';
        update praekulalst;
        Test.stopTest();
        system.assertEquals( praekulalst[0].TextForSelectionSales__c, 'Batch size', 'TextForSelectionSales__c should be Batch size');
    }
}