force-app/main/default/objects/Account/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  Inactive__c = false , IMAGE(&quot;/resource/Green&quot;, &quot;Green&quot;, 35, 40),
IF ( Inactive__c = true, IMAGE(&quot;/resource/Red&quot;, &quot;Red&quot;,35 ,40),&quot;Error&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentTemplate/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>   
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CalculationTimePoint__c.field-meta.xml
<CustomField>
    <fullName>CalculationTimePoint__c</fullName>
    <defaultValue>&quot;Monthly&quot;</defaultValue>
    <label>Time reference calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DateOf_Payment__c.field-meta.xml
<CustomField>
    <fullName>DateOf_Payment__c</fullName>
    <label>Date of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DateOfReceipt__c.field-meta.xml
<CustomField>
    <fullName>DateOfReceipt__c</fullName>
    <label>Date of Receipt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Incoterm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>Type of inquiry</description>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OpportunityType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QuoteOfferedDate__c.field-meta.xml
<CustomField>
    <fullName>QuoteOfferedDate__c</fullName>
    <inlineHelpText>The date on which the first active Quote is set to Offered.</inlineHelpText>
    <label>Quote Offered Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QuoteValidTill__c.field-meta.xml
<CustomField>
    <fullName>QuoteValidTill__c</fullName>
    <label>Quote valid till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UsePricingTool__c.field-meta.xml
<CustomField>
    <fullName>UsePricingTool__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Use Pricing Tool</label> 
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunitywithquotecreations.recordType-meta.xml
<RecordType>
    <fullName>Opportunitywithquotecreations</fullName>
    <active>true</active>
    <businessProcess>Full Opportunity Process</businessProcess>
    <label>Opportunity with quote creations</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <label>Certificate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Certificate</fullName>
            </value>
            <value>
                <fullName>2.2 Factory Certificate</fullName>
            </value>
            <value>
                <fullName>3.1 Acceptance Test Certificate</fullName>
            </value>
            <value>
                <fullName>3.2 Acceptance Test Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CustomerSteelGrade__c.field-meta.xml
<CustomField>
    <fullName>CustomerSteelGrade__c</fullName>
    <label>Customer Steel Grade</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DimensionAFrom__c.field-meta.xml
<CustomField>
    <fullName>DimensionAFrom__c</fullName>
    <label>Dimension A from in mm</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DimensioncalculationA__c.field-meta.xml
<CustomField>
    <fullName>DimensioncalculationA__c</fullName>
    <label>Dimension for calculation A</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FinalPrice__c.field-meta.xml
<CustomField>
    <fullName>FinalPrice__c</fullName>
    <label>Offered Price (Net revenue)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FreightCosts__c.field-meta.xml
<CustomField>
    <fullName>FreightCosts__c</fullName>
    <label>Freight Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/HeatTreatmentSales__c.field-meta.xml
<CustomField>
    <fullName>HeatTreatmentSales__c</fullName>
    <label>Heat Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HeatTreatment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PurposeOfUse__c.field-meta.xml
<CustomField>
    <fullName>PurposeOfUse__c</fullName>
    <label>Purpose Of Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-UNKNOWN</fullName>
            </value>
            <value>
                <fullName>2-TRADE</fullName>
            </value>
            <value>
                <fullName>3-GRINDING MATERIAL</fullName>
            </value>
            <value>
                <fullName>4-HEADSTOCK MATERIAL</fullName>
            </value>
            <value>
                <fullName>5-CHUCKING STEEL</fullName>
            </value>
            <value>
                <fullName>6-FLUTED CYLINDER</fullName>
            </value>
            <value>
                <fullName>7-SHOOTING STEEL</fullName>
            </value>
            <value>
                <fullName>8-RIFLE RIFLE</fullName>
            </value>
            <value>
                <fullName>9-TURNING</fullName>
            </value>
            <value>
                <fullName>10-DRAWING MATERIAL</fullName>
            </value>
            <value>
                <fullName>11-DRAWING MATERIAL PRESSURE TIGHT</fullName>
            </value>
            <value>
                <fullName>12-DRAWING MATERIAL FOR DRILLING</fullName>
            </value>
            <value>
                <fullName>13-DRAWING MATERIAL ROUND ON 6-KT.</fullName>
            </value>
            <value>
                <fullName>14-DRAWING MATERIAL ROUND ON 6-KT. PRESSURED.</fullName>
            </value>
            <value>
                <fullName>15-DRAWING MATERIAL FOR PISTON RODS</fullName>
            </value>
            <value>
                <fullName>16-DRAWING MATERIAL FOR WELDING STUDS</fullName>
            </value>
            <value>
                <fullName>17-DRAWING MATERIAL FOR UPSETTING</fullName>
            </value>
            <value>
                <fullName>18-DRAWING STOCK FOR COLD ROLLING</fullName>
            </value>
            <value>
                <fullName>19-PLATING QUALITY</fullName>
            </value>
            <value>
                <fullName>1A-SOFT DRAWING MATERIAL</fullName>
            </value>
            <value>
                <fullName>1B-HARD DRAWING WIRE</fullName>
            </value>
            <value>
                <fullName>1C-PIANO WIRE PIANO WIRE</fullName>
            </value>
            <value>
                <fullName>1D-GRIDS</fullName>
            </value>
            <value>
                <fullName>1E-STEEL FLEX BOWDEN WIRE</fullName>
            </value>
            <value>
                <fullName>1F-STAPLES STAPLES</fullName>
            </value>
            <value>
                <fullName>1G-TEXTILE NEEDLES</fullName>
            </value>
            <value>
                <fullName>1H-HOSEWIRE TUBING WIRE</fullName>
            </value>
            <value>
                <fullName>1K-HEAD SUPPORT WIRE</fullName>
            </value>
            <value>
                <fullName>1L-CABLE WIRE</fullName>
            </value>
            <value>
                <fullName>1M-OFFSHORE/CABLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/QuantityUnit__c.field-meta.xml
<CustomField>
    <fullName>QuantityUnit__c</fullName>
    <label>Quantity Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Moto</fullName>
            </value>
            <value>
                <fullName>Jato</fullName>
            </value>
            <value>
                <fullName>Stück</fullName>
            </value>
            <value>
                <fullName>LBS</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ShortPiece__c.field-meta.xml
<CustomField>
    <fullName>ShortPiece__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Short Piece</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>No Offer</fullName>
            </value>
            <value>
                <fullName>Offer Later</fullName>
            </value>
            <value>
                <fullName>-None-</fullName>
                <isActive>false</isActive>
                <label>-None-</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <isActive>false</isActive>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Won</fullName>
                <isActive>false</isActive>
                <label>Won</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Surcharge1__c.field-meta.xml
<CustomField>
    <fullName>Surcharge1__c</fullName>
    <label>Surcharge 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SurfaceCondition__c.field-meta.xml
<CustomField>
    <fullName>SurfaceCondition__c</fullName>
    <label>Surface Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SurfaceCondition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/UnitOfMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasurement__c</fullName>
    <label>Unit Of Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MM</fullName>
                <default>true</default>
                <label>MM</label>
            </value>
            <value>
                <fullName>Inch</fullName>
            </value>
            <value>
                <fullName>Feet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/OrgWideSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ability to set the org on and off an alternative basic plan</description>
    <label>Org Wide Settings</label>
</CustomObject>

force-app/main/default/objects/OrgWideSettings__c/fields/ActivateAlternateBasicPlan__c.field-meta.xml
<CustomField>
    <fullName>ActivateAlternateBasicPlan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate Alternate Basic Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/fields/Rawmateriallastupdatedon__c.field-meta.xml
<CustomField>
    <fullName>Rawmateriallastupdatedon__c</fullName>
    <label>Raw material last updated on</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HeatTreatment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>+T-Tempered</fullName>
    </customValue>
    <customValue>
        <fullName>+FP-Treated for ferrite-pearlite structure and hardness span</fullName>
    </customValue>
    <customValue>
        <fullName>+TH-Treated for hardness span</fullName>
    </customValue>
    <customValue>
        <fullName>+S-Treated for cold shear</fullName>
    </customValue>
    <customValue>
        <fullName>+AC-Annealed to obtain spherical carbides</fullName>
    </customValue>
    <customValue>
        <fullName>+N-Normalized annealed or normalizing shaped</fullName>
    </customValue>
    <customValue>
        <fullName>+U-Untreated</fullName>
    </customValue>
    <customValue>
        <fullName>+QT-Quench Hardened-Tempered</fullName>
    </customValue>
    <customValue>
        <fullName>+A-Soft annealed</fullName>
    </customValue>
    <customValue>
        <fullName>+AR-As rolled (without any special rolling and/or heat treatment conditions)</fullName>
    </customValue>
    <masterLabel>Heat Treatment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Incoterm.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAD - CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CFR - Costs and freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIF - Cost, Insurance &amp; Freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIP - Freight free insured</fullName>
    </customValue>
    <customValue>
        <fullName>CPT - Freight free</fullName>
    </customValue>
    <customValue>
        <fullName>DAP - Delivered named place</fullName>
    </customValue>
    <customValue>
        <fullName>DPU - Delivered terminal</fullName>
    </customValue>
    <customValue>
        <fullName>DDP - Delivered duty paid</fullName>
    </customValue>
    <customValue>
        <fullName>EXW - Ex works</fullName>
    </customValue>
    <customValue>
        <fullName>FAS - Free longitudinal ship</fullName>
    </customValue>
    <customValue>
        <fullName>FCA - Free carrier</fullName>
    </customValue>
    <customValue>
        <fullName>FOB - Free on board</fullName>
    </customValue>
    <masterLabel>Incoterm</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OpportunityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Mass Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal - Existing Portfolio</label>
    </customValue>
    <masterLabel>Opportunity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PaymentTerms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AA</fullName>
    </customValue>
    <customValue>
        <fullName>AB</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AH</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AJ</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>DA</fullName>
    </customValue>
    <customValue>
        <fullName>DB</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DD</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DF</fullName>
    </customValue>
    <customValue>
        <fullName>DG</fullName>
    </customValue>
    <customValue>
        <fullName>DH</fullName>
    </customValue>
    <customValue>
        <fullName>DI</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SurfaceCondition.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>As Rolled</fullName>
    </customValue>
    <customValue>
        <fullName>Peeled</fullName>
    </customValue>
    <customValue>
        <fullName>Pickled</fullName>
    </customValue>
    <customValue>
        <fullName>Pickled + coated</fullName>
    </customValue>
    <customValue>
        <fullName>Coated</fullName>
    </customValue>
    <customValue>
        <fullName>Protection Against Rust</fullName>
    </customValue>
    <customValue>
        <fullName>Blasted</fullName>
    </customValue>
    <masterLabel>Surface Condition</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteLineItemTriggerHandlerTest.cls
@isTest
public class QuoteLineItemTriggerHandlerTest {
    @testSetup
    static void setUpData(){
        List<User> userList = TestDataFactory.createUser(3);
        System.runAs(userList[0]) {
            List<Account> act = TestDataFactory.createAccounts(1);
            act[0].ChannelOfDistribution__c = '11';
            update act;
            Account acc = [Select Id, Name, ChannelOfDistribution__c from Account limit 1];
            List<Opportunity> opplst = TestDataFactory.createOpps(1);
            opplst[0].AccountId = acc.id;
            opplst[0].ChannelOfDistribution__c = '11';
            update opplst;  
            TestDataFactory.createdocumentTemplate(1);
            List<DocumentTemplate> Quoteserversidedoclst = [SELECT Id, Name, Language__c, CreatedDate, CreatedBy.name FROM DocumentTemplate Limit 1];
            IF(!Quoteserversidedoclst.isempty()){
                Quoteserversidedoclst[0].Name = ConstantClass.QUOTE_DOC_NAME_EN;
                Quoteserversidedoclst[0].Language__c = 'EN';
                update Quoteserversidedoclst;
            }
            OrgWideSettings__c setting = new OrgWideSettings__c();
            setting.Name = 'Org Wide Info';
            setting.ActivateAlternateBasicPlan__c = false;
            setting.Rawmateriallastupdatedon__c = System.today();
            insert setting;
        }
    }
    @isTest
    static void testAfterInsert() {
        Test.startTest();
        Account acc = [SELECT Id, Name, ChannelOfDistribution__c FROM Account WHERE Name = 'TestAccount0' limit 1];
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'Opportunitywithquotecreations'];
        List<Product2> prdlst = testdatafactory.createProduct(1);
        Opportunity op = new Opportunity(Name = 'Test',
                                         StageName = 'New',
                                         CloseDate = System.today().addMonths(1),
                                         AccountId = acc.Id,
                                         RecordTypeId = rt.ID,
                                         QuoteOfferedDate__c= System.today(),
                                         ChannelOfDistribution__c = '11',
                                         OpportunityType__c = 'Standard Inquiry',
                                         BusinessArea__c ='ZK',
                                         DateOfReceipt__c = System.today(),
                                         CurrencyIsoCode ='EUR',
                                         CalculationTimePoint__c = 'Monthly',
                                         QuoteValidTill__c = System.today(),
                                         Incoterms__c = 'CAD - CAD',
                                         DateOf_Payment__c = 'AA',
                                         Type = 'Existing Business'
                                        );
        
        PricebookEntry customPrice = testdatafactory.customPriceBook();
        op.Pricebook2Id = customPrice.Pricebook2Id;
        insert op;
        
        OpportunityLineItem OLI = new OpportunityLineItem();
        OLI.OpportunityId = op.Id;
        OLI.Status__c = 'Active';
        OLI.Product2Id = prdlst[0].Id;  
        OLI.UnitOfMeasurement__c = 'MM';
        OLI.Quantity = 5;
        OLI.UnitPrice = 10;
        OLI.HeatTreatmentSales__c = '+T-Tempered';
        OLI.CustomerSteelGrade__c = 'sdfdrg';
        OLI.SurfaceCondition__c ='As Rolled';
        OLI.UnitOfMeasurement__c = 'Inch';
        OLI.PurposeOfUse__c ='2-TRADE';
        OLI.Certificate__c ='No Certificate';
        OLI.ShortPiece__c = true;
        OLI.DimensionAFrom__c = 2.2;
        OLI.FinalPrice__c =0;
        OLI.Surcharge1__c =1;
        OLI.FreightCosts__c =1;
        OLI.QuantityUnit__c ='Moto';
        OLI.DimensioncalculationA__c = 1;
        OLI.UsePricingTool__c = true;
        if(OLI != null){
            Insert OLI;
        }
        Quote qo = new Quote();
        qo.Name = 'TestQuote';
        qo.Pricebook2Id = customPrice.Pricebook2Id;
        qo.OpportunityId =op.id; 
        insert qo;
        qo.Status = ConstantClass.OFFERED_STATUS;
        update qo;
        
        QuoteLineItem qli = new QuoteLineItem();
        qli.QuoteId = qo.Id;
        qli.Quantity = 1;
        qli.UnitPrice = 100;
        qli.PricebookEntryId = customPrice.Id;
        qli.Product2Id = OLI.Product2Id;
        qli.OpportunityLineItemId = OLI.Id;
        insert qli;
        List<QuoteLineItem> insertedQLIs = [SELECT Id FROM QuoteLineItem WHERE QuoteId = :qo.Id LIMIT 1];
        system.assertEquals(1, insertedQLIs.size(), 'A new QuoteLineItem should be created for the given QuoteID'); //assert that trigger worked properly
        
        Test.stopTest();
    }
    
    @isTest
    static void testAfterInsert1() {
        Test.startTest();
        Account acc = [SELECT Id, Name, ChannelOfDistribution__c, Language__c FROM Account WHERE Name = 'TestAccount0' limit 1];
        acc.Language__c ='DE';
        update acc;
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'Opportunitywithquotecreations'];
        List<DocumentTemplate> Quoteserversidedoclst = [SELECT Id, Name, Language__c, CreatedDate, CreatedBy.name FROM DocumentTemplate Limit 1];
            IF(!Quoteserversidedoclst.isempty()){
                Quoteserversidedoclst[0].Name = ConstantClass.QUOTE_DOC_NAME_EN;
                Quoteserversidedoclst[0].Language__c = 'DE';
                update Quoteserversidedoclst;
            }
        List<Product2> prdlst = testdatafactory.createProduct(1);
        Opportunity op = new Opportunity(Name = 'Test',
                                         StageName = 'New',
                                         CloseDate = System.today().addMonths(1),
                                         AccountId = acc.Id,
                                         RecordTypeId = rt.ID,
                                         QuoteOfferedDate__c= System.today(),
                                         ChannelOfDistribution__c = '11',
                                         OpportunityType__c = 'Standard Inquiry',
                                         BusinessArea__c ='ZK',
                                         DateOfReceipt__c = System.today(),
                                         CurrencyIsoCode ='EUR',
                                         CalculationTimePoint__c = 'Monthly',
                                         QuoteValidTill__c = System.today(),
                                         Incoterms__c = 'CAD - CAD',
                                         DateOf_Payment__c = 'AA',
                                         Language__c = 'DE',
                                         Type = 'Existing Business'
                                        );
        
        PricebookEntry customPrice = testdatafactory.customPriceBook();
        op.Pricebook2Id = customPrice.Pricebook2Id;
        insert op;
        
        OpportunityLineItem OLI = new OpportunityLineItem();
        OLI.OpportunityId = op.Id;
        OLI.Status__c = 'Active';
        OLI.Product2Id = prdlst[0].Id;  
        OLI.UnitOfMeasurement__c = 'MM';
        OLI.Quantity = 5;
        OLI.UnitPrice = 10;
        OLI.HeatTreatmentSales__c = '+T-Tempered';
        OLI.CustomerSteelGrade__c = 'sdfdrg';
        OLI.SurfaceCondition__c ='As Rolled';
        OLI.UnitOfMeasurement__c = 'Inch';
        OLI.PurposeOfUse__c ='2-TRADE';
        OLI.Certificate__c ='No Certificate';
        OLI.ShortPiece__c = true;
        OLI.DimensionAFrom__c = 2.2;
        OLI.FinalPrice__c =0;
        OLI.Surcharge1__c =1;
        OLI.FreightCosts__c =1;
        OLI.QuantityUnit__c ='Moto';
        OLI.DimensioncalculationA__c = 1;
        OLI.UsePricingTool__c = true;
        if(OLI != null){
            Insert OLI;
        }
        Quote qo = new Quote();
        qo.Name = 'TestQuote';
        qo.Pricebook2Id = customPrice.Pricebook2Id;
        qo.OpportunityId =op.id; 
        insert qo;
        qo.Status = ConstantClass.OFFERED_STATUS;
        update qo;
        
        QuoteLineItem qli = new QuoteLineItem();
        qli.QuoteId = qo.Id;
        qli.Quantity = 1;
        qli.UnitPrice = 100;
        qli.PricebookEntryId = customPrice.Id;
        qli.Product2Id = OLI.Product2Id;
        qli.OpportunityLineItemId = OLI.Id;
        insert qli;
        List<QuoteLineItem> insertedQLIs = [SELECT Id FROM QuoteLineItem WHERE QuoteId = :qo.Id LIMIT 1];
        system.assertEquals(1, insertedQLIs.size(), 'A new QuoteLineItem should be created for the given QuoteID'); //assert that trigger worked properly
        
        Test.stopTest();
    }
}