force-app/main/default/objects/Account/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CalculationTimePoint__c.field-meta.xml
<CustomField>
    <fullName>CalculationTimePoint__c</fullName>
    <defaultValue>&quot;Monthly&quot;</defaultValue>
    <label>Time reference calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ChannelOfDistribution__c.field-meta.xml
<CustomField>
    <fullName>ChannelOfDistribution__c</fullName>
    <label>Channel Of Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DateOf_Payment__c.field-meta.xml
<CustomField>
    <fullName>DateOf_Payment__c</fullName>
    <label>Date of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DateOfReceipt__c.field-meta.xml
<CustomField>
    <fullName>DateOfReceipt__c</fullName>
    <label>Date of Receipt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Incoterm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>Type of inquiry</description>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OpportunityType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QuoteOfferedDate__c.field-meta.xml
<CustomField>
    <fullName>QuoteOfferedDate__c</fullName>
    <inlineHelpText>The date on which the first active Quote is set to Offered.</inlineHelpText>
    <label>Quote Offered Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QuoteValidTill__c.field-meta.xml
<CustomField>
    <fullName>QuoteValidTill__c</fullName>
    <label>Quote valid till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunitywithquotecreations.recordType-meta.xml
<RecordType>
    <fullName>Opportunitywithquotecreations</fullName>
    <active>true</active>
    <businessProcess>Full Opportunity Process</businessProcess>
    <label>Opportunity with quote creations</label>
</RecordType>

force-app/main/default/globalValueSets/Incoterm.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAD - CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CFR - Costs and freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIF - Cost, Insurance &amp; Freight</fullName>
    </customValue>
    <customValue>
        <fullName>CIP - Freight free insured</fullName>
    </customValue>
    <customValue>
        <fullName>CPT - Freight free</fullName>
    </customValue>
    <customValue>
        <fullName>DAP - Delivered named place</fullName>
    </customValue>
    <customValue>
        <fullName>DPU - Delivered terminal</fullName>
    </customValue>
    <customValue>
        <fullName>DDP - Delivered duty paid</fullName>
    </customValue>
    <customValue>
        <fullName>EXW - Ex works</fullName>
    </customValue>
    <customValue>
        <fullName>FAS - Free longitudinal ship</fullName>
    </customValue>
    <customValue>
        <fullName>FCA - Free carrier</fullName>
    </customValue>
    <customValue>
        <fullName>FOB - Free on board</fullName>
    </customValue>
    <masterLabel>Incoterm</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OpportunityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Mass Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal - Existing Portfolio</label>
    </customValue>
    <masterLabel>Opportunity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PaymentTerms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AA</fullName>
    </customValue>
    <customValue>
        <fullName>AB</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AH</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AJ</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>DA</fullName>
    </customValue>
    <customValue>
        <fullName>DB</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DD</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DF</fullName>
    </customValue>
    <customValue>
        <fullName>DG</fullName>
    </customValue>
    <customValue>
        <fullName>DH</fullName>
    </customValue>
    <customValue>
        <fullName>DI</fullName>
    </customValue>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
/****************************************************************************
* Name: QuoteTriggerHandlerTest
* Author: Impana Paalyam
* Created Date: 02/02/2023
* Description: Test class for Quote Trigger
*****************************************************************************
* Modification log
* Name      Date                    Description
* Developer Name    Date of Modification    Modification Description  
****************************************************************************/
@isTest
public class QuoteTriggerHandlerTest {
    
    @testSetup
    static void setUpData(){
        List<User> userList = TestDataFactory.createUser(3);
        System.runAs(userList[0]) {
            List<Account> act = TestDataFactory.createAccounts(1);
            act[0].ChannelOfDistribution__c = '11';
            update act;
            Account acc = [Select Id, Name, ChannelOfDistribution__c from Account limit 1];
            List<Opportunity> opplst = TestDataFactory.createOpps(1);
            opplst[0].AccountId = acc.id;
            opplst[0].ChannelOfDistribution__c = '11';  
            update opplst;
       }
    }
    @isTest static void testInsertOpportunity(){
        Test.startTest();
        Account acc = [SELECT Id, Name, ChannelOfDistribution__c FROM Account WHERE Name = 'TestAccount0' limit 1];
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'Opportunitywithquotecreations'];
        Opportunity op = new Opportunity(Name = 'Test',
                                         StageName = 'New',
                                         CloseDate = System.today().addMonths(1),
                                         AccountId = acc.Id,
                                         RecordTypeId = rt.ID,
                                         QuoteOfferedDate__c= System.today(),
                                         ChannelOfDistribution__c = '11',
                                                OpportunityType__c = 'Standard Inquiry',
                                               BusinessArea__c ='ZK',
                                               DateOfReceipt__c = System.today(),
                                               CurrencyIsoCode ='EUR',
                                               CalculationTimePoint__c = 'Monthly',
                                               QuoteValidTill__c = System.today(),
                                               Incoterms__c = 'CAD - CAD',
                                               DateOf_Payment__c = 'AA',
                                               Type = 'Existing Business'
                                       );
        insert op;
        Quote qo = new Quote();
        qo.Name = 'TestQuote';
        qo.OpportunityId =op.id; 
        insert qo;
        qo.Status = ConstantClass.OFFERED_STATUS;
        update qo;
        system.assertEquals(op.ChannelOfDistribution__c, '11' , 'ChannelOfDistribution__c should be 11');
        Test.stopTest();
    }
}