force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/DeliveryInstructions__c.object-meta.xml
<CustomObject>
    <label>Delivery Instructions</label>
    <nameField> 
        <displayFormat>LV-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber> 
        <label>LVID</label>
        <type>AutoNumber</type> 
    </nameField>
    <pluralLabel>Delivery Instructions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryInstructions__c/fields/DateOfIssue__c.field-meta.xml
<CustomField>
    <fullName>DateOfIssue__c</fullName>
    <label>Date Of Issue  </label> 
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label> 
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>  
    <label>Publisher</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A.T.M.</fullName>
            </value>
            <value>
                <fullName>AAM</fullName>
            </value>
            <value>
                <fullName>ABC Umformtechnik</fullName>
            </value>
            <value>
                <fullName>ABTech</fullName>
            </value>
            <value>
                <fullName>AFF</fullName>
            </value>
            <value>
                <fullName>AFF ST. FLO</fullName>
            </value>
            <value>
                <fullName>AFF Visserie</fullName>
            </value>
            <value>
                <fullName>AFNOR</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>ARC Automotiv Inc.</fullName>
            </value>
            <value>
                <fullName>ARS Industries</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>ASDO</fullName>
            </value>
            <value>
                <fullName>ASSI</fullName>
            </value>
            <value>
                <fullName>ASTM</fullName>
            </value>
            <value>
                <fullName>ASW</fullName>
            </value>
            <value>
                <fullName>ATE</fullName>
            </value>
            <value>
                <fullName>ATG</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>AUSA</fullName>
            </value>
            <value>
                <fullName>AUTOCAM</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Aartee Bright Bar</fullName>
            </value>
            <value>
                <fullName>Abinsa</fullName>
            </value>
            <value>
                <fullName>Acenta</fullName>
            </value>
            <value>
                <fullName>Aceros Grinon</fullName>
            </value>
            <value>
                <fullName>Aciéries de Bonpertuis</fullName>
            </value>
            <value>
                <fullName>Ador Welding</fullName>
            </value>
            <value>
                <fullName>Agrati</fullName>
            </value>
            <value>
                <fullName>Ahle Federn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision  </label> 
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName> 
    <label>Title  </label> 
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>Norm</fullName>
            </value>
            <value>
                <fullName>QSV</fullName>
            </value>
            <value>
                <fullName>WDB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LVPostion__c/LVPostion__c.object-meta.xml
<CustomObject>
    <label>LV Position</label>
    <nameField>
        <displayFormat>LVPos-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber>
        <label>LVPosition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LV Position</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVPostion__c/fields/CustomerSteelGrade__c.field-meta.xml
<CustomField>
    <fullName>CustomerSteelGrade__c</fullName>
    <label>Customer Steel Grade</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/DimensionAFrom__c.field-meta.xml
<CustomField>
    <fullName>DimensionAFrom__c</fullName>
    <label>Dimension A from in mm</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/DimensionATo__c.field-meta.xml
<CustomField>
    <fullName>DimensionATo__c</fullName>
    <label>Dimension A to in mm</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/HeatTreatmentSales__c.field-meta.xml
<CustomField>
    <fullName>HeatTreatmentSales__c</fullName>
    <label>Heat Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HeatTreatment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/Praekula__c.field-meta.xml
<CustomField>
    <fullName>Praekula__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Präkula</label>
    <referenceTo>Praekula__c</referenceTo>
    <relationshipLabel>LV Position</relationshipLabel>
    <relationshipName>LVPosition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>LV Position</relationshipLabel>
    <relationshipName>LV_Position</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mass Inquiry</fullName>
            </value>
            <value>
                <fullName>Standard Inquiry</fullName>
            </value>
            <value>
                <fullName>Specification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>Type of inquiry</description>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OpportunityType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CustomerSteelGrade__c.field-meta.xml
<CustomField>
    <fullName>CustomerSteelGrade__c</fullName>
    <label>Customer Steel Grade</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DimensionAFrom__c.field-meta.xml
<CustomField>
    <fullName>DimensionAFrom__c</fullName>
    <label>Dimension A from in mm</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DimensionATo__c.field-meta.xml
<CustomField>
    <fullName>DimensionATo__c</fullName>
    <label>Dimension A to in mm</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/HeatTreatmentSales__c.field-meta.xml
<CustomField>
    <fullName>HeatTreatmentSales__c</fullName>
    <label>Heat Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HeatTreatment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Prakula__c.field-meta.xml
<CustomField>
    <fullName>Prakula__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Präkula</label>
    <referenceTo>Praekula__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/Praekula__c.object-meta.xml
<CustomObject>
    <label>Präkula</label>
    <nameField>
        <displayFormat>TA-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber>
        <label>PräkulaID</label> 
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Präkula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Praekula__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account </label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Präkula</relationshipLabel>
    <relationshipName>Pr_kula</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language </label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PraekulaDeliveryInstructions__c/PraekulaDeliveryInstructions__c.object-meta.xml
<CustomObject>
    <label>Praekula Delivery Instructions </label>
    <nameField>
        <displayFormat>TAJun-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber>
        <label>PräkulaJunction</label> 
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Praekula Delivery Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PraekulaDeliveryInstructions__c/fields/DeliveryInstructions__c.field-meta.xml
<CustomField>
    <fullName>DeliveryInstructions__c</fullName>
    <label>Delivery Instructions </label>
    <referenceTo>DeliveryInstructions__c</referenceTo>
    <relationshipLabel>Präkula</relationshipLabel>
    <relationshipName>Praekula_Delivery_Instructions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PraekulaDeliveryInstructions__c/fields/Praekula__c.field-meta.xml
<CustomField>
    <fullName>Praekula__c</fullName>
    <label>Praekula</label>
    <referenceTo>Praekula__c</referenceTo>
    <relationshipLabel>Delivery Instruction</relationshipLabel>
    <relationshipName>Praekula_Delivery_Instructions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/HeatTreatment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>+T-Tempered</fullName>
    </customValue>
    <customValue>
        <fullName>+FP-Treated for ferrite-pearlite structure and hardness span</fullName>
    </customValue>
    <customValue>
        <fullName>+TH-Treated for hardness span</fullName>
    </customValue>
    <customValue>
        <fullName>+S-Treated for cold shear</fullName>
    </customValue>
    <customValue>
        <fullName>+AC-Annealed to obtain spherical carbides</fullName>
    </customValue>
    <customValue>
        <fullName>+N-Normalized annealed or normalizing shaped</fullName>
    </customValue>
    <customValue>
        <fullName>+U-Untreated</fullName>
    </customValue>
    <customValue>
        <fullName>+QT-Quench Hardened-Tempered</fullName>
    </customValue>
    <customValue>
        <fullName>+A-Soft annealed</fullName>
    </customValue>
    <customValue>
        <fullName>+AR-As rolled (without any special rolling and/or heat treatment conditions)</fullName>
    </customValue>
    <masterLabel>Heat Treatment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OpportunityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Mass Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal - Existing Portfolio</label>
    </customValue>
    <masterLabel>Opportunity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrakulaDeliveryInstructionsController.cls
/****************************************************************************
* Name: PrakulaDeliveryInstructionsController
* Author: Harshitha Udaykumar
* Created Date: 06/10/2023
* Description: Controller class for PrakulaDeliveryInstruction - LVPosition Search on OLI.
*****************************************************************************
* Modification log
* Name		Date	           		Description
* Developer Name	Date of Modification	Modification Description  
****************************************************************************/
public with sharing class PrakulaDeliveryInstructionsController {
    /****************************************************************************
* Author Name: Harshitha Udaykumar
* Description: to Fecth the list of prakula records based on the search criteria entered in UI.
* Created Date: 06/10/2023
* Last Modified Date: 
****************************************************************************/
public static List<PraekulaDeliveryInstructions__c> fetchPrakula(List<String> deliveryInstructionsID, String OLIID){
    List<String> lstDIds = deliveryInstructionsID;
    List<PraekulaDeliveryInstructions__c> devinstwithCond = new List<PraekulaDeliveryInstructions__c>();
    Set<String> prakulaId = new Set<String>();
    if(!lstDIds.isEmpty()){
        OpportunityLineItem oppIdRecord = [SELECT id, Opportunity.AccountId, Opportunity.Language__c FROM OpportunityLineItem WHERE Id =:OLIID];
        List<PraekulaDeliveryInstructions__c> devinst = [SELECT Id, Praekula__c, Praekula__r.Name , Praekula__r.Account__c, Praekula__r.Account__r.Name,  Praekula__r.Language__c, DeliveryInstructions__c ,DeliveryInstructions__r.Type__c,DeliveryInstructions__r.Publisher__c, DeliveryInstructions__r.Revision__c, 
                                                         DeliveryInstructions__r.Title__c, DeliveryInstructions__r.DateOfIssue__c
                                                         FROM PraekulaDeliveryInstructions__c WHERE DeliveryInstructions__c In: lstDIds 
                                                        ]; 
        for(PraekulaDeliveryInstructions__c pr : devinst){
            if(pr.Praekula__r.Account__c != null && oppIdRecord.Opportunity.AccountId != null && pr.Praekula__r.Account__c == oppIdRecord.Opportunity.AccountId && pr.Praekula__r.Language__c != null && oppIdRecord.Opportunity.Language__c != null && pr.Praekula__r.Language__c == oppIdRecord.Opportunity.Language__c){
                prakulaId.add(pr.Praekula__c);
            }
        } 
       devinstwithCond = [SELECT Id, Praekula__c, Praekula__r.Name , Praekula__r.Account__c, Praekula__r.Account__r.Name,  Praekula__r.Language__c, DeliveryInstructions__c ,DeliveryInstructions__r.Type__c,DeliveryInstructions__r.Publisher__c, DeliveryInstructions__r.Revision__c, 
                                                         DeliveryInstructions__r.Title__c, DeliveryInstructions__r.DateOfIssue__c
                                                         FROM PraekulaDeliveryInstructions__c WHERE Praekula__c In: prakulaId 
                                                        ]; 
        
    }
    return devinstwithCond;
}
    /****************************************************************************
* Author Name: Naina Butle
* Description: TO search the LV positions based on the Prakula selected.
* Created Date: 09/10/2023
* Last Modified Date: 
****************************************************************************/
    @AuraEnabled
    public static List<LVPostion__c> sendprakulaIds (String prakulaId, String OLIID)
    {
        String[] filtersOR = new String[0];
        OpportunityLineItem oppIdRecord = [SELECT id, Product2Id, Opportunity.AccountId, Prakula__c, Opportunity.OpportunityType__c, DimensionAFrom__c, DimensionATo__c, CustomerSteelGrade__c, Opportunity.Language__c FROM OpportunityLineItem WHERE Id = :OLIID];
        String oppIdRecordCustomerSteelGrade = oppIdRecord.CustomerSteelGrade__c;
        String oppIdRecordProduct2 = oppIdRecord.Product2Id;
        String oppIdRecordPrakula = oppIdRecord.Prakula__c;
        Decimal oppIdRecordDimensionAFrom = oppIdRecord.DimensionAFrom__c;
        Decimal oppIdRecordDimensionATo = oppIdRecord.DimensionATo__c;
        String StandardInquiry = 'Standard Inquiry';
        String MassInquiry = 'Mass Inquiry';
        String strEsc;
        String query = 'SELECT Id, Praekula__c, Name, Praekula__r.Name, Type__c, DimensionAFrom__c, HeatTreatmentSales__c, DimensionATo__c, Product__r.Name, CustomerSteelGrade__c FROM LVPostion__c WHERE ';
        
        if (oppIdRecordPrakula != null) {
            query += 'Praekula__c = :oppIdRecordPrakula AND ';
        }
        
        if (oppIdRecordCustomerSteelGrade != null) {
            query += 'CustomerSteelGrade__c = :oppIdRecordCustomerSteelGrade AND ';
        }
        
        if (oppIdRecordProduct2 != null) {
            query += 'Product__c = :oppIdRecordProduct2 AND ';
        }
        
        /*if (oppIdRecordDimensionAFrom != null) {
            query += 'DimensionAFrom__c <= :oppIdRecordDimensionAFrom AND DimensionATo__c >= :oppIdRecordDimensionAFrom AND ';
        }*/
        
        if (oppIdRecordDimensionATo != null && oppIdRecordDimensionAFrom!= null) {
            query += 'DimensionAFrom__c <= :oppIdRecordDimensionAFrom AND DimensionATo__c >= :oppIdRecordDimensionATo AND ';
        }
        
        
        if (oppIdRecord.Opportunity.OpportunityType__c != null) {
            if (oppIdRecord.Opportunity.OpportunityType__c == StandardInquiry) {
                query += 'Type__c =: StandardInquiry';
            } else if (oppIdRecord.Opportunity.OpportunityType__c == MassInquiry) {
                filtersOR.add('Type__c =: StandardInquiry');
                filtersOR.add('Type__c =: MassInquiry');
            }
        }
        
        if (filtersOR.size() > 0) {
            query += '(' + String.join(filtersOR, ' OR ') + ')';
        } 
        
        if (oppIdRecordDimensionAFrom != null && oppIdRecordDimensionATo == null) {
           query +=' AND (DimensionAFrom__c = :oppIdRecordDimensionAFrom ';
           query +=' OR ';
           query +='(DimensionAFrom__c <= :oppIdRecordDimensionAFrom AND DimensionATo__c >= :oppIdRecordDimensionAFrom))';
        }
        
        if (query.endsWith('AND ')) {     
            query = query.substring(0, query.length() - 4); 
        }
        if (oppIdRecordDimensionAFrom != null){
        strEsc = String.escapeSingleQuotes(query); 
        }
        List<LVPostion__c> lvlst = Database.query(strEsc);
        
        return lvlst;			
    }
    
    @AuraEnabled
    public static List<PraekulaDeliveryInstructions__c> getDeliveryInstructionId(String deliveryInsType, String deliveryInsPublisher, String deliveryInsRevision, String deliveryInsTitle, String deliveryInsDateOfIssue, String OLIID){
        List<String> deliveryInstructionsID = new List<String>();
        String query ;
        Date deliveryInsDateOfIssueDate;
        if(deliveryInsType != null || deliveryInsPublisher != null || deliveryInsRevision != null || deliveryInsTitle != null || deliveryInsDateOfIssue != null ){
            query = 'SELECT Id, Type__c, Publisher__c, Name, DateOfIssue__c, Title__c, Revision__c from DeliveryInstructions__c WHERE ';
        }
        if (deliveryInsType != null) {
            query += 'Type__c  = :deliveryInsType AND ';
        }
        
        if (deliveryInsPublisher != null) {
            query += 'Publisher__c   = :deliveryInsPublisher AND ';
        }
        
        if (deliveryInsRevision != null) {
            query += 'Revision__c   = :deliveryInsRevision AND ';
        }
        
        if (deliveryInsTitle != null) {
            query += 'Title__c   = :deliveryInsTitle AND ';
        }
        
        if (deliveryInsDateOfIssue != null) {
            deliveryInsDateOfIssueDate = Date.valueOf(deliveryInsDateOfIssue);
            query += 'DateOfIssue__c   = :deliveryInsDateOfIssueDate';
        }
        
        if(query != null){
            if (query.endsWith('AND ')) {     
                query = query.substring(0, query.length() - 4); 
            }
            String strEsc = String.escapeSingleQuotes(query); 
            List<DeliveryInstructions__c > deliveryInslst = Database.query(strEsc);
            for(DeliveryInstructions__c dIn : deliveryInslst){
                deliveryInstructionsID.add(dIn.Id);
            } 
        }
        List<PraekulaDeliveryInstructions__c> devinstwithCond = fetchPrakula(deliveryInstructionsID, OLIID);
        return devinstwithCond;
    }
    
}