force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TechnicalRequirement__c.field-meta.xml
<CustomField>
    <fullName>TechnicalRequirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The technical requirement that resulted in this OLI</description>
    <label>Technical Requirement</label>
    <referenceTo>TechnicalRequirement__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/OrgWideSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ability to set the org on and off an alternative basic plan</description>
    <label>Org Wide Settings</label>
</CustomObject>

force-app/main/default/objects/OrgWideSettings__c/fields/ActivateAlternateBasicPlan__c.field-meta.xml
<CustomField>
    <fullName>ActivateAlternateBasicPlan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate Alternate Basic Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/TechnicalRequirement__c.object-meta.xml
<CustomObject>
    <description>Ability to create Standard Inquiry Technical Requirements</description>
    <label>Technical Requirement</label>
    <nameField>
        <label>Technical Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalRequirement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Use accounts to store information</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>TechnicalRequirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <formula>TEXT( Opportunity__r.Language__c )</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use Opportunity to store information</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>TechnicalRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity (t)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/TechnicalOffer__c.field-meta.xml
<CustomField>
    <fullName>TechnicalOffer__c</fullName>
    <label>Technical Offer</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/TextForSelectionQuality__c.field-meta.xml
<CustomField>
    <fullName>TextForSelectionQuality__c</fullName>
    <label>Texts for Selection Quality Dep.</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not in product portfolio</fullName>
            </value>
            <value>
                <fullName>Acceptance of Spec.</fullName>
            </value>
            <value>
                <fullName>Surface according to DIN EN ISO 9443</fullName>
            </value>
            <value>
                <fullName>Surface according to EN ISO 9443</fullName>
            </value>
            <value>
                <fullName>Upset testing</fullName>
            </value>
            <value>
                <fullName>Edge decarburization according to DIN EN ISO 3887-03</fullName>
            </value>
            <value>
                <fullName>Edge decarburization according to DIN EN 10263</fullName>
            </value>
            <value>
                <fullName>Purpose of use</fullName>
            </value>
            <value>
                <fullName>Maraform</fullName>
            </value>
            <value>
                <fullName>Standard sentence: &quot;Further customer requirements&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/TechnicalRequirementTriggerHandlerTest.cls
/****************************************************************************
* Name: TechnicalRequirementTriggerHandlerTest
* Author: Priyanka Kumari
* Created Date: 30/11/2022
* Description: Test class for TechnicalRequirementTriggerHandler
*****************************************************************************
* Modification log
* Name      Date                    Description
* Developer Name    Date of Modification    Modification Description  
****************************************************************************/
@isTest
public class TechnicalRequirementTriggerHandlerTest {
    
    @testSetup
    static void setUpData(){
        List<Account> acc = TestDataFactory.createAccountsWithOpps(1, 1);
        OrgWideSettings__c setting = new OrgWideSettings__c();
        setting.Name = 'Org Wide Info';
        setting.ActivateAlternateBasicPlan__c = false;
        insert setting;
    }   
    
    @isTest
    static void updateTechReqPositive(){
        List<Opportunity> op = [SELECT id, Language__c, AccountId FROM Opportunity LIMIT 1];
        op[0].Language__c = 'DE';
        update op;
        TechnicalRequirement__c tr = New TechnicalRequirement__c();
        tr.Opportunity__c = op[0].id;
        tr.Account__c = op[0].AccountId;
        tr.TextForSelectionQuality__c = 'Not in product portfolio';
        Test.startTest();        
        insert tr;
        List<TechnicalRequirement__c> techReq = [SELECT id, TechnicalOffer__c, TextForSelectionQuality__c,LANGUAGE__C FROM TechnicalRequirement__c LIMIT 1];
        system.assertEquals(techReq[0].TechnicalOffer__c, 'Wir bedauern Ihnen mitteilen zu müssen, dass wir diese Güte nicht in unserem Lieferprogramm führen.' , 'Wir bedauern Ihnen mitteilen zu müssen, dass wir diese Güte nicht in unserem Lieferprogramm führen.');
       	Test.stopTest();
    }
    @isTest
    static void updateTechReqNegative(){
        List<Opportunity> op = [SELECT id, Language__c, AccountId FROM Opportunity LIMIT 1];
        TechnicalRequirement__c tr = New TechnicalRequirement__c();
        tr.Opportunity__c = op[0].id;
        tr.Account__c = op[0].AccountId;
        tr.TextForSelectionQuality__c = 'Not in product portfolio';
        Test.startTest();
        op[0].Language__c = 'FR';
        update op;
        insert tr;
        List<TechnicalRequirement__c> techReq = [SELECT id, TechnicalOffer__c, TextForSelectionQuality__c FROM TechnicalRequirement__c LIMIT 1];
        techReq[0].TextForSelectionQuality__c = 'Acceptance of Spec.';
        update techReq;
        system.assertNotEquals(techReq[0].TechnicalOffer__c, 'Wir bedauern Ihnen mitteilen zu müssen, dass wir diese Güte nicht in unserem Lieferprogramm führen.' , 'Technical offer value should be - "Nous regrettons de vous informer que cette type dacierx nest pas dans notre gamme de produits.');
        Test.stopTest();
    }
    @isTest
    static void deleteOLITest(){
        OpportunityLineItem oli = TestDataFactory.oppLineItemTestData();
        
        TechnicalRequirement__c tr = [SELECT id, Active__c FROM TechnicalRequirement__c LIMIT 1];
        String trId=tr.id;
        Test.startTest();
        tr.Active__c=false;
        update tr;
        List<OpportunityLineItem> oliList = [SELECT id FROM OpportunityLineItem where TechnicalRequirement__c= :trId];
        system.assertEquals(oliList.size(),0, 'Incorrect output');
        Test.stopTest();
    }
    
    
    @isTest
    static void testCloneTR(){
        List<Opportunity> op = [SELECT id, Language__c, AccountId FROM Opportunity LIMIT 1];
        TechnicalRequirement__c tr = New TechnicalRequirement__c();
        tr.Opportunity__c = op[0].id;
        tr.Account__c = op[0].AccountId;
        tr.TextForSelectionQuality__c = 'Not in product portfolio';
        tr.TechnicalOffer__c = 'Testing';
        tr.Quantity__c =2;
        insert tr;
        Id trid=[Select Id from TechnicalRequirement__c where id=:tr.Id].Id;
        System.debug('Inside CloneTest' +trid);
        List<Id> trList=new List<id>();
        trList.add(trid);
        Test.startTest();
        TechnicalRequirementHelper.CloneTechnicalRequirement(trList);
        Id tridnew=[Select Id from TechnicalRequirement__c order by createdDate desc Limit 1].Id;
        system.assertEquals(tr.Quantity__c,2,'Incorrect output');
        Test.stopTest();
    }
    
}