force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/DeliveryInstructions__c.object-meta.xml
<CustomObject>
    <label>Delivery Instructions</label>
    <nameField> 
        <displayFormat>LV-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber> 
        <label>LVID</label>
        <type>AutoNumber</type> 
    </nameField>
    <pluralLabel>Delivery Instructions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryInstructions__c/fields/DateOfIssue__c.field-meta.xml
<CustomField>
    <fullName>DateOfIssue__c</fullName>
    <label>Date Of Issue  </label> 
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label> 
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>  
    <label>Publisher</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A.T.M.</fullName>
            </value>
            <value>
                <fullName>AAM</fullName>
            </value>
            <value>
                <fullName>ABC Umformtechnik</fullName>
            </value>
            <value>
                <fullName>ABTech</fullName>
            </value>
            <value>
                <fullName>AFF</fullName>
            </value>
            <value>
                <fullName>AFF ST. FLO</fullName>
            </value>
            <value>
                <fullName>AFF Visserie</fullName>
            </value>
            <value>
                <fullName>AFNOR</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>ARC Automotiv Inc.</fullName>
            </value>
            <value>
                <fullName>ARS Industries</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>ASDO</fullName>
            </value>
            <value>
                <fullName>ASSI</fullName>
            </value>
            <value>
                <fullName>ASTM</fullName>
            </value>
            <value>
                <fullName>ASW</fullName>
            </value>
            <value>
                <fullName>ATE</fullName>
            </value>
            <value>
                <fullName>ATG</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>AUSA</fullName>
            </value>
            <value>
                <fullName>AUTOCAM</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Aartee Bright Bar</fullName>
            </value>
            <value>
                <fullName>Abinsa</fullName>
            </value>
            <value>
                <fullName>Acenta</fullName>
            </value>
            <value>
                <fullName>Aceros Grinon</fullName>
            </value>
            <value>
                <fullName>Aciéries de Bonpertuis</fullName>
            </value>
            <value>
                <fullName>Ador Welding</fullName>
            </value>
            <value>
                <fullName>Agrati</fullName>
            </value>
            <value>
                <fullName>Ahle Federn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision  </label> 
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName> 
    <label>Title  </label> 
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryInstructions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>Norm</fullName>
            </value>
            <value>
                <fullName>QSV</fullName>
            </value>
            <value>
                <fullName>WDB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LVPostion__c/LVPostion__c.object-meta.xml
<CustomObject>
    <label>LV Position</label>
    <nameField>
        <displayFormat>LVPos-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber>
        <label>LVPosition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LV Position</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVPostion__c/fields/CustomerSteelGrade__c.field-meta.xml
<CustomField>
    <fullName>CustomerSteelGrade__c</fullName>
    <label>Customer Steel Grade</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/DimensionATo__c.field-meta.xml
<CustomField>
    <fullName>DimensionATo__c</fullName>
    <label>Dimension A to in mm</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/Praekula__c.field-meta.xml
<CustomField>
    <fullName>Praekula__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Präkula</label>
    <referenceTo>Praekula__c</referenceTo>
    <relationshipLabel>LV Position</relationshipLabel>
    <relationshipName>LVPosition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LVPostion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mass Inquiry</fullName>
            </value>
            <value>
                <fullName>Standard Inquiry</fullName>
            </value>
            <value>
                <fullName>Specification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>Type of inquiry</description>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OpportunityType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CustomerSteelGrade__c.field-meta.xml
<CustomField>
    <fullName>CustomerSteelGrade__c</fullName>
    <label>Customer Steel Grade</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DimensionATo__c.field-meta.xml
<CustomField>
    <fullName>DimensionATo__c</fullName>
    <label>Dimension A to in mm</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Prakula__c.field-meta.xml
<CustomField>
    <fullName>Prakula__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Präkula</label>
    <referenceTo>Praekula__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TechnicalRequirement__c.field-meta.xml
<CustomField>
    <fullName>TechnicalRequirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The technical requirement that resulted in this OLI</description>
    <label>Technical Requirement</label>
    <referenceTo>TechnicalRequirement__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/Praekula__c.object-meta.xml
<CustomObject>
    <label>Präkula</label>
    <nameField>
        <displayFormat>TA-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber>
        <label>PräkulaID</label> 
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Präkula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Praekula__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account </label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Präkula</relationshipLabel>
    <relationshipName>Pr_kula</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Praekula__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language </label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PraekulaDeliveryInstructions__c/PraekulaDeliveryInstructions__c.object-meta.xml
<CustomObject>
    <label>Praekula Delivery Instructions </label>
    <nameField>
        <displayFormat>TAJun-{YY}-{0}</displayFormat> 
        <startingNumber>1</startingNumber>
        <label>PräkulaJunction</label> 
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Praekula Delivery Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PraekulaDeliveryInstructions__c/fields/DeliveryInstructions__c.field-meta.xml
<CustomField>
    <fullName>DeliveryInstructions__c</fullName>
    <label>Delivery Instructions </label>
    <referenceTo>DeliveryInstructions__c</referenceTo>
    <relationshipLabel>Präkula</relationshipLabel>
    <relationshipName>Praekula_Delivery_Instructions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PraekulaDeliveryInstructions__c/fields/Praekula__c.field-meta.xml
<CustomField>
    <fullName>Praekula__c</fullName>
    <label>Praekula</label>
    <referenceTo>Praekula__c</referenceTo>
    <relationshipLabel>Delivery Instruction</relationshipLabel>
    <relationshipName>Praekula_Delivery_Instructions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/TechnicalRequirement__c.object-meta.xml
<CustomObject>
    <description>Ability to create Standard Inquiry Technical Requirements</description>
    <label>Technical Requirement</label>
    <nameField>
        <label>Technical Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalRequirement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Use accounts to store information</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>TechnicalRequirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <formula>TEXT( Opportunity__r.Language__c )</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/OpportunityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Mass Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal - Existing Portfolio</label>
    </customValue>
    <masterLabel>Opportunity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrakulaDeliveryInstructionsContrTest.cls
@isTest
public class PrakulaDeliveryInstructionsContrTest {
	@testSetup
    static void setUpData(){
        	TestDataFactory.oppLineItemTestData();
            TestDataFactory.createOrgWideSetting();
            TestDataFactory.createPreakulaDeliveryInstruction(3);
            TestDataFactory.createPrakula(3);
            TestDataFactory.createLV(2);
    }
    
    @isTest 
    static void testfetchPrakulatest(){
        Test.startTest();
		List<OpportunityLineItem> oli = [SELECT Id, TechnicalRequirement__c, OpportunityId, PricebookEntryId,  Quantity, UnitPrice, Opportunity.Pricebook2Id FROM OpportunityLineItem LIMIT 3];
        List<Opportunity> opplist = [SELECT ID,Language__c,AccountId FROM  Opportunity WHERE id= :oli[0].OpportunityId];
        
        List<PraekulaDeliveryInstructions__c> deliveryInstructions = [SELECT Id, Praekula__c, Praekula__r.Name , Praekula__r.Account__c, Praekula__r.Account__r.Name,  Praekula__r.Language__c, DeliveryInstructions__c ,DeliveryInstructions__r.Type__c, DeliveryInstructions__r.Publisher__c, DeliveryInstructions__r.Revision__c, 
                                                         DeliveryInstructions__r.Title__c, DeliveryInstructions__r.DateOfIssue__c
                                                         FROM PraekulaDeliveryInstructions__c]; 
        String deliveryInstructionIdInput =  '';
        opplist[0].Language__c = deliveryInstructions[0].Praekula__r.Language__c;
        opplist[0].AccountId = deliveryInstructions[0].Praekula__r.Account__c;
        Update opplist;
        for(integer i = 0; i < 3; i++) {
            deliveryInstructionIdInput += String.valueOf(deliveryInstructions[0].DeliveryInstructions__c);
            if (i < deliveryInstructions.size() - 1) {
                deliveryInstructionIdInput += ',';
            }
        }
        String deliveryInsType = deliveryInstructions[0].DeliveryInstructions__r.Type__c;
        String deliveryInsPublisher = deliveryInstructions[0].DeliveryInstructions__r.Publisher__c; 
        String deliveryInsRevision = deliveryInstructions[0].DeliveryInstructions__r.Revision__c;
        String deliveryInsTitle = deliveryInstructions[0].DeliveryInstructions__r.Title__c;
        String deliveryInsDateOfIssue = String.valueOf(deliveryInstructions[0].DeliveryInstructions__r.DateOfIssue__c);
        String oliID = oli[0].Id;
        List<PraekulaDeliveryInstructions__c> prd = PrakulaDeliveryInstructionsController.getDeliveryInstructionId(deliveryInsType, deliveryInsPublisher, deliveryInsRevision, deliveryInsTitle, deliveryInsDateOfIssue, oliID);
        Test.stopTest();
        System.assertEquals(deliveryInstructions[0].ID, prd[0].ID , 'Fetch Prakula');
    }
    
    @isTest 
    static void testsendprakulaIds(){
        Test.startTest();
        List<OpportunityLineItem> oli = [SELECT Id, TechnicalRequirement__c, OpportunityId, CustomerSteelGrade__c,  Quantity, UnitPrice, DimensionATo__c FROM OpportunityLineItem LIMIT 3];
        oli[0].CustomerSteelGrade__c = '3';
        oli[0].DimensionATo__c = 3;
        update  oli[0];
        List<Opportunity> opplist = [SELECT ID, Language__c, AccountId, OpportunityType__c FROM  Opportunity WHERE id= :oli[0].OpportunityId];
        opplist[0].OpportunityType__c = 'Mass Inquiry';
        update opplist[0];
        Praekula__c Prakula = [Select Id, Language__c, Account__c FROM Praekula__c Limit 1]; 
        PrakulaDeliveryInstructionsController.sendprakulaIds(Prakula.Id, oli[0].Id);
        Test.stopTest();
        System.assertEquals(opplist[0].OpportunityType__c , 'Mass Inquiry' , 'opportunity type should be Mass Inquiry');
    }
    
     @isTest 
    static void testsendprakulaIds1(){
        Test.startTest();
        Praekula__c Prakula = [Select Id, Language__c, Account__c FROM Praekula__c Limit 1]; 
        List<OpportunityLineItem> oli = [SELECT Id, TechnicalRequirement__c, OpportunityId, CustomerSteelGrade__c,  Quantity, UnitPrice, DimensionATo__c FROM OpportunityLineItem LIMIT 3];
        oli[0].CustomerSteelGrade__c = '3';
        oli[0].DimensionATo__c = 3;
        oli[0].Prakula__c = Prakula.Id;
        update  oli[0];
         List<Opportunity> opplist = [SELECT ID, Language__c, AccountId, OpportunityType__c FROM  Opportunity WHERE id= :oli[0].OpportunityId];
        opplist[0].OpportunityType__c = 'Standard Inquiry';
        update opplist[0];
        List<LVPostion__c> lvlst = PrakulaDeliveryInstructionsController.sendprakulaIds(Prakula.Id, oli[0].Id);
        List<LVPostion__c> lvlstactual = new List<LVPostion__c>();
        Test.stopTest();
        System.assertEquals(lvlstactual , lvlst , 'Search Prakula');
    }
    @isTest 
    static void testsendprakulaIds2(){
        Test.startTest();
        Praekula__c Prakula = [Select Id, Language__c, Account__c FROM Praekula__c Limit 1]; 
        List<OpportunityLineItem> oli = [SELECT Id, TechnicalRequirement__c, OpportunityId, CustomerSteelGrade__c,  Quantity, UnitPrice, DimensionATo__c FROM OpportunityLineItem LIMIT 3];
        oli[0].CustomerSteelGrade__c = '3';
        oli[0].DimensionATo__c = null;
        oli[0].Prakula__c = Prakula.Id;
        update  oli[0];
         List<Opportunity> opplist = [SELECT ID, Language__c, AccountId, OpportunityType__c FROM  Opportunity WHERE id= :oli[0].OpportunityId];
        opplist[0].OpportunityType__c = 'Standard Inquiry';
        update opplist[0];
        List<LVPostion__c> lvlst = PrakulaDeliveryInstructionsController.sendprakulaIds(Prakula.Id, oli[0].Id);
        List<LVPostion__c> lvlstactual = new List<LVPostion__c>();
        Test.stopTest();
        System.assertEquals(lvlstactual , lvlst , 'Search Prakula');
    }
}