force-app/main/default/objects/ContentBlock__mdt/ContentBlock__mdt.object-meta.xml
<CustomObject>
    <label>Content Block</label>
    <pluralLabel>Content Block</pluralLabel>
</CustomObject>

force-app/main/default/objects/ContentBlock__mdt/fields/ContentText__c.field-meta.xml
<CustomField>
    <fullName>ContentText__c</fullName>
    <label>Content Text</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContentBlock__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
                <default>true</default>
                <label>EN</label>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentBlock__mdt/fields/PicklistValue__c.field-meta.xml
<CustomField>
    <fullName>PicklistValue__c</fullName>
    <label>Picklist Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TechnicalRequirement__c.field-meta.xml
<CustomField>
    <fullName>TechnicalRequirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The technical requirement that resulted in this OLI</description>
    <label>Technical Requirement</label>
    <referenceTo>TechnicalRequirement__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/TechnicalRequirement__c.object-meta.xml
<CustomObject>
    <description>Ability to create Standard Inquiry Technical Requirements</description>
    <label>Technical Requirement</label>
    <nameField>
        <label>Technical Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalRequirement__c/fields/CheckOnLanguageChange__c.field-meta.xml
<CustomField>
    <fullName>CheckOnLanguageChange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check On Language Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <formula>TEXT( Opportunity__r.Language__c )</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>TechnicalRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/TechnicalOffer__c.field-meta.xml
<CustomField>
    <fullName>TechnicalOffer__c</fullName>
    <label>Technical Offer</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/TextForSelectionQuality__c.field-meta.xml
<CustomField>
    <fullName>TextForSelectionQuality__c</fullName>
    <label>Texts for Selection Quality Dep.</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not in product portfolio</fullName>
            </value>
            <value>
                <fullName>Acceptance of Spec.</fullName>
            </value>
            <value>
                <fullName>Surface according to DIN EN ISO 9443</fullName>
            </value>
            <value>
                <fullName>Surface according to EN ISO 9443</fullName>
            </value>
            <value>
                <fullName>Upset testing</fullName>
            </value>
            <value>
                <fullName>Edge decarburization according to DIN EN ISO 3887-03</fullName>
            </value>
            <value>
                <fullName>Edge decarburization according to DIN EN 10263</fullName>
            </value>
            <value>
                <fullName>Purpose of use</fullName>
            </value>
            <value>
                <fullName>Maraform</fullName>
            </value>
            <value>
                <fullName>Standard sentence: &quot;Further customer requirements&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/recordTypes/TechnicalRequirement.recordType-meta.xml
<RecordType>
    <fullName>TechnicalRequirement</fullName>
    <active>true</active>
    <label>Technical Requirement</label>
</RecordType>

force-app/main/default/classes/TechnicalRequirementHelper.cls
/****************************************************************************
* Name: TechnicalRequirementHelper
* Author: Priyanka Kumari
* Created Date: 30/11/2022
* Description: Handler class for TechnicalRequirement Trigger
*****************************************************************************
* Modification log
* Name			Date	           	Description 
* Monika Kadam          13/1/2023		Added deleteOLI method
****************************************************************************/
public with sharing class TechnicalRequirementHelper {

    /***************************************************************************************************
     * Author Name: Priyanka Kumari
     * Description: Method to populate Technical Offer field value a technical requirement record before insert.
     * Created Date: 30/11/2022
     * Last Modified Date: 
     ****************************************************************************************************/
      public static void populateTechnicalOffer (List<TechnicalRequirement__c> newTechReq, Map<Id, TechnicalRequirement__c> oldtrMap) {
        Map<String, Map<String, String>> contentBlockMap = new Map<String, Map<String, String>>();
        List<String> exeptionList = new List<String>();
        try{
            for(ContentBlock__mdt cb : [SELECT Id, Language__c, PicklistValue__c, ContentText__c FROM ContentBlock__mdt]){
                if(!contentBlockMap.containsKey(cb.PicklistValue__c))
                    contentBlockMap.put(cb.PicklistValue__c, new Map<String, String>());
                Map<String, String> innerMap = contentBlockMap.get(cb.PicklistValue__c);
                innerMap.put(cb.Language__c, cb.ContentText__c);
            }
            for(TechnicalRequirement__c tr : newTechReq){
                List<String> pickListValuesList;
                if(TR.TextForSelectionQuality__c != null){ //1
                    pickListValuesList = TR.TextForSelectionQuality__c.split(';'); 
                    String tempTechOffer=''; 
                    String oldTechOffer ='';           
                    for(String plv : pickListValuesList){
                        Map<String, String> valuesToBeChecked;
                        valuesToBeChecked = contentBlockMap.get(plv);
                        if(oldTrMap != null && valuesToBeChecked != null  && oldTrMap.get(TR.ID).TextForSelectionQuality__c != null && oldTrMap.get(TR.ID).TechnicalOffer__c != null){ //2
                            if(!oldTrMap.get(TR.ID).TextForSelectionQuality__c.contains(plv) && !oldTrMap.get(TR.ID).TechnicalOffer__c.contains(valuesToBeChecked.get(tr.Language__c))){ //3
                                tempTechOffer+= '\n' + valuesToBeChecked.get(tr.Language__c);
                            }
                        }
                        else if(valuesToBeChecked != null){
                            tempTechOffer+= '\n' + valuesToBeChecked.get(tr.Language__c);
                        }
                    }
                    if(oldTrMap != null && (TR.TextForSelectionQuality__c!=oldTrMap.get(TR.ID).TextForSelectionQuality__c)){ //2
                        if(TR.TechnicalOffer__c != null){//3
                            oldTechOffer = TR.TechnicalOffer__c ;  
                        }else if(TR.TechnicalOffer__c == null){
                            oldTechOffer = '';
                        }
                        tempTechOffer = tempTechOffer.replace('null', '');
                        oldTechOffer = oldTechOffer.replace('null', '');
                        TR.TechnicalOffer__c = oldTechOffer + tempTechOffer;
                    }else if(oldTrMap == null){
                        TR.TechnicalOffer__c = oldTechOffer + tempTechOffer;
                    }
                }
                if(tr.Language__c != null){
                    tr.CheckOnLanguageChange__c = false;  
                }
            }
        }
        catch(Exception e){
            String exeptionDetails = e.getCause()+' ; '+e.getLineNumber() + ' ; '+e.getMessage()+' ; '+e.getStackTraceString()
                +' ; '+e.getTypeName() ;
            exeptionList.add(exeptionDetails);
            ExceptionUtilClass.logException(ConstantClass.TECHREQUIREMENT_OBJECT,ConstantClass.TECHREQEXCEPTIONERROR_MSG,'',exeptionDetails,ConstantClass.APEX_CLASS);  
        }
    }
   	public static void deleteOLI (List<TechnicalRequirement__c> newTechReq, Map<Id,TechnicalRequirement__c> oldTechReq) {
        List<Id> trIdlst = new List<Id>();
        List<String> exeptionList = new List<String>();
        try{
         for(TechnicalRequirement__c tr : newTechReq){
             if(tr.Active__c!= oldTechReq.get(tr.Id).Active__c && tr.Active__c==false)   {
                 trIdlst.add(tr.Id);
             }
         }
        List<OpportunityLineitem> delOLIlst=[Select Id from OpportunityLineitem where TechnicalRequirement__c IN :trIdlst]; 
        delete delOLIlst;
        }catch(Exception e){
            String exeptionDetails = e.getCause()+' ; '+e.getLineNumber() + ' ; '+e.getMessage()+' ; '+e.getStackTraceString()
                +' ; '+e.getTypeName() ;
            exeptionList.add(exeptionDetails);
            ExceptionUtilClass.logException(ConstantClass.TECHREQUIREMENT_OBJECT,ConstantClass.OLIDELETEEXCEPTIONERROR_MSG,'',exeptionDetails,ConstantClass.APEX_CLASS);
        }
        
    }
    @InvocableMethod(label = 'Clone Technical Requirement' description = 'Clone Technical Requirement in system mode' category = 'TechnicalRequirement')
    public static List < TechnicalRequirement__c > CloneTechnicalRequirement(List<ID> trIDlst) {
       List < TechnicalRequirement__c > returnList =  new List <TechnicalRequirement__c>();
        String fieldsNames = '';
        for (Schema.SObjectField sObjectField : TechnicalRequirement__c.SObjectType.getDescribe().fields.getMap().values()) {
            fieldsNames += sObjectField.getDescribe().getName() + ',';
        }
        fieldsNames = fieldsNames.removeEnd(',');
        String soqlQuery = 'SELECT ' + fieldsNames + ' FROM TechnicalRequirement__c Where Id IN :trIDlst';
        List<TechnicalRequirement__c> TechReqMaster = Database.query(soqlQuery);
        List<TechnicalRequirement__c> techReqsToInsert = new List<TechnicalRequirement__c>();
        for(TechnicalRequirement__c tempTr : TechReqMaster)
        {
           TechnicalRequirement__c newTechReq = tempTr.clone();
            String Name = tempTr.Name + '-Clone';
            newTechReq.name = Name;
            newTechReq.OpportunityProduct__c = null;
            techReqsToInsert.add(newTechReq);
            returnList.add(newTechReq);
        }
        
        insert techReqsToInsert;
        return returnList;
    }
    
}