force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/ErrorOccuredIn__c.field-meta.xml
<CustomField>
    <fullName>ErrorOccuredIn__c</fullName>
    <label>ErrorOccuredIn</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/ExceptionDetails__c.field-meta.xml
<CustomField>
    <fullName>ExceptionDetails__c</fullName>
    <description>Stores the error/exception message</description>
    <label>Exception Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <description>Stores the Record ID of the Error Object</description>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__e/ExceptionLog__e.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <pluralLabel>Exception Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ExceptionLog__e/fields/ErrorOccuredIn__c.field-meta.xml
<CustomField>
    <fullName>ErrorOccuredIn__c</fullName>
    <label>ErrorOccuredIn</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__e/fields/ExceptionDetails__c.field-meta.xml
<CustomField>
    <fullName>ExceptionDetails__c</fullName>
    <label>Exception Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__e/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessExceptionHandler.cls
/****************************************************************************
* Name: ProcessExceptionHandler
* Author: Harshitha U
* Test Class: ProcessExceptionHandlerTest
* Created Date: 22/08/2022
* Description: Handler Class to create and log exceptions.
(Includes method to create an exception record once the platform event is published)
*****************************************************************************/
public without sharing class ProcessExceptionHandler {
    public void createException(List<ExceptionLog__e> lstex){
        List<Exception__c> listex = new list<Exception__c>();
        for(ExceptionLog__e ex : lstex)
        {
            Exception__c exc = new Exception__c();
            exc.Object__c =ex.Object__c;
            exc.Operation__c = ex.Operation__c;
            exc.ExceptionDetails__c = ex.ExceptionDetails__c;
            exc.RecordID__c = ex.RecordID__c;
            exc.ErrorOccuredIn__c = ex.ErrorOccuredIn__c;
            listex.add(exc);       
        }
        if(!listex.isEmpty())
        {
            INSERT listex;
        }
    }
}