force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/ExceptionDetails__c.field-meta.xml
<CustomField>
    <fullName>ExceptionDetails__c</fullName>
    <description>Stores the error/exception message</description>
    <label>Exception Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <description>Stores the Record ID of the Error Object</description>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__e/ExceptionLog__e.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <pluralLabel>Exception Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ExceptionLog__e/fields/ExceptionDetails__c.field-meta.xml
<CustomField>
    <fullName>ExceptionDetails__c</fullName>
    <label>Exception Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__e/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessExceptionHandlerTest.cls
/****************************************************************************
* Name: ProcessExceptionHandlerTest
* Author: Harshitha U
* Created Date: 22/08/2022
* Description: Test class for ProcessExceptionHandler class.
*****************************************************************************/
@isTest
private class ProcessExceptionHandlerTest {
    @isTest static void testValidateEvent() {
        List<Account> lstaccts = new List<Account>();
        lstaccts = TestDataFactory.createAccounts(1);
        ExceptionLog__e expEvent = new ExceptionLog__e(Object__c='Account', 
                                             ExceptionDetails__c='DML Exception', 
                                             RecordID__c=lstaccts[0].ID);
        
        Test.startTest();
        Database.SaveResult sr = EventBus.publish(expEvent);
        Test.stopTest();
        System.assertEquals(true, sr.isSuccess(),'Incorrect output');
        List<Exception__c> explst = [SELECT Id,Object__c,ExceptionDetails__c FROM Exception__c];
        System.assertEquals(1, explst.size(), 'Incorrect output');
    }
}