force-app/main/default/objects/Opportunity/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>Type of inquiry</description>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OpportunityType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalOLIs__c.field-meta.xml
<CustomField>
    <fullName>TotalOLIs__c</fullName>
    <label>Total OLIs</label>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UsePricingTool__c.field-meta.xml
<CustomField>
    <fullName>UsePricingTool__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Use Pricing Tool</label> 
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/UsePricingTool__c.field-meta.xml
<CustomField>
    <fullName>UsePricingTool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Pricing Tool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/OpportunityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Mass Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal - Existing Portfolio</label>
    </customValue>
    <masterLabel>Opportunity Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityLineItemHelper.cls
/****************************************************************************
* Name: OpportunityLineItemHelper
* Author: Gunjan Saxena
* Created Date: 14/12/2022
* Description: Handler class for Opportunity Line Item Trigger US-873
*****************************************************************************
* Modification log
* Name      Date                    Description
* Developer Name    Date of Modification    Modification Description  
****************************************************************************/
public with sharing class OpportunityLineItemHelper {
    
    /***************************************************************************************************
     * Author Name: Ashutosh Rao
     * Description: Method to populate usePricingTool__C based on parent opporunity's value
     * Created Date: 09/15/2023
     * Last Modified Date: 
     ****************************************************************************************************/
    public static void populateUsePricingTool(List<OpportunityLineItem> lineItems){
        List<Id> opportunityIds = new List<Id>();
        for(OpportunityLineItem oli:lineItems){
            opportunityIds.add(oli.OpportunityId);
        }
        Map<id,Opportunity> opportunityMap = new Map<id,Opportunity>([select id,Name, TotalOLIs__c, USePricingTool__c,OpportunityType__c from opportunity where id in :opportunityIds]);
        for(OpportunityLineItem oli:lineItems){
            Opportunity parentOpty = opportunityMap.get(oli.opportunityId);
            oli.USePricingTool__c  = parentOpty.USePricingTool__c;
            if(parentOpty.OpportunityType__c=='Standard Inquiry')
            {
                oli.Position__c = parentOpty.Name + ' '+((parentOpty.TotalOLIs__c+1)*10);
            }
            else
            {
                oli.Position__c = parentOpty.Name + ' '+(parentOpty.TotalOLIs__c+1);
            }
        }
    }
   
}