force-app/main/default/objects/Opportunity/fields/QuoteOfferedDate__c.field-meta.xml
<CustomField>
    <fullName>QuoteOfferedDate__c</fullName>
    <inlineHelpText>The date on which the first active Quote is set to Offered.</inlineHelpText>
    <label>Quote Offered Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UsePricingTool__c.field-meta.xml
<CustomField>
    <fullName>UsePricingTool__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Use Pricing Tool</label> 
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <label>Certificate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Certificate</fullName>
            </value>
            <value>
                <fullName>2.2 Factory Certificate</fullName>
            </value>
            <value>
                <fullName>3.1 Acceptance Test Certificate</fullName>
            </value>
            <value>
                <fullName>3.2 Acceptance Test Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CustomerSteelGrade__c.field-meta.xml
<CustomField>
    <fullName>CustomerSteelGrade__c</fullName>
    <label>Customer Steel Grade</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DimensionAFrom__c.field-meta.xml
<CustomField>
    <fullName>DimensionAFrom__c</fullName>
    <label>Dimension A from in mm</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DimensioncalculationA__c.field-meta.xml
<CustomField>
    <fullName>DimensioncalculationA__c</fullName>
    <label>Dimension for calculation A</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FinalPrice__c.field-meta.xml
<CustomField>
    <fullName>FinalPrice__c</fullName>
    <label>Offered Price (Net revenue)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FreightCosts__c.field-meta.xml
<CustomField>
    <fullName>FreightCosts__c</fullName>
    <label>Freight Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/HeatTreatmentSales__c.field-meta.xml
<CustomField>
    <fullName>HeatTreatmentSales__c</fullName>
    <label>Heat Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HeatTreatment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PurposeOfUse__c.field-meta.xml
<CustomField>
    <fullName>PurposeOfUse__c</fullName>
    <label>Purpose Of Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-UNKNOWN</fullName>
            </value>
            <value>
                <fullName>2-TRADE</fullName>
            </value>
            <value>
                <fullName>3-GRINDING MATERIAL</fullName>
            </value>
            <value>
                <fullName>4-HEADSTOCK MATERIAL</fullName>
            </value>
            <value>
                <fullName>5-CHUCKING STEEL</fullName>
            </value>
            <value>
                <fullName>6-FLUTED CYLINDER</fullName>
            </value>
            <value>
                <fullName>7-SHOOTING STEEL</fullName>
            </value>
            <value>
                <fullName>8-RIFLE RIFLE</fullName>
            </value>
            <value>
                <fullName>9-TURNING</fullName>
            </value>
            <value>
                <fullName>10-DRAWING MATERIAL</fullName>
            </value>
            <value>
                <fullName>11-DRAWING MATERIAL PRESSURE TIGHT</fullName>
            </value>
            <value>
                <fullName>12-DRAWING MATERIAL FOR DRILLING</fullName>
            </value>
            <value>
                <fullName>13-DRAWING MATERIAL ROUND ON 6-KT.</fullName>
            </value>
            <value>
                <fullName>14-DRAWING MATERIAL ROUND ON 6-KT. PRESSURED.</fullName>
            </value>
            <value>
                <fullName>15-DRAWING MATERIAL FOR PISTON RODS</fullName>
            </value>
            <value>
                <fullName>16-DRAWING MATERIAL FOR WELDING STUDS</fullName>
            </value>
            <value>
                <fullName>17-DRAWING MATERIAL FOR UPSETTING</fullName>
            </value>
            <value>
                <fullName>18-DRAWING STOCK FOR COLD ROLLING</fullName>
            </value>
            <value>
                <fullName>19-PLATING QUALITY</fullName>
            </value>
            <value>
                <fullName>1A-SOFT DRAWING MATERIAL</fullName>
            </value>
            <value>
                <fullName>1B-HARD DRAWING WIRE</fullName>
            </value>
            <value>
                <fullName>1C-PIANO WIRE PIANO WIRE</fullName>
            </value>
            <value>
                <fullName>1D-GRIDS</fullName>
            </value>
            <value>
                <fullName>1E-STEEL FLEX BOWDEN WIRE</fullName>
            </value>
            <value>
                <fullName>1F-STAPLES STAPLES</fullName>
            </value>
            <value>
                <fullName>1G-TEXTILE NEEDLES</fullName>
            </value>
            <value>
                <fullName>1H-HOSEWIRE TUBING WIRE</fullName>
            </value>
            <value>
                <fullName>1K-HEAD SUPPORT WIRE</fullName>
            </value>
            <value>
                <fullName>1L-CABLE WIRE</fullName>
            </value>
            <value>
                <fullName>1M-OFFSHORE/CABLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/QuantityUnit__c.field-meta.xml
<CustomField>
    <fullName>QuantityUnit__c</fullName>
    <label>Quantity Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Moto</fullName>
            </value>
            <value>
                <fullName>Jato</fullName>
            </value>
            <value>
                <fullName>Stück</fullName>
            </value>
            <value>
                <fullName>LBS</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ShortPiece__c.field-meta.xml
<CustomField>
    <fullName>ShortPiece__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Short Piece</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Surcharge1__c.field-meta.xml
<CustomField>
    <fullName>Surcharge1__c</fullName>
    <label>Surcharge 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SurfaceCondition__c.field-meta.xml
<CustomField>
    <fullName>SurfaceCondition__c</fullName>
    <label>Surface Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SurfaceCondition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/UnitOfMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasurement__c</fullName>
    <label>Unit Of Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MM</fullName>
                <default>true</default>
                <label>MM</label>
            </value>
            <value>
                <fullName>Inch</fullName>
            </value>
            <value>
                <fullName>Feet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/UsePricingTool__c.field-meta.xml
<CustomField>
    <fullName>UsePricingTool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Pricing Tool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/HeatTreatment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>+T-Tempered</fullName>
    </customValue>
    <customValue>
        <fullName>+FP-Treated for ferrite-pearlite structure and hardness span</fullName>
    </customValue>
    <customValue>
        <fullName>+TH-Treated for hardness span</fullName>
    </customValue>
    <customValue>
        <fullName>+S-Treated for cold shear</fullName>
    </customValue>
    <customValue>
        <fullName>+AC-Annealed to obtain spherical carbides</fullName>
    </customValue>
    <customValue>
        <fullName>+N-Normalized annealed or normalizing shaped</fullName>
    </customValue>
    <customValue>
        <fullName>+U-Untreated</fullName>
    </customValue>
    <customValue>
        <fullName>+QT-Quench Hardened-Tempered</fullName>
    </customValue>
    <customValue>
        <fullName>+A-Soft annealed</fullName>
    </customValue>
    <customValue>
        <fullName>+AR-As rolled (without any special rolling and/or heat treatment conditions)</fullName>
    </customValue>
    <masterLabel>Heat Treatment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SurfaceCondition.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>As Rolled</fullName>
    </customValue>
    <customValue>
        <fullName>Peeled</fullName>
    </customValue>
    <customValue>
        <fullName>Pickled</fullName>
    </customValue>
    <customValue>
        <fullName>Pickled + coated</fullName>
    </customValue>
    <customValue>
        <fullName>Coated</fullName>
    </customValue>
    <customValue>
        <fullName>Protection Against Rust</fullName>
    </customValue>
    <customValue>
        <fullName>Blasted</fullName>
    </customValue>
    <masterLabel>Surface Condition</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerHelper.cls
public with sharing class QuoteTriggerHelper {
/****************************************************************************
* Author Name: Naina B
* Description: Method to update the QuoteOfferedDate based on the date when related Quote is set in Offered Stage.
* Created Date: 31/01/2023
* Last Modified Date: 
****************************************************************************/
    public static void updateQuoteOfferedDate (Map<Id, Quote> quoteoldMap,Map<Id, Quote> quoteNewMap){
        Set<Id> oppIdSet = new  Set<Id>();
        List<Opportunity> oppList = new List<Opportunity>();
        Map<Id, List<Opportunity>> idVsoppMap = new Map<Id, List<Opportunity>>();
        for(Quote currentQuote : quoteNewMap.values())
        {
            oppIdSet.add(currentQuote.OpportunityId);
        }
        
        for(Opportunity opp : [SELECT Id, QuoteOfferedDate__c  FROM Opportunity WHERE Id IN : oppIdSet]){
            if(!idVsoppMap.containsKey(opp.Id)){
                idVsoppMap.put(opp.Id, new List<Opportunity>());
            }
            idVsoppMap.get(opp.Id).add(opp);
        }
        for(Quote oldQuoteLoop : quoteNewMap.values())
        {
            if(quoteoldMap.get(oldQuoteLoop.Id).Status != ConstantClass.OFFERED_STATUS && oldQuoteLoop.Status == ConstantClass.OFFERED_STATUS){
                for(Opportunity oppLoop : idVsoppMap.get(oldQuoteLoop.OpportunityId)){
                    if(oppLoop.QuoteOfferedDate__c == null){
                        oppLoop.QuoteOfferedDate__c = System.today();
                    }
                }
            }
            
        }
        for(Id oppId : idVsoppMap.KeySet()){
            oppList.addAll(idVsoppMap.get(oppId)); 
        }
        update oppList;    
    }
/****************************************************************************
* Author Name: Harshitha U
* Description: Method to check mandatory fields during Quote Creation.
* Created Date: 05/08/2023
* Last Modified Date: 05/08/2023
****************************************************************************/
public static void checkMandatoryFieldsOnCreation(list<Quote> quoteList,Map<Id, Quote> quoteOldMap, Map<Id, Quote> quoteNewMap){
    List<OpportunityLineItem> relatedOLI = new List<OpportunityLineItem>();
    Map<Id,List<Quote>> quoteIds = new Map<Id,List<Quote>>();
    for (Quote qts : quoteList) {
         if(quoteIds.containsKey(qts.OpportunityId)) {
         List<Quote> quoteIdslst = quoteIds.get(qts.OpportunityId);
         quoteIdslst.add(qts);
     } else {
        List<Quote> newQuoteIds = new List<Quote>();
        newQuoteIds.add(qts);
        quoteIds.put(qts.OpportunityId, newQuoteIds);
    }

   }
    if(!quoteIds.IsEmpty()){
        relatedOLI = [SELECT Id, CustomerSteelGrade__c, HeatTreatmentSales__c, SurfaceCondition__c, UnitOfMeasurement__c, PurposeOfUse__c, Certificate__c, ShortPiece__c, DimensionAFrom__c, FinalPrice__c, Surcharge1__c,
                      FreightCosts__c, Position__c, QuantityUnit__c,OpportunityId,DimensioncalculationA__c,UsePricingTool__c FROM OpportunityLineItem WHERE OpportunityId IN :quoteIds.keyset()];
        
        for(OpportunityLineItem oli : relatedOLI){
            for(Schema.FieldSetMember fieldSetMemberObj : SObjectType.OpportunityLineItem.FieldSets.OLIFieldSet.getFields()){
                if(oli.get(fieldSetMemberObj.getFieldPath()) == null || (oli.UsePricingTool__c == true && oli.DimensioncalculationA__c==null)){
                    for(Quote qt : quoteIds.get(oli.OpportunityId)){
                        qt.addError(System.Label.QuoteError);
                    }
                    break;
                }
            }                
        }
    }
}
}