force-app/main/default/objects/OrgWideSettings__c/OrgWideSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ability to set the org on and off an alternative basic plan</description>
    <label>Org Wide Settings</label>
</CustomObject>

force-app/main/default/objects/OrgWideSettings__c/fields/ActivateAlternateBasicPlan__c.field-meta.xml
<CustomField>
    <fullName>ActivateAlternateBasicPlan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate Alternate Basic Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/fields/Rawmateriallastupdatedon__c.field-meta.xml
<CustomField>
    <fullName>Rawmateriallastupdatedon__c</fullName>
    <label>Raw material last updated on</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/RawMaterial__c.object-meta.xml
<CustomObject>
    <description>Contains the Raw Material Forecast Values</description>
    <label>Rohmaterial</label>
    <nameField>
        <label>Raw Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rohmaterialien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RawMaterial__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Captures the error when Raw Material data is send to Heroku.</description>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/MaterialNumber__c.field-meta.xml
<CustomField>
    <fullName>MaterialNumber__c</fullName>
    <externalId>true</externalId>
    <label>Material Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/RLevel1__c.field-meta.xml
<CustomField>
    <fullName>RLevel1__c</fullName>
    <label>R-Level-1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metall. Einsatz</fullName>
            </value>
            <value>
                <fullName>Nichtmetall. Einsatz</fullName>
            </value>
            <value>
                <fullName>Zuschläge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/RLevel2__c.field-meta.xml
<CustomField>
    <fullName>RLevel2__c</fullName>
    <label>R-Level-2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RLevel1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schrott</fullName>
            </value>
            <value>
                <fullName>Legierungen</fullName>
            </value>
            <value>
                <fullName>Roheisen</fullName>
            </value>
            <value>
                <fullName>Nichtmetall. Zuschläge</fullName>
            </value>
            <value>
                <fullName>Energie / Medien</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/RLevel3__c.field-meta.xml
<CustomField>
    <fullName>RLevel3__c</fullName>
    <label>R-Level-3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RLevel2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eigenschrott</fullName>
            </value>
            <value>
                <fullName>Kaufschrott</fullName>
            </value>
            <value>
                <fullName>Aluminium</fullName>
            </value>
            <value>
                <fullName>Bleigranalien</fullName>
            </value>
            <value>
                <fullName>Chrom</fullName>
            </value>
            <value>
                <fullName>Mangan</fullName>
            </value>
            <value>
                <fullName>Silizium</fullName>
            </value>
            <value>
                <fullName>Molybdän</fullName>
            </value>
            <value>
                <fullName>Nickel</fullName>
            </value>
            <value>
                <fullName>Tellur</fullName>
            </value>
            <value>
                <fullName>Selen</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Bismut</fullName>
            </value>
            <value>
                <fullName>Vanadium</fullName>
            </value>
            <value>
                <fullName>Roheisen</fullName>
            </value>
            <value>
                <fullName>Entschwefelungsmittel</fullName>
            </value>
            <value>
                <fullName>Kalk</fullName>
            </value>
            <value>
                <fullName>Kohlungsmittel und Koks</fullName>
            </value>
            <value>
                <fullName>Sonstige Zuschläge</fullName>
            </value>
            <value>
                <fullName>Sonstige Legierungen</fullName>
            </value>
            <value>
                <fullName>Delta Gas zu Grundplan</fullName>
            </value>
            <value>
                <fullName>Delta Strom zu Grundplan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint10__c.field-meta.xml
<CustomField>
    <fullName>TimePoint10__c</fullName>
    <label>Time Point 10</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint11__c.field-meta.xml
<CustomField>
    <fullName>TimePoint11__c</fullName>
    <label>Time Point 11</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint12__c.field-meta.xml
<CustomField>
    <fullName>TimePoint12__c</fullName>
    <label>Time Point 12</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint13__c.field-meta.xml
<CustomField>
    <fullName>TimePoint13__c</fullName>
    <label>Time Point 13</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint14__c.field-meta.xml
<CustomField>
    <fullName>TimePoint14__c</fullName>
    <label>Time Point 14</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint15__c.field-meta.xml
<CustomField>
    <fullName>TimePoint15__c</fullName>
    <label>Time Point 15</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint16__c.field-meta.xml
<CustomField>
    <fullName>TimePoint16__c</fullName>
    <label>Time Point 16</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint17__c.field-meta.xml
<CustomField>
    <fullName>TimePoint17__c</fullName>
    <label>Time Point 17</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint18__c.field-meta.xml
<CustomField>
    <fullName>TimePoint18__c</fullName>
    <label>Time Point 18</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint1__c.field-meta.xml
<CustomField>
    <fullName>TimePoint1__c</fullName>
    <label>Time Point 1</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint2__c.field-meta.xml
<CustomField>
    <fullName>TimePoint2__c</fullName>
    <label>Time Point 2</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint3__c.field-meta.xml
<CustomField>
    <fullName>TimePoint3__c</fullName>
    <label>Time Point 3</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint4__c.field-meta.xml
<CustomField>
    <fullName>TimePoint4__c</fullName>
    <label>Time Point 4</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint5__c.field-meta.xml
<CustomField>
    <fullName>TimePoint5__c</fullName>
    <label>Time Point 5</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint6__c.field-meta.xml
<CustomField>
    <fullName>TimePoint6__c</fullName>
    <label>Time Point 6</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint7__c.field-meta.xml
<CustomField>
    <fullName>TimePoint7__c</fullName>
    <label>Time Point 7</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint8__c.field-meta.xml
<CustomField>
    <fullName>TimePoint8__c</fullName>
    <label>Time Point 8</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/TimePoint9__c.field-meta.xml
<CustomField>
    <fullName>TimePoint9__c</fullName>
    <label>Time Point 9</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RawMaterial__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
                <label>Internal</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>External</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendRawMaterialsToHerokuTest.cls
/****************************************************************************
* Name: SendRawMaterialsToHerokuTest
* Author: Harshitha U
* Created Date: 1/12/2022
* Description: Test class for SendRawMaterialsToHeroku
*****************************************************************************
* Modification log
* Name		     Date	           		Description
* Developer Name	Date of Modification	Modification Description   
****************************************************************************/
@isTest
public class SendRawMaterialsToHerokuTest {
    @testSetup static void setUpData() { 
        List<RawMaterial__c> rm = TestDataFactory.createRM(1);
        OrgWideSettings__c setting = new OrgWideSettings__c();
        setting.Name = 'Org Wide Info';
        setting.ActivateAlternateBasicPlan__c = false;
        setting.Rawmateriallastupdatedon__c = System.today();
        insert setting;
    }
     @isTest static void testPostCallout(){
        Test.startTest();
        SendRawMaterialsToHeroku.RawMaterialData  wrp = new SendRawMaterialsToHeroku.RawMaterialData();
        Test.setMock(HttpCalloutMock.class, new MockSuccess());
        List<RawMaterial__c> rm1 = new List<RawMaterial__c>();
        List<List<RawMaterial__c>> rm2 = new List<List<RawMaterial__c>>();
        rm1= [Select Id,MaterialNumber__c,TimePoint1__c, TimePoint10__c, TimePoint11__c, 
                                     TimePoint12__c, TimePoint13__c, TimePoint14__c, TimePoint15__c, TimePoint16__c, TimePoint3__c, TimePoint4__c, TimePoint5__c, TimePoint6__c, TimePoint7__c, TimePoint8__c, TimePoint9__c, TimePoint17__c, TimePoint18__c, TimePoint2__c,
                                     RLevel2__c, RLevel1__c, RLevel3__c,Type__c,error__c from RawMaterial__c];
        rm2.add(rm1);
        SendRawMaterialsToHeroku.sendDataToHeroku(rm2);
         List<RawMaterial__c> rawmaterialList= [Select Id,MaterialNumber__c,TimePoint1__c, TimePoint10__c, TimePoint11__c, 
                                     TimePoint12__c, TimePoint13__c, TimePoint14__c, TimePoint15__c, TimePoint16__c, TimePoint3__c, TimePoint4__c, TimePoint5__c, TimePoint6__c, TimePoint7__c, TimePoint8__c, TimePoint9__c, TimePoint17__c, TimePoint18__c, TimePoint2__c,
                                     RLevel2__c, RLevel1__c, RLevel3__c,Type__c,error__c from RawMaterial__c];
         System.assertEquals(rawmaterialList.size(), 0, 'Incorrect output');
        Test.stopTest();
    }
    
        @isTest static void testErrorPostCallout(){
        Test.startTest();
        SendRawMaterialsToHeroku.RawMaterialData  wrp = new SendRawMaterialsToHeroku.RawMaterialData();
        Test.setMock(HttpCalloutMock.class, new Mock());
        List<RawMaterial__c> rm1 = new List<RawMaterial__c>();
        List<List<RawMaterial__c>> rm2 = new List<List<RawMaterial__c>>();
        rm1= [Select Id,MaterialNumber__c,TimePoint1__c, TimePoint10__c, TimePoint11__c, 
                                     TimePoint12__c, TimePoint13__c, TimePoint14__c, TimePoint15__c, TimePoint16__c, TimePoint3__c, TimePoint4__c, TimePoint5__c, TimePoint6__c, TimePoint7__c, TimePoint8__c, TimePoint9__c, TimePoint17__c, TimePoint18__c, TimePoint2__c,
                                     RLevel2__c, RLevel1__c, RLevel3__c,Type__c,error__c from RawMaterial__c];
        rm2.add(rm1);
        SendRawMaterialsToHeroku.sendDataToHeroku(rm2);
         List<RawMaterial__c> rawmaterialList= [Select Id,MaterialNumber__c,TimePoint1__c, TimePoint10__c, TimePoint11__c, 
                                     TimePoint12__c, TimePoint13__c, TimePoint14__c, TimePoint15__c, TimePoint16__c, TimePoint3__c, TimePoint4__c, TimePoint5__c, TimePoint6__c, TimePoint7__c, TimePoint8__c, TimePoint9__c, TimePoint17__c, TimePoint18__c, TimePoint2__c,
                                     RLevel2__c, RLevel1__c, RLevel3__c,Type__c,error__c from RawMaterial__c];
         System.assertNotEquals(rawmaterialList.size(), 0, 'Incorrect output');
        Test.stopTest();
    }
    
    @isTest static void testNegative(){
        Test.startTest();
        SendRawMaterialsToHeroku.RawMaterialData  wrp = new SendRawMaterialsToHeroku.RawMaterialData();
        Test.setMock(HttpCalloutMock.class, new Mock());
        List<RawMaterial__c> rm1 = new List<RawMaterial__c>();
        List<List<RawMaterial__c>> rm2 = new List<List<RawMaterial__c>>();
        rm1= [Select Id,MaterialNumber__c,TimePoint1__c, TimePoint10__c, TimePoint11__c, 
                                     TimePoint12__c, TimePoint13__c, TimePoint14__c, TimePoint15__c, TimePoint16__c, TimePoint3__c, TimePoint4__c, TimePoint5__c, TimePoint6__c, TimePoint7__c, TimePoint8__c, TimePoint9__c, TimePoint17__c, TimePoint18__c, TimePoint2__c,
                                     RLevel2__c, RLevel1__c, RLevel3__c from RawMaterial__c];
        rm2.add(rm1);
        SendRawMaterialsToHeroku.sendDataToHeroku(rm2);
        List<RawMaterial__c> rawmaterialList= [Select Id,MaterialNumber__c,TimePoint1__c, TimePoint10__c, TimePoint11__c, 
                                     TimePoint12__c, TimePoint13__c, TimePoint14__c, TimePoint15__c, TimePoint16__c, TimePoint3__c, TimePoint4__c, TimePoint5__c, TimePoint6__c, TimePoint7__c, TimePoint8__c, TimePoint9__c, TimePoint17__c, TimePoint18__c, TimePoint2__c,
                                     RLevel2__c, RLevel1__c, RLevel3__c,Type__c,error__c from RawMaterial__c];
         System.assertNotEquals(rawmaterialList.size(), 0, 'Incorrect output');
        Test.stopTest();
    }
    
    private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"status": "error","message": "Raw material records not created.","data": [{ "material_raw_id": "00000001","type": "E","status_code": 400,"status_message": "duplicate material_raw_id and type combination"}]}');     
            response.setStatusCode(400);
            return response; 
        }
    }
    private class MockSuccess implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"status": "Success"}');     
            response.setStatusCode(200);
            return response; 
        }
    }
}