force-app/main/default/objects/InvoicedOrders__c/InvoicedOrders__c.object-meta.xml
<CustomObject>
    <label>Invoiced Order</label>
    <nameField>
        <label>Invoiced Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoiced Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicedOrders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Orders</relationshipLabel>
    <relationshipName>Invoiced_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessArea</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/fields/Nettoerloes__c.field-meta.xml
<CustomField>
    <fullName>Nettoerloes__c</fullName>
    <label>Nettoerloes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/fields/ProductCategoryBusinessArea__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryBusinessArea__c</fullName>
    <label>Product Category Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductGroupBusinessArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>Without B10</fullName>
                <isActive>false</isActive>
                <label>Without B10</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/fields/ProductGroupBusinessArea__c.field-meta.xml
<CustomField>
    <fullName>ProductGroupBusinessArea__c</fullName>
    <label>Product Group Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinessArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>BusinessSubgroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/fields/SoldAmount__c.field-meta.xml
<CustomField>
    <fullName>SoldAmount__c</fullName>
    <label>Sold Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/BusinessArea.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZK</fullName>
        <label>Cold Heading</label>
    </customValue>
    <customValue>
        <fullName>ZF</fullName>
        <label>Spring Steel</label>
    </customValue>
    <customValue>
        <fullName>ZS</fullName>
        <label>Free Cutting Steel (SZO)</label>
    </customValue>
    <customValue>
        <fullName>ZZ</fullName>
        <label>Drawing Grades</label>
    </customValue>
    <customValue>
        <fullName>ZW</fullName>
        <label>Bearing Steel</label>
    </customValue>
    <customValue>
        <fullName>ZM</fullName>
        <label>Forging Steel</label>
    </customValue>
    <customValue>
        <fullName>00</fullName>
        <label>Across Business Areas</label>
    </customValue>
    <masterLabel>Business Area</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/BusinessSubgroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Welding Wire (SZW)</fullName>
        <label>Welding Wire</label>
    </customValue>
    <customValue>
        <fullName>Tyre Cord</fullName>
    </customValue>
    <customValue>
        <fullName>Low Carbon</fullName>
    </customValue>
    <customValue>
        <fullName>High Carbon</fullName>
    </customValue>
    <masterLabel>Product Group Business Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RollouttoAccountlevelBatch.cls
/****************************************************************************
* Name: RollouttoAccountlevelBatch
* Author: Gunjan Saxena
* Created Date: 05/22/2023
* Class Name: RollouttoAccountlevelBatch 
* Description: Batch Class for reset the Forecast sold Amount on Account level. 
* US-4374
*****************************************************************************/
/*****************************************************************************
* Modification log
* Name		        Date	           		Description
* Developer Name	Date of Modification	Modification Description  
* Gunjan Saxena		22/05/2023				Created 
****************************************************************************/
global class RollouttoAccountlevelBatch implements Database.Batchable<sObject>,Database.Stateful{
    
    //global Variables;    
    global  MAP<string,decimal> OrderShareMap = new MAP<string,decimal>();
    global  MAP<string,decimal> NetOrderShareMap = new MAP<string,decimal>();
    global  MAP<string,decimal> NetOrderSharepercentMap = new MAP<string,decimal>();
    public RollouttoAccountlevelBatch(){
        
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
       return Database.getQueryLocator([SELECT Id, Account__c,BusinessArea__c,SoldAmount__c,Nettoerloes__c, InvoiceDate__c,ProductCategoryBusinessArea__c,ProductGroupBusinessArea__c FROM InvoicedOrders__c 
                                         where InvoiceDate__c >=  :system.today().addMonths(-3).toStartOfMonth() AND InvoiceDate__c <  :system.today().toStartOfMonth() 
                                        order by BusinessArea__c ]); 
    }
    public void execute(Database.BatchableContext BC, 
                        List<InvoicedOrders__c> scope){
                           for(InvoicedOrders__c Invo : scope){
                               string BusinessArea = '';
                                    if(Invo.BusinessArea__c == 'ZZ'){
                                        if(Invo.ProductGroupBusinessArea__c == 'Low Carbon'){
                                            BusinessArea = Invo.BusinessArea__c + ' - ' + Invo.ProductGroupBusinessArea__c + ' - ' + Invo.ProductCategoryBusinessArea__c; 
                                        }else{
                                            BusinessArea = Invo.BusinessArea__c + ' - ' + Invo.ProductGroupBusinessArea__c ; 
                                        }                                        
                                    }else{
                                        BusinessArea = Invo.BusinessArea__c;                                        
                                    }
                               if(Invo.Account__c != null){
                                  if(OrderShareMap.containsKey(Invo.Account__c+'_'+BusinessArea)){
                                        OrderShareMap.put(Invo.Account__c+'_'+BusinessArea, Invo.SoldAmount__c + OrderShareMap .get(Invo.Account__c+'_'+BusinessArea));
                                    }else{
                                        OrderShareMap.put(Invo.Account__c+'_'+BusinessArea, Invo.SoldAmount__c);
                                    }
                               }
                               if(NetOrderShareMap.containsKey(BusinessArea)){
                                        NetOrderShareMap.put(BusinessArea, Invo.SoldAmount__c + NetOrderShareMap .get(BusinessArea));
                                    }else{
                                        NetOrderShareMap.put(BusinessArea, Invo.SoldAmount__c);
                                    }
                           }
                        }
    public void finish(Database.BatchableContext BC){
        for(string str : OrderShareMap.keySet()){
            string BA = str.substringAfter('_');
            if(OrderShareMap.containsKey(str) && NetOrderShareMap.containsKey(BA))
            NetOrderSharepercentMap.put(str,OrderShareMap.get(str)/NetOrderShareMap.get(BA));
        }
        SalesPlanningFAmountupdateBatch b = new SalesPlanningFAmountupdateBatch(NetOrderSharepercentMap); 
     	 Database.executeBatch(b);
    }

}