force-app/main/default/objects/FinishedGoods__c/FinishedGoods__c.object-meta.xml
<CustomObject>
    <label>Finished Goods</label>
    <nameField>
        <label>Finished Goods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finished Goods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinishedGoods__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessArea</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/MaterialNumber__c.field-meta.xml
<CustomField>
    <fullName>MaterialNumber__c</fullName>
    <description>Capture SAP Material numbers for a finished product</description>
    <externalId>true</externalId>
    <label>Material Number</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/ProductGroupBusinessArea__c.field-meta.xml
<CustomField>
    <fullName>ProductGroupBusinessArea__c</fullName>
    <label>Product Group Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessSubgroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/InvoicedOrders__c.object-meta.xml
<CustomObject>
    <label>Invoiced Order</label>
    <nameField>
        <label>Invoiced Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoiced Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicedOrders__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessArea</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoicedOrders__c/fields/ProductGroupBusinessArea__c.field-meta.xml
<CustomField>
    <fullName>ProductGroupBusinessArea__c</fullName>
    <label>Product Group Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinessArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>BusinessSubgroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AppointedDayCalculation__c.field-meta.xml
<CustomField>
    <fullName>AppointedDayCalculation__c</fullName>
    <label>Appointed Day Calculation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CalculationTimePoint__c.field-meta.xml
<CustomField>
    <fullName>CalculationTimePoint__c</fullName>
    <defaultValue>&quot;Monthly&quot;</defaultValue>
    <label>Time reference calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProductGroupBusinessArea__c.field-meta.xml
<CustomField>
    <fullName>ProductGroupBusinessArea__c</fullName>
    <label>Product Group Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinessArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>BusinessSubgroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CostOfProduction__c.field-meta.xml
<CustomField>
    <fullName>CostOfProduction__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Costs (internal view)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DateOfDelivery__c.field-meta.xml
<CustomField>
    <fullName>DateOfDelivery__c</fullName>
    <label>Date Of Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FinalPrice__c.field-meta.xml
<CustomField>
    <fullName>FinalPrice__c</fullName>
    <label>Offered Price (Net revenue)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FinishedGoods__c.field-meta.xml
<CustomField>
    <fullName>FinishedGoods__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finished Goods (For Price Caclulation)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FinishedGoods__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FinishedGoods__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/LastRefreshedDate__c.field-meta.xml
<CustomField>
    <fullName>LastRefreshedDate__c</fullName>
    <description>Populated every time CoP is fetched from Heroku</description>
    <label>Last Refreshed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/LastSavedFinalPriceDate__c.field-meta.xml
<CustomField>
    <fullName>LastSavedFinalPriceDate__c</fullName>
    <label>Last Saved Final Price Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/OrientationPrice__c.field-meta.xml
<CustomField>
    <fullName>OrientationPrice__c</fullName>
    <label>Orientation Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PriceLevel1__c.field-meta.xml
<CustomField>
    <fullName>PriceLevel1__c</fullName>
    <label>Price Level 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PriceLevel2__c.field-meta.xml
<CustomField>
    <fullName>PriceLevel2__c</fullName>
    <label>Price Level 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PriceLevel3__c.field-meta.xml
<CustomField>
    <fullName>PriceLevel3__c</fullName>
    <label>Price Level 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PriceLevel4__c.field-meta.xml
<CustomField>
    <fullName>PriceLevel4__c</fullName>
    <label>Price Level 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PriceLevel5__c.field-meta.xml
<CustomField>
    <fullName>PriceLevel5__c</fullName>
    <label>Price Level 5</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ProductFinderStatus__c.field-meta.xml
<CustomField>
    <fullName>ProductFinderStatus__c</fullName>
    <description>This field shows the result of the product finder process</description>
    <label>Product Finder Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Matching FMN found</fullName>
            </value>
            <value>
                <fullName>New combination of steel grade and rolling mill/further processing created. Only use as price indicator</fullName>
            </value>
            <value>
                <fullName>No matching steel grade found. Reach out to Controlling.</fullName>
            </value>
            <value>
                <fullName>Inductive heat treatment. Reach out to Controlling.</fullName>
            </value>
            <value>
                <fullName>FMN specified on Position</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TechnicalRequirement__c.field-meta.xml
<CustomField>
    <fullName>TechnicalRequirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The technical requirement that resulted in this OLI</description>
    <label>Technical Requirement</label>
    <referenceTo>TechnicalRequirement__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/OrgWideSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ability to set the org on and off an alternative basic plan</description>
    <label>Org Wide Settings</label>
</CustomObject>

force-app/main/default/objects/OrgWideSettings__c/fields/ActivateAlternateBasicPlan__c.field-meta.xml
<CustomField>
    <fullName>ActivateAlternateBasicPlan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate Alternate Basic Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/fields/Rawmateriallastupdatedon__c.field-meta.xml
<CustomField>
    <fullName>Rawmateriallastupdatedon__c</fullName>
    <label>Raw material last updated on</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PriceLevelSurcharge__c/PriceLevelSurcharge__c.object-meta.xml
<CustomObject>
    <description>To store and edit the CO2 surcharge for the price level 1 creation</description>
    <label>Price Level Surcharge</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Level Surcharges</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceLevelSurcharge__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessArea</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PriceLevelSurcharge__c/fields/BusinessSubgroup__c.field-meta.xml
<CustomField>
    <fullName>BusinessSubgroup__c</fullName>
    <label>Product Group Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinessArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>BusinessSubgroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PriceLevelSurcharge__c/fields/PriceLevel__c.field-meta.xml
<CustomField>
    <fullName>PriceLevel__c</fullName>
    <label>Price Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2c</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>Orientation Price</fullName>
            </value>
            <value>
                <fullName>2b</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/TechnicalRequirement__c.object-meta.xml
<CustomObject>
    <description>Ability to create Standard Inquiry Technical Requirements</description>
    <label>Technical Requirement</label>
    <nameField>
        <label>Technical Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalRequirement__c/fields/BusinessArea__c.field-meta.xml
<CustomField>
    <fullName>BusinessArea__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessArea</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/FinishedGoods__c.field-meta.xml
<CustomField>
    <fullName>FinishedGoods__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Finished goods number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FinishedGoods__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FinishedGoods__c</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>Technical_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/ProductGroupBusinessArea__c.field-meta.xml
<CustomField>
    <fullName>ProductGroupBusinessArea__c</fullName>
    <label>Product Group Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinessArea__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>BusinessSubgroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BusinessArea.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZK</fullName>
        <label>Cold Heading</label>
    </customValue>
    <customValue>
        <fullName>ZF</fullName>
        <label>Spring Steel</label>
    </customValue>
    <customValue>
        <fullName>ZS</fullName>
        <label>Free Cutting Steel (SZO)</label>
    </customValue>
    <customValue>
        <fullName>ZZ</fullName>
        <label>Drawing Grades</label>
    </customValue>
    <customValue>
        <fullName>ZW</fullName>
        <label>Bearing Steel</label>
    </customValue>
    <customValue>
        <fullName>ZM</fullName>
        <label>Forging Steel</label>
    </customValue>
    <customValue>
        <fullName>00</fullName>
        <label>Across Business Areas</label>
    </customValue>
    <masterLabel>Business Area</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/BusinessSubgroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Welding Wire (SZW)</fullName>
        <label>Welding Wire</label>
    </customValue>
    <customValue>
        <fullName>Tyre Cord</fullName>
    </customValue>
    <customValue>
        <fullName>Low Carbon</fullName>
    </customValue>
    <customValue>
        <fullName>High Carbon</fullName>
    </customValue>
    <masterLabel>Product Group Business Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricingToolControllerTest.cls
/****************************************************************************
* Name: PricingToolControllerTest
* Author: Naina Butle
* Created Date: 13/09/2022
* Description: test class of PricingToolController
*****************************************************************************
* Modification log
* Name		     Date	           		Description 
* Developer Name	Date of Modification	Modification Description   
****************************************************************************/
@isTest
public class PricingToolControllerTest {
    @testSetup static void setUpData() { 
        TestDataFactory.createpriceBookEntry();
        TestDataFactory.oppLineItemTestData();
        TestDataFactory.createFG(1);
        TestDataFactory.createPls(8);
        TestDataFactory.createIOs(2);
               
        List<PriceLevelSurcharge__c> pls1 = [SELECT id from PriceLevelSurcharge__c ];
        pls1[1].PriceLevel__c = '2c';
        pls1[1].BusinessArea__c = 'ZK';
        pls1[0].PriceLevel__c = '2b';
        pls1[2].BusinessArea__c = 'ZK';
        pls1[2].PriceLevel__c = '3';
        pls1[2].Country__c = 'IN';
        pls1[3].PriceLevel__c = '5';
        pls1[3].BusinessArea__c = 'ZZ';
        pls1[3].BusinessSubgroup__c = 'Welding Wire (SZW)';
        pls1[4].BusinessArea__c = 'ZK';
        pls1[4].PriceLevel__c = 'Orientation Price';
        pls1[5].PriceLevel__c = '5';
        pls1[5].BusinessArea__c = 'ZK';
        pls1[6].BusinessArea__c = 'ZZ';
        pls1[6].PriceLevel__c = 'Orientation Price';
        pls1[6].BusinessSubgroup__c = 'Welding Wire (SZW)';
        pls1[7].BusinessArea__c = 'ZZ';
        pls1[7].PriceLevel__c = '2c';
        pls1[7].BusinessSubgroup__c = 'Welding Wire (SZW)';
        update pls1;
               
		OrgWideSettings__c setting = new OrgWideSettings__c();
        setting.Name = 'Org Wide Info';
        setting.ActivateAlternateBasicPlan__c = false;
        setting.Rawmateriallastupdatedon__c = System.today();
        insert setting;
    }
    
    @isTest static void getOpportunityLineItemTest(){
        OpportunityLineItem oppItem = [SELECT Id, OpportunityId, Quantity, DateOfDelivery__c, PricebookEntryId, TotalPrice, Product2Id, CostOfProduction__c, PriceLevel1__c, PriceLevel2__c,Opportunity.StageName,
                                        PriceLevel3__c,PriceLevel4__c,PriceLevel5__c,OrientationPrice__c,FinalPrice__c FROM OpportunityLineItem LIMIT 1];
        Test.startTest();
        List<PricingToolController.PLWrapperData> oppList=PricingToolController.getOpportunityLineItem(oppItem.id);
        System.assertEquals(1, oppList.size(), '1 records should be returned');
        List<PricingToolController.MarginWrapperData> oppMarginList = PricingToolController.getMarginPriceDetails(oppItem.id);
        system.assertEquals(1, oppMarginList.size(), '1 records should be returned');
        Test.stopTest();
    }
    
    @isTest static void saveFinalPrice(){
        OpportunityLineItem oppItem = [SELECT Id,OpportunityId,Quantity,PricebookEntryId,TotalPrice,Product2Id,CostOfProduction__c from OpportunityLineItem LIMIT 1];
        Test.startTest();
        Decimal FinalPrice = PricingToolController.saveFinalPrice(23.00, oppItem.id);
        System.assertEquals(23.00, FinalPrice, 'Final Price Should be returned');
        Test.stopTest();
    }
    
    @isTest static void getPublicGroupUsers(){
        Test.startTest();
        Boolean ismemberofGroup = PricingToolController.getPublicGroupUsers();
        System.assertEquals(true, ismemberofGroup, 'ismemberofGroup should return true');
        Test.stopTest();
    }
    
    @isTest static void getReRunProductFinder(){
    	TechnicalRequirement__c TR = [SELECT Id FROM TechnicalRequirement__c LIMIT 1];
        OpportunityLineItem oppItem= [SELECT Id, OpportunityId, Quantity, PricebookEntryId,
                                      TotalPrice, Product2Id, CostOfProduction__c, TechnicalRequirement__c 
                                      FROM OpportunityLineItem LIMIT 1 ];
        oppItem.TechnicalRequirement__c = TR.Id;
        update oppItem;
        Test.startTest();
        List<OpportunityLineItem> rerun = PricingToolController.ReRunProductFinder(oppItem.Id);
        System.assertEquals(1, rerun.size(), 'reruning the method');
        Test.stopTest();
     }
       
     @isTest static void testBulkPostCallout(){
        List<Id> oliIds = new  List<Id>();
        List<OpportunityLineItem> oliToUpdate = new List<OpportunityLineItem>();
        FinishedGoods__c fmn = [SELECT Id, BusinessArea__c, ProductGroupBusinessArea__c, MaterialNumber__c FROM FinishedGoods__c WHERE MaterialNumber__c != '' LIMIT 1];
        fmn.BusinessArea__c = 'ZZ';
        fmn.ProductGroupBusinessArea__c = 'Welding Wire (SZW)';
        update fmn;
        Opportunity opp = [SELECT Id, AppointedDayCalculation__c FROM Opportunity LIMIT 1];
        OrgWideSettings__c orgWideSetting = OrgWideSettings__c.getValues(ConstantClass.ORG_WIDE_INFO);
        Date lastUpdateDate = orgWideSetting.Rawmateriallastupdatedon__c;
        opp.CalculationTimePoint__c = 'Monthly';
        opp.AppointedDayCalculation__c = lastUpdateDate.addMonths(1);
        update opp;
        
        for(OpportunityLineItem oppItem : [SELECT Id, FinishedGoods__r.MaterialNumber__c FROM OpportunityLineItem]){
			oppItem.FinishedGoods__c = fmn.id;
         	oliToUpdate.add(oppItem);
            oliIds.add(oppItem.Id);
        }
        if(!oliToUpdate.isEmpty())
       		update oliToUpdate;
        
        List<InvoicedOrders__c> IOs = [SELECT Id, MaterialNumber__c FROM InvoicedOrders__c];
        IOs[0].MaterialNumber__c = fmn.MaterialNumber__c;
        update IOs;
       	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MocktestRecord());
       	String res = PricingToolController.upadateBulkCOP(oliIds);
        System.assertEquals('true', res, 'upadateBulkCOP should return true');
        Test.stopTest();
	 }
    
      @isTest static void getOpportunityLineItem1Test(){
        OpportunityLineItem oppItem = [SELECT Id, OpportunityId, Quantity, DateOfDelivery__c, PricebookEntryId, TotalPrice, Product2Id, CostOfProduction__c, PriceLevel1__c, PriceLevel2__c,Opportunity.StageName,
                                        PriceLevel3__c,PriceLevel4__c,PriceLevel5__c,OrientationPrice__c,FinalPrice__c,LastSavedFinalPriceDate__c,LastRefreshedDate__c FROM OpportunityLineItem LIMIT 1];
        oppItem.LastSavedFinalPriceDate__c = system.today();
        oppItem.LastRefreshedDate__c = system.today();
        update oppItem;
        Test.startTest();
        List<PricingToolController.PLWrapperData> oppList=PricingToolController.getOpportunityLineItem(oppItem.id);
        System.assertEquals(1, oppList.size(), '1 records should be returned');
        List<PricingToolController.MarginWrapperData> oppMarginList = PricingToolController.getMarginPriceDetails(oppItem.id);
        system.assertEquals(1, oppMarginList.size(), '1 records should be returned');
        Test.stopTest();
    }
     @isTest static void testBulkPostelseCallout(){
        Set<Id> oliIds = new  Set<Id>();
        List<OpportunityLineItem> oliToUpdate = new List<OpportunityLineItem>();
        FinishedGoods__c fmn = [SELECT Id, MaterialNumber__c FROM FinishedGoods__c WHERE MaterialNumber__c != '' LIMIT 1];
        List<ID> OPPIDLST = new List<ID>();
        for(OpportunityLineItem oppItem : [SELECT Id, FinishedGoods__r.MaterialNumber__c,OpportunityId FROM OpportunityLineItem]){
			oppItem.FinishedGoods__c = fmn.id;
         	oliToUpdate.add(oppItem);
            oliIds.add(oppItem.Id);
            OPPIDLST.add(oppItem.OpportunityId);
        }
        List<opportunity> opplst = [SELECT Id, CalculationTimePoint__c FROM Opportunity where ID IN :OPPIDLST];
        for(Opportunity opp : opplst){
           opp.CalculationTimePoint__c = 'Quarterly';  
        }
        OrgWideSettings__c orgWideSetting = OrgWideSettings__c.getValues(ConstantClass.ORG_WIDE_INFO);
        orgWideSetting.Rawmateriallastupdatedon__c = System.today().addMonths(5);   
        opplst[0].AppointedDayCalculation__c = System.today().addMonths(1);
        update opplst;
        if(!oliToUpdate.isEmpty())
       		update oliToUpdate;
         
       	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MocktestRecord());
       	String res = PricingToolController.bulkcallforcop(oliIds);
        System.assertEquals('true', res, 'upadateBulkCOP should return true');
        Test.stopTest();
	}
    
     @isTest static void testWithoutFmnCallout(){
        List<Id> oliIds = new List<Id>();
        List<OpportunityLineItem> oliToUpdate = new List<OpportunityLineItem>();
        for(OpportunityLineItem oppItem : [SELECT Id, FinishedGoods__r.MaterialNumber__c,OpportunityId FROM OpportunityLineItem]){
			oppItem.FinishedGoods__c = null;
            oppItem.ProductFinderStatus__c = ConstantClass.NOMATCHINGSTEEL_FINDERSTATUS;
         	oliToUpdate.add(oppItem);
            oliIds.add(oppItem.Id);
        }
        if(!oliToUpdate.isEmpty())
       		update oliToUpdate;
         
       	Test.startTest();
        String res = PricingToolController.upadateBulkCOP(oliIds);
        System.assertEquals('true', res, 'upadateBulkCOP should return true');
        Test.stopTest();
	}
    
    private class MocktestRecord implements HttpCalloutMock {
        
        public HTTPResponse respond(HTTPRequest request) {
            List<OpportunityLineItem> olis = [SELECT Id FROM OpportunityLineItem];
            
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('[{"salesforce_id": "'+olis[0].Id+'", "fmn": "1234","hzv": "", "price_point_information": "pp0", "alternate_basic_plan": false, "cost_of_production_internal": "1051.930018", "cost_of_production_external": "1051.930018", "fixed_cost": "235.169031", "status_code": 200, "status_message": "OK" }, { "salesforce_id": "'+olis[0].Id+'", "fmn": "1234", "hzv": "", "price_point_information": "pp1", "alternate_basic_plan": false, "cost_of_production_internal": "20.930018", "cost_of_production_external": "30.930018", "fixed_cost": "23.169031", "status_code": 200, "status_message": ""}]');
			response.setStatusCode(200);
            return response; 
        }
    }
} 