force-app/main/default/objects/FinishedGoods__c/FinishedGoods__c.object-meta.xml
<CustomObject>
    <label>Finished Goods</label>
    <nameField>
        <label>Finished Goods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finished Goods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinishedGoods__c/fields/DimensionA__c.field-meta.xml
<CustomField>
    <fullName>DimensionA__c</fullName>
    <label>Dimension A</label>
    <precision>11</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/DimensionB__c.field-meta.xml
<CustomField>
    <fullName>DimensionB__c</fullName>
    <label>Dimension B</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Finished Goods</relationshipLabel>
    <relationshipName>Finished_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/SteelGradeLookup__c.field-meta.xml
<CustomField>
    <fullName>SteelGradeLookup__c</fullName> 
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Steel Grade</label>
    <referenceTo>SteelGrade__c</referenceTo>
    <relationshipLabel>Finished Goods (Steel Grade)</relationshipLabel>
    <relationshipName>Finished_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SteelGrade__c/SteelGrade__c.object-meta.xml
<CustomObject>
    <label>Steel Grade</label>
    <nameField>
        <label>Steel Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steel Grades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/FinishedGoodsController.cls
/****************************************************************************
* Name: FinishedGoodsController
* Author: Harshitha Udaykumar
* Created Date: 17/01/2023
* Description: Controller class for Material Search on OLI.
*****************************************************************************
* Modification log
* Name		Date	           		Description
* Developer Name	Date of Modification	Modification Description  
****************************************************************************/
public with sharing class FinishedGoodsController {
/****************************************************************************
* Author Name: Harshitha Udaykumar
* Description: to Fecth the list of FG records based on the search criteria entered in UI.
* Created Date: 17/01/2023
* Last Modified Date: 
****************************************************************************/
    @AuraEnabled
    public static List<FinishedGoods__c> getFinishedGoods(String FGName, String FGProduct, String FGSteelGrade, Integer FGDimensionA, Integer FGDimensionB, String OLIID){
        List<FinishedGoods__c > FinsihedGoodslst = new List<FinishedGoods__c >();
        String query ;
        if(FGName != null || FGProduct != null || FGSteelGrade != null || FGDimensionA != null || FGDimensionB != null ){
            query = 'SELECT Name, Product__c, SteelGradeLookup__c, Product__r.Name, SteelGradeLookup__r.Name, DimensionA__c, DimensionB__c from FinishedGoods__c WHERE ';
        }
        if (FGName != null) {
            query += 'Name  = :FGName AND ';
        }
        
        if (FGProduct != null) {
            query += 'Product__c   = :FGProduct AND ';
        }
        
        if (FGSteelGrade != null) {
            query += 'SteelGradeLookup__c   = :FGSteelGrade AND ';
        }
        
        if (FGDimensionA != null) {
            query += 'DimensionA__c   = :FGDimensionA AND ';
        }
        
        if (FGDimensionB != null) {
            query += 'DimensionB__c   = :FGDimensionB';
        }
        if(query != null){
            if (query.endsWith('AND ')) {     
                query = query.substring(0, query.length() - 4); 
            }
            String strEsc = String.escapeSingleQuotes(query); 
            FinsihedGoodslst = Database.query(strEsc);
        }
        return FinsihedGoodslst;
    }

}