force-app/main/default/objects/FinishedGoods__c/FinishedGoods__c.object-meta.xml
<CustomObject>
    <label>Finished Goods</label>
    <nameField>
        <label>Finished Goods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finished Goods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinishedGoods__c/fields/Degassing__c.field-meta.xml
<CustomField>
    <fullName>Degassing__c</fullName> 
    <label>Degassing</label>
    <length>1</length>
    <type>Text</type>
</CustomField>
 

force-app/main/default/objects/FinishedGoods__c/fields/HeatTreatment__c.field-meta.xml
<CustomField>
    <fullName>HeatTreatment__c</fullName>
    <label>Heat Treatment (St.29+30)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/HZVCheckTreatment__c.field-meta.xml
<CustomField>
    <fullName>HZVCheckTreatment__c</fullName>
    <label>HZV - Check/Treatment (St.22-25)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/PrimRollingHomogenize__c.field-meta.xml
<CustomField>
    <fullName>PrimRollingHomogenize__c</fullName>
    <label>Prim. Rolling - Homogenize (St.15)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/PrimRollingInputFormat__c.field-meta.xml
<CustomField>
    <fullName>PrimRollingInputFormat__c</fullName>
    <label>Prim. Rolling - Input format (St.16-18)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Finished Goods</relationshipLabel>
    <relationshipName>Finished_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/SurfaceDefectInspec__c.field-meta.xml
<CustomField>
    <fullName>SurfaceDefectInspec__c</fullName>
    <label>Inspec.-Surface defect inspec.(St.38+39)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/USInspection__c.field-meta.xml
<CustomField>
    <fullName>USInspection__c</fullName>
    <label>Inspec.- US Inspection (St.40-42)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterValues__mdt/MasterValues__mdt.object-meta.xml
<CustomObject>
    <label>Master Values</label>
    <pluralLabel>Master Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/MasterValues__mdt/fields/FieldMappedTo__c.field-meta.xml
<CustomField>
    <fullName>FieldMappedTo__c</fullName>
    <label>Field Mapped To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__mdt/Position__mdt.object-meta.xml
<CustomObject>
    <label>Position</label>
    <pluralLabel>Positions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Position__mdt/fields/FieldMappedTo__c.field-meta.xml
<CustomField>
    <fullName>FieldMappedTo__c</fullName>
    <description>The object field this position shall be mapped to in the format (&lt;ObjectAPIName&gt;.&lt;FieldAPIName__c&gt;)</description>
    <label>Field Mapped To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__mdt/fields/IsRequired__c.field-meta.xml
<CustomField>
    <fullName>IsRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will tell if a particular position is required on production key</description>
    <label>Is Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__mdt/fields/PositionNumber__c.field-meta.xml
<CustomField>
    <fullName>PositionNumber__c</fullName>
    <label>Position Number</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production Key</fullName>
            </value>
            <value>
                <fullName>Norms</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/TechnicalRequirement__c.object-meta.xml
<CustomObject>
    <description>Ability to create Standard Inquiry Technical Requirements</description>
    <label>Technical Requirement</label>
    <nameField>
        <label>Technical Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalRequirement__c/fields/CheckTreatment__c.field-meta.xml
<CustomField>
    <fullName>CheckTreatment__c</fullName>
    <label>Check/Treatment (St.11-14)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/CRule__c.field-meta.xml
<CustomField>
    <fullName>CRule__c</fullName>
    <label>C- Rule (St.7+8)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Degassing__c.field-meta.xml
<CustomField>
    <fullName>Degassing__c</fullName>
    <label>Degassing (St.6)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/EndProcessing__c.field-meta.xml
<CustomField>
    <fullName>EndProcessing__c</fullName>
    <label>End Processing (St.36)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/EndProcessingSides__c.field-meta.xml
<CustomField>
    <fullName>EndProcessingSides__c</fullName>
    <label>End Processing Sides (St.37)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Finishing__c.field-meta.xml
<CustomField>
    <fullName>Finishing__c</fullName>
    <label>Finishing (St.45)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/HeatTreatment__c.field-meta.xml
<CustomField>
    <fullName>HeatTreatment__c</fullName>
    <label>Heat Treatment (St.29+30)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Homogenize__c.field-meta.xml
<CustomField>
    <fullName>Homogenize__c</fullName>
    <label>Homogenize (St.27)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/HZVAnnealing__c.field-meta.xml
<CustomField>
    <fullName>HZVAnnealing__c</fullName>
    <label>HZV - Annealing (St.26)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/HZVCheckTreatment__c.field-meta.xml
<CustomField>
    <fullName>HZVCheckTreatment__c</fullName>
    <label>HZV - Check/Treatment (St.22-25)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/HZVSampletest__c.field-meta.xml
<CustomField>
    <fullName>HZVSampletest__c</fullName>
    <label>HZV - Sample test (St.19)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <formula>TEXT( Opportunity__r.Language__c )</formula>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/MultipleStraightening__c.field-meta.xml
<CustomField>
    <fullName>MultipleStraightening__c</fullName>
    <label>Multiple Straightening (St.32)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin (St.2)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Packaging__c.field-meta.xml
<CustomField>
    <fullName>Packaging__c</fullName>
    <label>Packaging (St.46)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Peelingbarwirerod__c.field-meta.xml
<CustomField>
    <fullName>Peelingbarwirerod__c</fullName>
    <label>Peeling bar/ wire rod (St.33)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/PrimRollingHomogenize__c.field-meta.xml
<CustomField>
    <fullName>PrimRollingHomogenize__c</fullName>
    <label>Prim. Rolling - Homogenize (St.15)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/PrimRollingInputformat__c.field-meta.xml
<CustomField>
    <fullName>PrimRollingInputformat__c</fullName>
    <label>Prim. Rolling - Input format (St.16-18)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/ProcessingbeforeHT__c.field-meta.xml
<CustomField>
    <fullName>ProcessingbeforeHT__c</fullName>
    <label>Processing before HT (St.28)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>Technical_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Sampling__c.field-meta.xml
<CustomField>
    <fullName>Sampling__c</fullName>
    <label>Sampling (St.10)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/SpecialInspections__c.field-meta.xml
<CustomField>
    <fullName>SpecialInspections__c</fullName>
    <label>Special Inspections (St.43)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/SteelMillTesting__c.field-meta.xml
<CustomField>
    <fullName>SteelMillTesting__c</fullName>
    <label>Steel Mill Testing (St.9)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/STWCastingFormat__c.field-meta.xml
<CustomField>
    <fullName>STWCastingFormat__c</fullName>
    <label>STW Casting Format (St.3-5)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Surfacedefectinspec__c.field-meta.xml
<CustomField>
    <fullName>Surfacedefectinspec__c</fullName>
    <label>Inspec.-Surface defect inspec.(St.38+39)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/SurfaceTreatment__c.field-meta.xml
<CustomField>
    <fullName>SurfaceTreatment__c</fullName>
    <label>Straightening / SurfaceTreat. (St.31)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/TargetProduct__c.field-meta.xml
<CustomField>
    <fullName>TargetProduct__c</fullName>
    <label>Target Product (St.1)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/TestingFinishedMaterial__c.field-meta.xml
<CustomField>
    <fullName>TestingFinishedMaterial__c</fullName>
    <label>Testing Finished Material (St.44)</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/USHTesting__c.field-meta.xml
<CustomField>
    <fullName>USHTesting__c</fullName>
    <label>HZV - USH Testing (St.20+21)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/USInspection__c.field-meta.xml
<CustomField>
    <fullName>USInspection__c</fullName>
    <label>Inspec.- US Inspection (St.40-42)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translations__mdt/Translations__mdt.object-meta.xml
<CustomObject>
    <label>Translations</label>
    <pluralLabel>Translations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Translations__mdt/fields/TranslatedValue__c.field-meta.xml
<CustomField>
    <fullName>TranslatedValue__c</fullName>
    <label>Translated Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductionKeyInput.cls
/****************************************************************************
* Name: ProductionKeyInput
* Author: Priyanka Kumari
* Created Date: 08/12/2022
* Description: Production Key Screen helper class present on Technical Requirement
*****************************************************************************
* Modification log
* Name    Date                 Description
* Developer Name  Date of Modification  Modification Description  
****************************************************************************/
public with sharing class ProductionKeyInput {
    
    /****************************************************************************
* Author Name: Priyanka Kumari
* Description: Get Data from multiple metadata
* Created Date: 08/12/2022
* Last Modified Date: 
****************************************************************************/
    @AuraEnabled
    public static List<PositionWrapper> getPosition(String recordId){
        List<PositionWrapper> posWrapperList = new List<PositionWrapper>();
        Map<Id, String> positionMap = new Map<Id, String>();
        Map<Id, String> positionMapForFieldValues = new Map<Id, String>();
        Map<String , String> posTranslationPicklistValue = new Map<String, String>();
        Map<Id, Boolean> isRequiredMap = new Map<Id, Boolean>();
        Map<Id, String> posTranslation = new Map<Id, String>();
        Map<String, List<String>> fieldValTranslation = new Map<String, List<String>>();
        Map<Id, Object> finalMap1 = new Map<Id, Object>();
        Map<Id, Object> finalMap = new Map<Id, Object>();
        
        String lang = getUserLanguage();
        Set<String> setOfPFV = new Set<String>();
        String recordtypename = [SELECT Id, Name, RecordtypeId, RecordType.name FROM TechnicalRequirement__c Where Id=:recordId].RecordType.Name;
        if(recordtypename == ConstantClass.TRRECORDTYPENAME){
            for(Position__mdt position : [SELECT Id, MasterLabel, Type__c,FieldMappedTo__c, IsRequired__c, PositionNumber__c
                                          FROM Position__mdt 
                                          WHERE Type__c = :ConstantClass.PRODUCTION_KEY_TYPE  
                                          ORDER BY PositionNumber__c ASC]){
                                              
                                              positionMap.put(position.Id, position.MasterLabel);
                                              String[] FieldMappedTo = position.FieldMappedTo__c.split('\\.');
                                              positionMapForFieldValues.put(position.Id, FieldMappedTo[1]);
                                              isRequiredMap.put(position.Id, position.IsRequired__c);
                                          }
        }
        else if(recordtypename == ConstantClass.TRLIGHTRECORDTYPENAME){
            for(Position__mdt position : [SELECT Id, MasterLabel, Type__c,FieldMappedTo__c, IsRequired__c, PositionNumber__c
                                          FROM Position__mdt 
                                          WHERE Type__c = :ConstantClass.PRODUCTION_KEY_TYPE 
                                          AND MasterLabel IN :ConstantClass.POSITIONS_FOR_SALES
                                          ORDER BY PositionNumber__c ASC]){     
                                              positionMap.put(position.Id, position.MasterLabel);
                                              String[] FieldMappedTo = position.FieldMappedTo__c.split('\\.');
                                              positionMapForFieldValues.put(position.Id, FieldMappedTo[1]);
                                              isRequiredMap.put(position.Id, position.IsRequired__c);
                                          }
        }
        TechnicalRequirement__c TR = [SELECT TargetProduct__c, Origin__c, STWCastingFormat__c, Degassing__c, CRule__c, SteelMillTesting__c, Sampling__c, CheckTreatment__c, HZVSampletest__c, EndProcessing__c,
                                      USHTesting__c ,PrimRollingHomogenize__c, PrimRollingInputformat__c, HZVCheckTreatment__c, HZVAnnealing__c,Homogenize__c,ProcessingbeforeHT__c, HeatTreatment__c,SurfaceTreatment__c, 
                                      MultipleStraightening__c, Peelingbarwirerod__c, EndProcessingSides__c, Surfacedefectinspec__c, USInspection__c, SpecialInspections__c, 
                                      TestingFinishedMaterial__c, Finishing__c, Packaging__c from TechnicalRequirement__c where Id= :recordId LIMIT 1];
        
        Map<String, Object> fieldsMapValues = TR.getPopulatedFieldsAsMap();
        for(Id i :positionMapForFieldValues.KeySet()){              
            for(String fieldmapped : fieldsMapValues.keySet()){                          
                if(positionMapForFieldValues.get(i) == fieldmapped){
                    finalMap.put(i, fieldsMapValues.get(fieldmapped));
                    setOfPFV.add(String.valueOf(fieldsMapValues.get(fieldmapped)));
                }
            }
        }
        for(Translations__mdt trans : [SELECT Id, TranslatedValue__c, Language__c, Position__c, PositionFieldValue__r.Status__c,
                                       PositionFieldValue__c, TranslationNumber__c , PositionFieldValue__r.PicklistValue__c
                                       FROM Translations__mdt 
                                       WHERE Language__c = :lang 
                                       AND (PositionFieldValue__r.PicklistValue__c IN :setOfPFV
                                            AND Position__c IN :finalMap.keySet())
                                            ORDER BY TranslationNumber__c ASC, TranslatedValue__c ASC]){
                                           if(finalMap.get(trans.Position__c) == trans.PositionFieldValue__r.PicklistValue__c)
                                               finalMap1.put(trans.Position__c, trans.TranslatedValue__c);                               
                                       }
        if(recordtypename == ConstantClass.TRRECORDTYPENAME){
            for(Translations__mdt trans : [SELECT Id, TranslatedValue__c, Language__c, Position__c,PositionFieldValue__r.Status__c, 
                                           PositionFieldValue__c, TranslationNumber__c , PositionFieldValue__r.PicklistValue__c
                                           FROM Translations__mdt 
                                           WHERE Language__c = :lang
                                           ORDER BY TranslationNumber__c ASC]){
                                               
                                               if(trans.Position__c != null && trans.PositionFieldValue__c == null){ 
                                                   posTranslation.put(trans.Position__c, trans.TranslatedValue__c);                    
                                               }
                                               if(trans.PositionFieldValue__r.Status__c == 'Active'){
                                                   
                                                   if(trans.Position__c != null && trans.PositionFieldValue__c != null && trans.TranslatedValue__c != null)
                                                   {
                                                       posTranslationPicklistValue.put(trans.PositionFieldValue__r.PicklistValue__c, trans.Position__c +';'+trans.TranslatedValue__c);                 
                                                       
                                                   }
                                                   if(trans.PositionFieldValue__c !=null){                
                                                       if(!fieldValTranslation.containsKey(trans.Position__c))
                                                           fieldValTranslation.put(trans.Position__c, new List<String>());
                                                       
                                                       List<String> list1 = fieldValTranslation.get(trans.Position__c);
                                                       list1.add(trans.TranslatedValue__c);
                                                   } 
                                               }
                                           }
        }
        else if(recordtypename == ConstantClass.TRLIGHTRECORDTYPENAME){ 
            for(Translations__mdt trans : [SELECT Id, TranslatedValue__c, Language__c, Position__c,PositionFieldValue__r.Status__c, Position__r.MasterLabel,
                                           PositionFieldValue__c, TranslationNumber__c , PositionFieldValue__r.PicklistValue__c
                                           FROM Translations__mdt 
                                           WHERE Language__c = :lang AND Position__r.MasterLabel IN :ConstantClass.POSITIONS_FOR_SALES
                                           ORDER BY TranslationNumber__c ASC]){
                                               
                                               if(trans.Position__c != null && trans.PositionFieldValue__c == null){ 
                                                   posTranslation.put(trans.Position__c, trans.TranslatedValue__c);                    
                                               }
                                               if(trans.PositionFieldValue__r.Status__c == 'Active'){
                                                   
                                                   if(trans.Position__c != null && trans.PositionFieldValue__c != null && trans.TranslatedValue__c != null)
                                                   {
                                                       posTranslationPicklistValue.put(trans.PositionFieldValue__r.PicklistValue__c, trans.Position__c +';'+trans.TranslatedValue__c);                 
                                                       
                                                   }
                                                   if(trans.PositionFieldValue__c !=null){                
                                                       if(!fieldValTranslation.containsKey(trans.Position__c))
                                                           fieldValTranslation.put(trans.Position__c, new List<String>());
                                                       
                                                       List<String> list1 = fieldValTranslation.get(trans.Position__c);
                                                       list1.add(trans.TranslatedValue__c);
                                                   } 
                                               }
                                           }
        }
        for(Id fieldValueId : fieldValTranslation.keySet()){
            PositionWrapper posWrapper = new PositionWrapper();
            posWrapper.posLabel = posTranslation.get(fieldValueId);
            List<String> s = new List<String>();
            for(String val : fieldValTranslation.get(fieldValueId)){
                if(val != String.valueOf(finalMap1.get(fieldValueId))){
                    if(s != null)
                        s.add(val);
                }
                else{
                    posWrapper.valueToBeDefaulted = String.valueOf(finalMap1.get(fieldValueId));
                }
            } 
            s.sort();   
            posWrapper.listOfFieldVal = s;
            posWrapper.isRequired = isRequiredMap.get(fieldValueId);
            posWrapperList.add(posWrapper);
        }              
        return posWrapperList;
    }
    
    /****************************************************************************
* Author Name: Priyanka Kumari
* Description: Save data from production key screen to respecitive fields on 
* technical requirement record
* Created Date: 13/12/2022
* Last Modified Date: 
****************************************************************************/
    @AuraEnabled
    public static String saveProductionKey(List<Map<String, String>> resultFromLWC, Id recordId){
        Savepoint sp;
        Map<String, String> posFieldValMap = new Map<String, String>();
        Map<String, String> fieldMapping = new Map<String, String>();
        Map<String, String> mastervalueMap = new Map<String, String>();
        Map<String, String> transMapping = new Map<String, String>();
        Map<String, String> transPosMapping = new Map<String, String>();
        Map<String, String> transvalues = new Map<String, String>();
        Map<String, String> transFinal = new Map<String, String>();
        set<String> setOfPositions = new  set<String>();
        Map<String, String> transpickval = new Map<String, String>();
        try{
            sp = Database.setSavepoint();
            for(Map<String, String> res : resultFromLWC){
                for(String s : res.keySet()){
                    posFieldValMap.put(s, res.get(s));
                }     
            }
            String lang = getUserLanguage();
            for(Translations__mdt trans : [SELECT Id, TranslatedValue__c, Language__c, Position__c, Position__r.MasterLabel, PositionFieldValue__c, PositionFieldValue__r.PicklistValue__c, TranslationNumber__c
                                           FROM Translations__mdt 
                                           WHERE Language__c = :lang
                                           ORDER BY TranslationNumber__c ASC]){
                String translatedValue;                              
                if(trans.TranslatedValue__c!= null) {
                	translatedValue = trans.TranslatedValue__c.replaceAll('(\\s+)', ' ');                    
               	} 
               	if(posFieldValMap.containsKey(translatedValue)){
                    if(trans.Position__c != null && trans.PositionFieldValue__c == null){
                        setOfPositions.add(trans.Position__c);
                        transMapping.put(posFieldValMap.get(trans.TranslatedValue__c), trans.Position__r.MasterLabel);
                        transvalues.put(trans.Position__r.MasterLabel,trans.TranslatedValue__c);
                    }  
                    if(trans.Position__r.MasterLabel == 'HeatTreatment' && trans.PositionFieldValue__c !=null){
                        transpickval.put(trans.PositionFieldValue__r.PicklistValue__c,translatedValue);                                   
                    }
                } 
           	}
            for(Translations__mdt trans : [SELECT Id, TranslatedValue__c, Language__c, Position__c, Position__r.MasterLabel, PositionFieldValue__c, PositionFieldValue__r.PicklistValue__c, TranslationNumber__c
                                           FROM Translations__mdt 
                                           WHERE Language__c = :lang AND Position__c IN :setOfPositions
                                           ORDER BY TranslationNumber__c ASC]){
                String translatedValue;                              
                if(trans.TranslatedValue__c!= null) {
                	translatedValue = trans.TranslatedValue__c.replaceAll('(\\s+)', ' ');                    
               	}
                Set<String> mapValueSet = new Set<String>(posFieldValMap.values());
                if(mapValueSet.contains(translatedValue)){
                    if(trans.PositionFieldValue__c != null){
                		transPosMapping.put(translatedValue, trans.PositionFieldValue__r.PicklistValue__c);
                	}                            
                }                           
           	}
            for(String s : transMapping.keySet()){
            	transFinal.put(transMapping.get(s), transPosMapping.get(s));     
            }
            for(MasterValues__mdt mastervalue : [SELECT Id, Position__r.MasterLabel, FieldMappedTo__c, Value__c, PositionFieldValue__c,PositionFieldValue__r.PicklistValue__c
                                                 FROM MasterValues__mdt 
                                                 WHERE Position__r.MasterLabel IN :transFinal.keySet()]){ 
            	String delimiter = '.'; 
                String value = transvalues.get(mastervalue.Position__r.MasterLabel);
                                                     
                if(transpickval.get(mastervalue.PositionFieldValue__r.PicklistValue__c) == posFieldValMap.get(value)){
                	mastervalueMap.put(mastervalue.Position__r.MasterLabel,mastervalue.Value__c); 
                    String mastervaluestr = (String.valueOf(mastervalue.FieldMappedTo__c)).substringAfter(delimiter);                     
                    fieldMapping.put(mastervaluestr,mastervalueMap.get(mastervalue.Position__r.MasterLabel));
              	}
           	}
            for(Position__mdt position : [SELECT Id, MasterLabel, FieldMappedTo__c 
                                          FROM Position__mdt 
                                          WHERE MasterLabel IN :transFinal.keySet()]){
				if(transFinal.containsKey(position.MasterLabel)){
                	String delimiter = '.';
                    String str = (String.valueOf(position.FieldMappedTo__c)).substringAfter(delimiter);
                    fieldMapping.put(str, transFinal.get(position.MasterLabel)); 
                    if(position.MasterLabel == System.label.HeatTreatment)
                    	fieldMapping.put(str, mastervalueMap.get(position.MasterLabel)); 
                }
           	}
            TechnicalRequirement__c techReq = new TechnicalRequirement__c();
            for(String field : fieldMapping.keySet()){
                if(field =='Inductive__c')
                    techReq.put(field, Boolean.valueOf(fieldMapping.get(field)));
                else
                    techReq.put(field, fieldMapping.get(field)); 
            }
            techReq.put('Id', recordId);
            TechnicalRequirement__c tReq = [SELECT Id, FinishedGoods__r.Active__c,Product__c,Product__r.IsActive from TechnicalRequirement__c where Id= :recordId LIMIT 1];
            if((tReq.FinishedGoods__c !=null && tReq.FinishedGoods__r.Active__c == false) || (tReq.Product__c !=null && tReq.Product__r.IsActive == false)){
                return 'Inactive';
            }
            else{
                if(!(techReq == null)){
                    update techReq;
                    return 'true';
                }
            }
            return 'false'; 
        }
        catch(Exception e){
            Database.RollBack(sp);
            String exdetails = e.getCause() + ' ; '+ e.getLineNumber() + ' ; ' + e.getMessage() + ' ; ' + e.getStackTraceString()
                + ' ; ' + e.getTypeName() ;
            String error = e.getMessage();
            if(error.contains(System.Label.ValidationErrorOnTRForQualitycheck)){
                return System.Label.ValidationErrorOnTRForQualitycheck;
            }
            return exdetails;
        }
    }
    
 /****************************************************************************
* Author Name: Priyanka Kumari
* Description: Get profile for current user
* Created Date: 13/12/2022
* Last Modified Date: 
****************************************************************************/
    @AuraEnabled
    public static Boolean getProfile(){
        
        User user = [SELECT ID, FirstName, LastName, Name, Title, Profile.Name, Email From User WHERE ID = :UserInfo.getUserId() LIMIT 1];
        if(user.Profile.Name == System.label.SystemAdministratorProfile || user.Profile.Name == ConstantClass.SAG_QUALITY_PROFILE || user.Profile.Name == ConstantClass.SAG_SALES_PROFILE || user.Profile.Name == ConstantClass.SAG_MARKETING_PROFILE || user.Profile.Name ==  ConstantClass.SHS_ADMIN)
        {
            return true;
        }
        return false;
    }
    
    /****************************************************************************
* Author Name: Priyanka Kumari
* Description: Get user language
* Created Date: 13/12/2022
* Last Modified Date: 
****************************************************************************/
    @AuraEnabled
    public static String getUserLanguage(){
        
        String language = UserInfo.getLanguage();
        String lang;
        if(language == 'en_US'){
            String[] l = language.split('_');
            lang = String.valueOf(l[0].toUpperCase());
        }
        else
            lang = language.toUpperCase();
        
        return lang;
    }
    
    /****************************************************************************
* Author Name: Priyanka Kumari
* Description: Wrapper class used to pass data feom class to LWC component
* Created Date: 13/12/2022
* Last Modified Date: 
****************************************************************************/
    public class PositionWrapper{
        @AuraEnabled
        public String posLabel {get;set;}
        @AuraEnabled
        public Boolean isRequired {get;set;}
        @AuraEnabled
        public List<String> listOfFieldVal {get;set;}
        @AuraEnabled
        public String valueToBeDefaulted {get;set;}
        
    }   
}