force-app/main/default/objects/FinishedGoods__c/FinishedGoods__c.object-meta.xml
<CustomObject>
    <label>Finished Goods</label>
    <nameField>
        <label>Finished Goods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finished Goods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinishedGoods__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName> 
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>  
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finished Goods</relationshipLabel>
    <relationshipName>Finished_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/FinishedGoods__c/fields/DimensionA__c.field-meta.xml
<CustomField>
    <fullName>DimensionA__c</fullName>
    <label>Dimension A</label>
    <precision>11</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Finished Goods</relationshipLabel>
    <relationshipName>Finished_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/RollingMill__c.field-meta.xml
<CustomField>
    <fullName>RollingMill__c</fullName>
    <label>Rolling Mill</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/SELNumber__c.field-meta.xml
<CustomField>
    <fullName>SELNumber__c</fullName>
    <description>Capture SAP Material numbers for a fiished product</description>
    <label>SEL Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/SteelGrade__c.field-meta.xml
<CustomField>
    <fullName>SteelGrade__c</fullName>
    <label>Steel Grade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinishedGoods__c/fields/SteelGradeLookup__c.field-meta.xml
<CustomField>
    <fullName>SteelGradeLookup__c</fullName> 
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Steel Grade</label>
    <referenceTo>SteelGrade__c</referenceTo>
    <relationshipLabel>Finished Goods (Steel Grade)</relationshipLabel>
    <relationshipName>Finished_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FinishedGoods__c.field-meta.xml
<CustomField>
    <fullName>FinishedGoods__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finished Goods (For Price Caclulation)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FinishedGoods__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FinishedGoods__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SteelGrade__c.field-meta.xml
<CustomField>
    <fullName>SteelGrade__c</fullName>
    <formula>IF(ISBLANK(SemiFinishedGoods__c), FinishedGoods__r.SteelGradeLookup__c, SemiFinishedGoods__r.SteelGrade__c)</formula>
    <label>Steel Grade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TechnicalRequirement__c.field-meta.xml
<CustomField>
    <fullName>TechnicalRequirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The technical requirement that resulted in this OLI</description>
    <label>Technical Requirement</label>
    <referenceTo>TechnicalRequirement__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Flat__c.field-meta.xml
<CustomField>
    <fullName>Flat__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flat</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RollingMill__c/RollingMill__c.object-meta.xml
<CustomObject>
    <label>Rolling Mill</label>
    <nameField>
        <label>Rolling Mill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rolling Mills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RollingMill__c/fields/RollingMill__c.field-meta.xml
<CustomField>
    <fullName>RollingMill__c</fullName>
    <label>Rolling mill</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SteelGrade__c/SteelGrade__c.object-meta.xml
<CustomObject>
    <label>Steel Grade</label>
    <nameField>
        <label>Steel Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steel Grades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SteelGrade__c/fields/ExcludeFromProductFinder__c.field-meta.xml
<CustomField>
    <fullName>ExcludeFromProductFinder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude steel grade from Product Finder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SteelGrade__c/fields/SELNumber__c.field-meta.xml
<CustomField>
    <fullName>SELNumber__c</fullName>
    <label>SEL Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/TechnicalRequirement__c.object-meta.xml
<CustomObject>
    <description>Ability to create Standard Inquiry Technical Requirements</description>
    <label>Technical Requirement</label>
    <nameField>
        <label>Technical Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalRequirement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Use accounts to store information</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>TechnicalRequirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/DimensionA__c.field-meta.xml
<CustomField>
    <fullName>DimensionA__c</fullName>
    <label>Dimension A</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/FinishedGoods__c.field-meta.xml
<CustomField>
    <fullName>FinishedGoods__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Finished goods number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FinishedGoods__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FinishedGoods__c</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>Technical_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use Opportunity to store information</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>TechnicalRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>TechnicalRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Technical Requirements</relationshipLabel>
    <relationshipName>Technical_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity (t)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TechnicalRequirement__c/fields/Rollingmill__c.field-meta.xml
<CustomField>
    <fullName>Rollingmill__c</fullName>
    <label>Rolling mill</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConvertTechReqToOLITest.cls
/****************************************************************************
* Name: ConvertTechReqToOLITest
* Author: Gunjan Saxena
* Created Date: 08/11/2022
* Description: Test class of ConvertTechReqToOLI
*****************************************************************************/
/*****************************************************************************
* Modification log
* Name		        Date	           		Description
* Developer Name	Date of Modification	Modification Description   
****************************************************************************/
@isTest
public class  ConvertTechReqToOLITest {
    @testSetup
    static void setUpData(){
        OpportunityLineItem oli = TestDataFactory.oppLineItemTestData();
        TestDataFactory.createRollingMill(2);
        TestDataFactory.standardPriceBook();
        TestDataFactory.createpriceBookEntry();
       //	List<Opportunity> opplst = TestDataFactory.createOpps(1);
       List<Opportunity> opplst = [Select ID,PriceBook2Id from Opportunity  Limit 1];
       // opplst[0].PriceBook2Id = priceBookEntryData.Pricebook2Id;
       // update opplst;       
        //List<TechnicalRequirement__c> tRlst = TestDataFactory.createTR(1); 
        List<TechnicalRequirement__c> tRlst = [Select ID,Opportunity__c FROM TechnicalRequirement__c LIMIT 1];
        If(tRlst.size() > 0){
            tRlst[0].Opportunity__c = opplst[0].Id;
        }
        update tRlst;        
        List<FinishedGoods__c> fGlst = TestDataFactory.createFG(1);
        FGlst[0].Product__c = oli.Product2Id;
        update FGlst[0];
        TestDataFactory.createSFG(1);
        TestDataFactory.createSteelGrade(1);
        TestDataFactory.createOrgWideSetting();
    }
    
    @isTest static void testOLIRecord(){
        Test.startTest();
        FinishedGoods__c fg = [SELECT Id, Name, SteelGradeLookup__r.SELNumber__c,Product__c FROM FinishedGoods__c LIMIT 1];
        Opportunity opp = [SELECT Id, StageName, PriceBook2Id FROM Opportunity LIMIT 1];
        List<OpportunityLineItem> oli = [SELECT Id,TechnicalRequirement__c from OpportunityLineItem LIMIT 1];
        TechnicalRequirement__c tR = [SELECT Id, Active__c,OpportunityProduct__c, FinishedGoods__c, Quantity__c, Product__c,DimensionA__c FROM TechnicalRequirement__c LIMIT 1];
        tR.Opportunity__c = opp.ID;
        tR.FinishedGoods__c = fg.ID; 
        tr.OpportunityProduct__c = oli[0].Id;
        tr.DimensionA__c = NULL;
        update tR;
        oli[0].TechnicalRequirement__c = tR.Id;
        update oli;
        List<ID> TRSC0lst  = new List<ID>();   
        TRSC0lst.add(tR.ID);
        //Test.startTest();
        ConvertTechReqToOLI.ConvertTechnicalRequirementToOLI(TRSC0lst);
        Test.stopTest();
        system.assertEquals(TR.Active__c, True, 'Technical Requirement should be Active');
    } 
    
     @isTest static void testOLIRecordprd(){
         Test.startTest();
        PriceBookEntry prb = [SELECT Id,  Product2Id FROM PriceBookEntry WHERE  IsActive = true LIMIT 1];
        Opportunity opp = [SELECT Id, StageName, PriceBook2Id FROM Opportunity LIMIT 1];
        List<OpportunityLineItem> oli = [SELECT Id,TechnicalRequirement__c from OpportunityLineItem LIMIT 1];
        TechnicalRequirement__c tR = [SELECT Id, Active__c,OpportunityProduct__c, Opportunity__c, Product__c, FinishedGoods__c, Quantity__c, DimensionA__c FROM TechnicalRequirement__c LIMIT 1];
        tR.Opportunity__c = opp.ID;
        tR.Product__c = prb.Product2Id; 
        tr.OpportunityProduct__c = oli[0].Id;
        tr.DimensionA__c = NULL;
        update tR;
        oli[0].TechnicalRequirement__c = tR.Id;
        update oli;
        List<ID> TRSC0lst  = new List<ID>();   
        TRSC0lst.add(tR.ID);
        //Test.startTest();
        ConvertTechReqToOLI.ConvertTechnicalRequirementToOLI(TRSC0lst);
        Test.stopTest();
        system.assertEquals(TR.Active__c, True, 'Technical Requirement should be Active');
    } 
     @isTest static void testOLIRecordst(){
         Test.startTest();
        PriceBookEntry prb = [SELECT Id,  Product2Id FROM PriceBookEntry WHERE  IsActive = true LIMIT 1];
         Product2 prd = [SELECT Id, Flat__c, Family FROM PRODUCT2 WHERE ID = :prb.Product2Id];
         prd.Flat__c = false;
         prd.Family = 'Wire Rod';
         update prd;
        
         List<SteelGrade__c> STLst = [Select ID,ExcludeFromProductFinder__c from SteelGrade__c];
         for(SteelGrade__c st : STLst){
             st.ExcludeFromProductFinder__c = False;
         }
         update STLst;
        Opportunity opp = [SELECT Id, StageName, PriceBook2Id FROM Opportunity LIMIT 1];
        List<OpportunityLineItem> oli = [SELECT Id,TechnicalRequirement__c from OpportunityLineItem LIMIT 1];
        TechnicalRequirement__c tR = [SELECT Id, Active__c,OpportunityProduct__c, Opportunity__c, Product__c, FinishedGoods__c, Quantity__c, DimensionA__c FROM TechnicalRequirement__c LIMIT 1];
        tR.Opportunity__c = opp.ID;
        tR.Product__c = prb.Product2Id; 
        tr.OpportunityProduct__c = oli[0].Id;
        tr.DimensionA__c = 5;
         tr.Rollingmill__c = '11';
        update tR;
        oli[0].TechnicalRequirement__c = tR.Id;
        update oli;
        List<ID> TRSC0lst  = new List<ID>();   
        TRSC0lst.add(tR.ID);
        //Test.startTest();
        ConvertTechReqToOLI.ConvertTechnicalRequirementToOLI(TRSC0lst);
         system.assertEquals(TR.Active__c, True, 'Technical Requirement should be Active');
        Test.stopTest();
        
    } 
    @isTest static void testinsertOLIRecord(){
        Test.startTest();
        FinishedGoods__c fg = [SELECT Id, Name, SteelGradeLookup__r.SELNumber__c,Product__c FROM FinishedGoods__c LIMIT 1];
        
        Opportunity opp = [SELECT Id, StageName, PriceBook2Id FROM Opportunity LIMIT 1];
        List<OpportunityLineItem> oli = [SELECT Id,TechnicalRequirement__c from OpportunityLineItem LIMIT 1];
        TechnicalRequirement__c tR = [SELECT Id, Active__c,OpportunityProduct__c, FinishedGoods__c, Quantity__c, Product__c,DimensionA__c FROM TechnicalRequirement__c where OpportunityProduct__c = '' LIMIT 1];
        tR.Opportunity__c = opp.ID;
        tR.FinishedGoods__c = fg.ID; 
        tr.OpportunityProduct__c = oli[0].Id;
        tr.DimensionA__c = NULL;
        update tR;
        List<ID> TRSC0lst  = new List<ID>();   
        TRSC0lst.add(tR.ID);
        //Test.startTest();
        ConvertTechReqToOLI.ConvertTechnicalRequirementToOLI(TRSC0lst);
        Test.stopTest();
        system.assertEquals(TR.Active__c, True, 'Technical Requirement should be Active');
    } 
 
    @isTest static void testproductFinderToolbulk(){
        List<Id> technicalRequirementsToConvert = new List<Id> ();
        for(TechnicalRequirement__c tr : [SELECT ID,Product__c,FinishedGoods__c,Opportunity__c,Quantity__c,Account__c FROM TechnicalRequirement__c  ]){
            technicalRequirementsToConvert.Add(TR.Id);
        }
        Test.startTest();
        Map<Id,ConvertTechReqToOLI.FMHZVstatusreturnwrapper> fmmap = ConvertTechReqToOLI.productFinderToolbulk(technicalRequirementsToConvert);
        Test.stopTest();
        System.assert(fmmap.size() > 0,'Map is not null'); 
    }
       
}